[FEAT] 가게 이름 데이터 가공하기
woowacourse-teams/2020-songpa-people pull request #101
Opened 2020-08-03 09:10 UTC by moonyoungCHAE

fixes: #83

2020-08-03 09:50 UTC, ordinCode requested changes
오호 초스피드ㅋㅋㅋㅋ
근데 만약에 "스타벅스 한양대점"가 입력되면 "스타벅스 한양대"가 나오는게 맞는거지?
스타벅스 한양대점도 테스트 추가해주면 좋을 것 같아요.

그래서 그냥 '점'만 없애도록하고 "스타벅스 강남역점"도 "스타벅스 강남역"으로 나오게끔 하는게 어떨까 싶기도하고..
("스타벅스 강남"도 좋은데 
한양대점 ->  한양대
강남역점-> 강남
이렇게 둘다 적용되게 하는건 복잡할것 같아서)

2020-08-03 10:01 UTC, moonyoungCHAE commented
> 오호 초스피드ㅋㅋㅋㅋ
> 근데 만약에 "스타벅스 한양대점"가 입력되면 "스타벅스 한양대"가 나오는게 맞는거지?
> 스타벅스 한양대점도 테스트 추가해주면 좋을 것 같아요.
> 
> 그래서 그냥 '점'만 없애도록하고 "스타벅스 강남역점"도 "스타벅스 강남역"으로 나오게끔 하는게 어떨까 싶기도하고..
> ("스타벅스 강남"도 좋은데
> 한양대점 -> 한양대
> 강남역점-> 강남
> 이렇게 둘다 적용되게 하는건 복잡할것 같아서)


> 오호 초스피드ㅋㅋㅋㅋ
> 근데 만약에 "스타벅스 한양대점"가 입력되면 "스타벅스 한양대"가 나오는게 맞는거지?
> 스타벅스 한양대점도 테스트 추가해주면 좋을 것 같아요.
> 
> 그래서 그냥 '점'만 없애도록하고 "스타벅스 강남역점"도 "스타벅스 강남역"으로 나오게끔 하는게 어떨까 싶기도하고..
> ("스타벅스 강남"도 좋은데
> 한양대점 -> 한양대
> 강남역점-> 강남
> 이렇게 둘다 적용되게 하는건 복잡할것 같아서)

앗 이거 내가 실수한거다!!!!
스타벅스 한양대점 -> 스타벅스한양대
스타벅스 강남역점 -> 스타벅스강남역
이렇게 수정할게 땡큐!

2020-08-03 12:39 UTC, pci2676 approved these changes
무난하네요!

2020-08-03 14:33 UTC, giantim requested changes
타미 수고많았어요~
리뷰 몇가지 남겼는데 답변 주시면 될 것 같아요 :)

2020-08-03 14:33 UTC, giantim commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
> +        if (parsedPlaceName.endsWith("점")) {
메서드 접근제어자가 ```public``` 보다는 ```private``` 가 더 낫지 않을까요?
dto 만들때만 쓰이니까 이 클래스 이외에서는 사용할것 같지는 않네요 :)

2020-08-03 14:33 UTC, giantim commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
> +        if (parsedPlaceName.endsWith("점")) {
상수를 추출해서 관리하면 어떨까요?

2020-08-03 14:33 UTC, giantim commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstagramCrawlerTest.java
> +        assertThat(actual).isEqualTo(expected);
```assertThat``` 구문을 한 줄 띄어서 작성해주면 테스트 코드를 읽을 때 가독성이 더 좋아질 것 같습니다 :)

2020-08-03 14:33 UTC, giantim commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstagramCrawlerTest.java
> +    void parsePlaceName(String placeName, String expected) {
```parsePlaceName``` 메서드를 ```private``` 로 바꾼다면 ```crawler``` 메서드를 이용해서 테스트 하는 구조로 바뀔 수 있을 것 같네요!

2020-08-03 14:41 UTC, ordinCode approved these changes

2020-08-04 03:52 UTC, DunDung approved these changes
고생하셨습니다 타미 💯 
저는 instagramScheduler모듈에서 가공하는 걸로 알고있었는데 크롤러 모듈에서 하셨군요!
InstagramScheduler모듈의 Service 클래스에서 가공해주는건 어떻게 생각하세용?
```java
        return places.stream()
                .map(place -> crawlerWithProxy.crawlInstagram(place, START_TRY_COUNT))
                .filter(Optional::isPresent)
                .map(optional -> optional.orElseThrow(NullPointerException::new))
                .filter(CrawlingResult::isOverMinHashtagCount)
                .collect(Collectors.toList());
```
요쪽에 map으로 들어가면 좋을 것 같아서요!

2020-08-04 08:25 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
> +        if (parsedPlaceName.endsWith("점")) {
여기는 상수로 추출하면 오히려 알아보기 어려울 수 있을 것 같아서 안 뺐는데 어떻게 생각하세요?

2020-08-04 08:29 UTC, giantim approved these changes

2020-08-04 08:30 UTC, moonyoungCHAE commented
> 고생하셨습니다 타미 💯
> 저는 instagramScheduler모듈에서 가공하는 걸로 알고있었는데 크롤러 모듈에서 하셨군요!
> InstagramScheduler모듈의 Service 클래스에서 가공해주는건 어떻게 생각하세용?
> 
> ```java
>         return places.stream()
>                 .map(place -> crawlerWithProxy.crawlInstagram(place, START_TRY_COUNT))
>                 .filter(Optional::isPresent)
>                 .map(optional -> optional.orElseThrow(NullPointerException::new))
>                 .filter(CrawlingResult::isOverMinHashtagCount)
>                 .collect(Collectors.toList());
> ```
> 
> 요쪽에 map으로 들어가면 좋을 것 같아서요!

이것도 좋은 의견이네요. 하지만 내부에서 예외 사항을 처리해주는 게 더 깔끔할 것 같다는 생각도 드네요.
Service는 InstagramScheduler의 내부 구조를 모르는 상황으로 생각해봤어요.

2020-08-04 08:47 UTC, merged