[FEAT} 상세 모달 구현
woowacourse-teams/2020-songpa-people pull request #102
Opened 2020-08-03 09:50 UTC by DunDung

![image](https://user-images.githubusercontent.com/33235211/89169856-c771a000-d5b9-11ea-9032-209fbb2a26ba.png)

이미지 높이를 맞추는 건 새로 이슈를 파겠습니다..

2020-08-03 10:15 UTC, ordinCode approved these changes
넘나 고생했으
일단 네이밍 더 고민해볼 부분이나 v-bind: 생략가능한거 이런거는 내가 바톤받아서 controller구현하면서 조금 리펙토링해보겠음다 일단 approve 할게요

2020-08-03 13:15 UTC, pci2676 requested changes
리뷰 해둔 부분 반영해주세요~

이미지 사각형으로 나오게 하는건 css를 잘 못해서 모르겠네요~

2020-08-03 13:15 UTC, pci2676 commented on hashtagmap-web/front/src/views/DetailModal.vue
> +}
![image](https://user-images.githubusercontent.com/13347548/89186098-4c6ab280-d5d6-11ea-98c0-93572e593e30.png)


```suggestion
#instagram-page-button,
#detail-info {
  width: 20%;
  height: 3.5vw;
  font-size: 1.5vw;
  margin-right: 0.7vw;
  border: fuchsia 1.5px solid;
  box-sizing: content-box;
}
```

추가해 주세요 텍스트가 자유 분방해 졌네요~

2020-08-03 14:21 UTC, giantim requested changes
둔덩 고생하셨습니다.
vuex를 정말 잘 다루시네요! 앞으로도 프론트에서 활약 기대할께요 👍 
저도 비밥이 지적한대로 가게 이름이 긴 장소에 대해서 텍스트 위치가 깨지는 부분 수정이 완료되면 approve 하도록 하겠습니다.

2020-08-04 03:57 UTC, DunDung commented on hashtagmap-web/front/src/views/DetailModal.vue
> +}
width: 20% 때문에 box-sizing을 추가해도 벗어나길래
width를 제거했슴다 !

2020-08-04 04:31 UTC, pci2676 approved these changes

2020-08-04 11:47 UTC, moonyoungCHAE approved these changes
둔덩 모달 구현하느라 정말 수고했어요 !!! :)
기능 구현하느라 시간 많이 걸렸을 것 같아요.
아직 프론트쪽 구조가 조금 중구난방 같은데 Place Class 만들면 많이 개선될 것 같아요.

2020-08-05 00:44 UTC, giantim approved these changes

2020-08-05 00:58 UTC, wmakerjun requested changes
👏 👏 👏 
프론트엔드의 꽃은 지도를 다룰 때부터라고 보통 하는데, 쉽지 않은 도전을 이렇게 한스텝씩 구현해 나가는게 너무 멋진 것 같아요~! 몇가지 피드백을 남겼는데요. 나중에 한번에 고치기 어려울까봐 이번에 꼭 고쳤으면 하는거는 html tag에 id는 꼭 필요한 곳에만 넣어주면 좋을 것 같아요. 그리고 vue나 react의 경우에는 virtual dom을 쓰기 때문에 직접적으로 dom에 접근하기 위한 id값을 잘 쓰지 않아요. 그래서 가능하면 id라는 속성을 사용하지 않는 방법을 고민하면 더 좋은 프론트엔드 코드가 될 것 같습니다~! 너무 수고했구요 이따 뵙겠습니다 😄

2020-08-05 00:58 UTC, wmakerjun commented on hashtagmap-web/front/src/views/DetailModal.vue
> +              :key="image.id"
👍

2020-08-05 00:58 UTC, wmakerjun commented on hashtagmap-web/front/src/views/DetailModal.vue
> +                id="post-image"
id로 선언해야하는 이유가 있을까요? 🤔 id는 한 document에서 유일하게 존재해야하는 값인데, 여기서 꼭 id를 써야하는지 궁금해요~

2020-08-05 00:58 UTC, wmakerjun commented on hashtagmap-web/front/src/views/DetailModal.vue
> +    makeHashtagCount() {
computed 속성을 잘 사용하고 있군요 👍

2020-08-05 00:58 UTC, wmakerjun commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +    ...mapGetters(["getPlaces"]),
보통 mapGetters는 상태가 변경될 경우에만 새로 렌더링하기 위해 `computed`에서 선언해줘요 😄 
[공식 가이드 문서](https://vuex.vuejs.org/kr/guide/getters.html)에서도 확인 가능한 부분이니 참고해주면 좋을 것 같아요~

2020-08-05 00:58 UTC, wmakerjun commented on hashtagmap-web/front/src/store/index.js
>      places: [
mock 데이터는 따로 mock.js와 같이 따로 파일로 분리해서 재사용하는 방식이 좋을 것 같아요 😄

2020-08-05 00:58 UTC, eastjun commented on hashtagmap-web/front/src/views/DetailModal.vue
> +          <p id="place-title">{{ nowPlaceByDetailModal.title }}</p>
반드시 id로 선언해야하는 이유가 있을까? 🤔

2020-08-05 00:58 UTC, eastjun commented on hashtagmap-web/front/src/store/index.js
>        return state.places.map(function(place) {
다른 곳에서는 화살표 함수를 사용했는데 여기서는 `function` 키워드로 구현한 이유가 있을까요~? 가능하면 컨벤션을 맞추면 더 좋은 코드가 될 것 같아요 😄

2020-08-05 00:58 UTC, eastjun commented on hashtagmap-web/front/src/store/index.js
>            place.latitude,
이 부분은 아래처럼 작성하면 코드가 더 짧아질 것 같아요 😄 
혹시해서 말씀 드리자면 const { ... } = palce
이렇게 작성하는 방법은  [구조 분해 할당](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) 이라는 방법이에요~
```javascript
 const { id, title, latitude, longitude, hashtag_count, } = place
        return {
          id,
          title,
          hashtag_count,
          latlng: new state.kakaoMapApi.LatLng(latitude, longitude)
        }
```

2020-08-05 00:58 UTC, eastjun commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +        this.kakaoMapApi.event.addListener(marker, EVENT_TYPE.CLICK, () => {
이벤트를 바인딩할 때, 콜백함수의 경우 따로 분리해서 주소값만 작성해주는게 더 좋은 것 같아요.
왜냐하면 지금은 클릭했을 때 어떻게 처리하는지 코드를 다 봐야 알지만, `onAddModalToTextBallon` 이런식으로 따로 분리하여 구현하면, 이 한줄만 읽어도 어떤 역할을 하는지 더 명확할 것 같아요~

2020-08-05 00:58 UTC, eastjun commented on hashtagmap-web/front/src/views/KakaoMap.vue
>        places.forEach(place => {
특정 객체 또는 배열을 순회할 때 `forEach`는 보다 신중하게 사용해야하는 경우가 많아요. 
[링크](https://frontdev.tistory.com/entry/JS-Map-vs-ForEach)를 참조해주면 좋을 것 같은데요. `forEach`는 원래의 배열값을 직접 변형하기 때문에, 때론 원치 않는 에러를 발생시킬수도 있어요 😭

2020-08-05 04:06 UTC, wmakerjun approved these changes
빠르게 피드백 반영해주셨군요 💯 
밀리지 않게 저도 자주자주 피드백 드릴게요 넘넘 고생하셨습니다 😄

2020-08-05 04:12 UTC, DunDung commented
```javascript
    onAddModalToTextBalloon(place) {
      return event => {
        event.preventDefault();
        this.showDetailModal(place);
      };
    },
```
이 이벤트를 단축키로 분리해봤는데 return이 있더라구요..
그래서 return을 지워봤는데 동작을 안합니다..
근데 제가 봤었던 이런 메서드에서는 return을 본

2020-08-05 04:40 UTC, merged