[FEAT] Kakao Admin에서 Scheduler 주기 관리
woowacourse-teams/2020-songpa-people pull request #112
Opened 2020-08-05 05:55 UTC by moonyoungCHAE

2020-08-05 07:18 UTC, pci2676 requested changes
CustomResponse에 대한 제네릭이 거의다 없네요!

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/front/src/store/index.js
> +  },
common module로 빼서 관리해주세요

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +          console.log(res);
불필요한 로그를 남기지 말아주세요.

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/service/KakaoService.java
> +        return CustomResponse.of("카카오 스케줄러 주기가 변경되었습니다.");
메세지를 굳이 내려줄 필요가 있을까요?
성공 여부는 HttpStatus로 알수 있을것 같아요

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/service/KakaoService.java
> +    public CustomResponse changeSchedulePeriod(String expression) {
제네릭이 빠져있네요

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/service/KakaoService.java
> +    @Transactional(readOnly = true)
굳이 트랜잭션을 걸지 않아도 될 것 같아요.
오히려 성능 병목이 일어날 수 있을것 같아요

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/kakao/schedule/PeriodHistory.java
> +    private Long id;
BaseEntity를 상속받았는데 불필요하지 않을까요?
아래에 changedDate도 동일한 필드라고 생각되네요.

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/kakao/schedule/PeriodHistory.java
> +        this.member = "";
굳이 빈 문자열로 넣지않고 null로 처리해도 될것같아요.

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/CronPeriod.java
>          this.trigger = new CronTrigger(expression, TIME_SEOUL);
아니면 이부분 전체를 try catch로 잡아두어도 괜찮을것 같아요
```suggestion
        try {
            this.trigger = new CronTrigger(expression, TIME_SEOUL);
        } catch (IllegalArgumentException e) {
            throw new KakaoSchedulerException(KakaoSchedulerExceptionStatus.INVALID_PERIOD_EXPRESSION);
        }
```

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/CronPeriodTest.java
> +    @ValueSource(strings = {"", "* * * * * * /", "* - * - *", "L * * * * *"})
잘못된 문자열 데이터가 서로다른 error 결과를 반환하면 의미있을것 같은데
"* * * * * * /", "* - * - *", "L * * * * *"
위 세개 데이터는 딱히 세번 테스트할 필요가 있을까요?

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +              })
아래 get은 axios.get 으로 붙여서 만들어 주셨는데 이쪽은 일부러 이렇게 해두신건가요?

2020-08-05 07:18 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/controller/KakaoScheduleController.java
> +    public CustomResponse changeSchedulePeriod(@RequestBody String expression) {
제네릭 채워주세요~

2020-08-05 11:23 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/CronPeriodTest.java
> +    @ValueSource(strings = {"", "* * * * * * /", "* - * - *", "L * * * * *"})
저는 길이에 따라 다른 에러를 반환하는 줄 알았는데 아니였네요!
수정했습니다 ~~

2020-08-06 01:34 UTC, ordinCode approved these changes
타미 생각보다 쉽지않은 작업이었을텐데 고생많았습니다.

2020-08-06 01:34 UTC, ordinCode commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +      axios
지금 return을 빼먹은거 같네요
현재는 공란이 들어와도 아래 axios.put이 동작하는것 같아요

2020-08-06 01:34 UTC, ordinCode commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +    },
지금보니까 비동기통신으로 주고받는 데이터는 성공실패여부밖에 없는 것 같네요.
이런 경우에는 준이 피드백 준게 있었는데 그걸 공유하면 좋을 것 같습니다.

https://github.com/woowacourse-teams/2020-songpa-people/pull/107 의 중간에 try~catch로 잡는거 피드백 참고!

그러면 아마 아래와 같은 모습이 되지 않을까 싶습니다

~~~javascript
      try {
        await axios.put("/kakao/scheduler/period", this.expression, {
          headers: {
            "Content-Type": "application/json"
          }
        });
        this.$store.commit("SHOW_SNACKBAR", {
          type: SNACK_BAR_TYPE.SUCCESS,
          message: MESSAGE.CHANGE_PERIOD
        });
      } catch (e) {
        this.$store.commit("SHOW_SNACKBAR", {
          type: SNACK_BAR_TYPE.ERROR,
          message: e.response.data.message,
          code: e.response.data.code
        });
      } finally {
        this.expression = "";
      }
~~~

2020-08-06 01:34 UTC, ordinCode commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +      });
요부분도 고치자면 아래와 같이?

~~~javascript
    async showPeriodHistory() {
      this.periods = [];
      try {
        const res = await axios.get("/kakao/scheduler/period");
        console.log(res);
        if (res.data.data) {
          res.data.data.map(period =>
            this.periods.push({
              changedDate: period.changedDate,
              expression: period.expression,
              member: period.member
            })
          );
        }
      } catch (e) {}
~~~

2020-08-06 01:34 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/controller/PageController.java
> +    }
👍
저랑 둔덩은 "index"으로 해서 properties에 subfix로 .html을 줬어요. 이부분은 통일하는거 어때요?

2020-08-06 04:16 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +      axios
앗 그러네요! 감사합니다 :)

2020-08-06 04:44 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +    },
오 좋은 피드백 감사합니다 ^_^

2020-08-06 05:03 UTC, DunDung approved these changes
고생하셨습니다 💯 
간단한 리뷰 남겼어요 !

2020-08-06 05:03 UTC, DunDung commented on hashtagmap-admin/front/src/components/CustomSnackBar.vue
> +    }
computed에 ...mapState를 달면 더 깔끔해지는데 반영해주실 생각있나욤?

2020-08-06 05:03 UTC, DunDung commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +      },
indent 안맞는거 아닌가요?

2020-08-06 05:03 UTC, DunDung commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +    data: () => ({
data 형식 통일 까먹으실까봐 적어놓슴니다.

2020-08-06 05:03 UTC, DunDung commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +          message: MESSAGE.NO_INPUT
vuex에 있는 내용은 mutation을 호출해서 바꾸는게 좋아보여요~!!

2020-08-06 05:03 UTC, DunDung commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/exception/KakaoSchedulerExceptionStatus.java
> +    private final String message;
한 줄 띄어주세요/'~

2020-08-06 05:03 UTC, giantim requested changes
타미 수고하셨어요 :)
테스트코드를 꼼꼼히 잘 작성하셨네요!
간단한 리뷰 몇가지 남겼습니다 :)

2020-08-06 05:03 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/controller/KakaoScheduleController.java
> +public class KakaoScheduleController {
카카오 스케쥴러만 이용하는 컨트롤러이니까 ```@RequestMapping("/kakao/scheduler")``` 로 매핑해주는 것은 어떨까요?

2020-08-06 05:03 UTC, giantim commented on hashtagmap-admin/src/main/resources/application.yml
> +    active: local
이슈 내용을 구현할 때 실제 데이터베이스와 통신이 필요없어서 local 환경이 필요한 것 같은데 이럴때는 해당 모듈에 있는 application.yml 이 아닌 ```hashtagmap-core/src/main/resources/application-db.yml``` 의 active 를 수정해서 테스트 해주세요 :)

2020-08-06 05:03 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/integration/KakaoScheduleIntegrationTest.java
> +class KakaoScheduleIntegrationTest {
클래스 내부에서만 사용하는 @BeforeEach, @AfterEach, 다른 메서드들의 접근 제어자를 private 로 바꿔주세요 :)

2020-08-06 05:03 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/service/KakaoServiceTest.java
> +class KakaoServiceTest {
통합테스트 코드에 남긴 리뷰와 동일합니다 :)

2020-08-07 03:37 UTC, giantim approved these changes

2020-08-07 04:06 UTC, pci2676 approved these changes

2020-08-07 04:08 UTC, merged