Feature/2020 songpa people 96
woowacourse-teams/2020-songpa-people pull request #114
Opened 2020-08-07 01:32 UTC by DunDung

오랜만에 문서화 적용하느라 시간이 쫌 걸렸슴다.  미안함다~~
fixes #96

2020-08-07 04:17 UTC, pci2676 requested changes

2020-08-07 04:17 UTC, pci2676 commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/doc/ApiDocumentUtils.java
> +                        .host("docs.api.com")
여기서 명시한 host가 문서에서 설명하는 api를 호출하기 위한 host를 의미하는 건가요?
만약 그렇다면 hashtagmap의 호스트가 되어야 하는것 아닌가요?

2020-08-07 04:17 UTC, pci2676 commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/service/InstagramQueryService.java
> +    @Transactional(readOnly = true)
불필요한 트랜잭션인것 같아요
성능 병목이 발생할 수 있는 포인트 같습니다

2020-08-07 04:25 UTC, ordinCode approved these changes
고생했습니다.
지금 조금 걸리는 부분 몇가지 있는데 함께 생각해보면 좋을 것 같아요

1. maps/markers 라는 url이 restful한가?
  maps에 관련된 api인것도 맞는데 추후 어떤 api들이 생길지에 따라서 좋은 네이밍이 될 것 같기도하고, 아닐것 같기도 해서요 혹시 get("/places") 나 get("/markers/) 는 어떨까 싶기도합니다.

2. "maps/markers"주소로 통신한 결과는 MarkerResponse를 내려주는데 응답 데이터를 할당하는 변수는 places인것이 어색한 부분이 있네요. 가독성이 떨어지는 부분이 있어서 통일된 네이밍을 사용하는 방법을 찾아보면 좋을 것 같아요.

3. .data.data 이부분은 아마 axios자체에서 설정으로 개선할수도 있을 것 같은데 추후 이슈로 따서 개선할수 있는지 보죠!

고생했습니다!

2020-08-07 04:25 UTC, ordinCode commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/api/MapApiControllerTest.java
> +        );
mock 처리부분이 좀 복잡한것 같아서
~~~java
Arrays.asList(
                MarkerResponse.from(Instagram.builder()
                        .place(Place.builder()
                                .placeName("스타벅스")
                                .kakaoId("777")
                                .location(new Location(new Point("1", "2"), null))
                                .build())
                        .id(1L)
                        .hashtagCount(10000L)
                        .build())
~~~
이부분을 변수로 분리하는쪽에 한표 던지고 싶네요
만약에 이렇게 하는걸로 정해지면 다른 테스트에서도 일괄 적용해주세요

2020-08-07 04:41 UTC, moonyoungCHAE approved these changes
둔덩 수고하셨어요 빠른 수정 부탁드릴게요

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/MapController.java
> +    public CustomResponse<List<MarkerResponse>> findAllMarkers() {
HttpStatus도 달아주세요

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/MarkerResponse.java
> +    private MarkerResponse(String placeName, String kakaoId, Long hashtagCount,
parameter가 4개 이상으로 많을 때에는 builder를 만들면 어떨까요?

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/MapController.java
> +    private final InstagramQueryService instagramQueryService;
InstagramQueryService  -> InstagramService  으로 바꾸면 어떤가요?

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/MapApiController.java
> +    public CustomResponse<List<MarkerResponse>> findAllMarkers() {
HttpStatus 달아주세여~

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/MarkerResponse.java
> +    public MarkerResponse(String placeName, String kakaoId, Long instagramId, Long hashtagCount,
지금 사용하는 곳이 from만 있어서 private으로 해도 되겠네요

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/api/MapApiControllerTest.java
> +                .addFilter(new ShallowEtagHeaderFilter())
불필요한 필터네요!

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/api/MapApiControllerTest.java
> +                .apply(documentationConfiguration(restDocumentation))
문서화를 위한 테스트는 별도로 빼는 게 관리하는데 더 편할 것 같아요!

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/service/InstagramQueryServiceTest.java
> +    @DisplayName("findAllMarkers 테스트")
DisplayName 좀 더 자세하게 써주세요

2020-08-07 04:41 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +    ...mapState(["kakaoMap", "kakaoMapApi", "places"]),
mapState보다는 mapGetters가 어떨까요

2020-08-07 07:39 UTC, giantim approved these changes
둔덩 고생 많았어요 :)
이번 이슈에 대해서 가장 늦게 리뷰를 남겼는데 다른 분들이 남겨놓으신 내용 이외의 리뷰 내용은 찾지 못했네요.....
공감한 내용에 대해 로켓 마크 달아놓았습니다!

2020-08-07 08:36 UTC, DunDung commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/doc/ApiDocumentUtils.java
> +                        .host("docs.api.com")
맞네요! 수정했습니다 :)

2020-08-07 08:37 UTC, DunDung commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/service/InstagramQueryService.java
> +    @Transactional(readOnly = true)
좋은 지적 감사합니다!
패치 조인으로 한 번에 가져오도록 수정했슴다.

2020-08-07 08:46 UTC, DunDung commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +    ...mapState(["kakaoMap", "kakaoMapApi", "places"]),
[stackoverflow](https://stackoverflow.com/questions/49696542/differences-b-n-mapstate-mapgetters-mapactions-mapmutations-in-vuex) 저도 궁금해서 찾아봤는데 이 글에 관련 내용이 있어요.
mapState는 state에 있는 값을 그대로 사용할 때 쓰고 mapGetters는 계산된 고정된 값을 가져오는게 맞는 것 같아요!

2020-08-07 09:26 UTC, DunDung commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/api/MapApiControllerTest.java
> +        );
변수 분리하는 쪽이 더 가독성이 좋은 것 같아요!
다른 테스트까지 일괄 적용했슴다 :)

2020-08-07 09:30 UTC, DunDung commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/MapController.java
> +    private final InstagramQueryService instagramQueryService;
오프라인으로도 얘기했지만 우선 일반적인 패턴을 따르는 것으로 가겠습니다 ..!

2020-08-07 09:31 UTC, DunDung commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/MarkerResponse.java
> +    public MarkerResponse(String placeName, String kakaoId, Long instagramId, Long hashtagCount,
private로 하고 builder 패턴도 적용했슴다 : )

2020-08-07 10:07 UTC, pci2676 approved these changes

2020-08-08 07:01 UTC, DunDung commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/api/MapApiControllerTest.java
> +                .apply(documentationConfiguration(restDocumentation))
처음엔 그럴 필요 없다고 생각했는데 분리해보니 훨씬 좋네요! 감사합니다 :)

2020-08-08 08:47 UTC, merged