[FEAT] Admin에서 Kakao Scheduler 시작/종료 관리
woowacourse-teams/2020-songpa-people pull request #120
Opened 2020-08-09 18:55 UTC by pci2676

## Java
- 서비스 CQRS 패턴으로 나눴음
  - Controller까지 나누고 싶긴한데.. 고민
- 통합테스트는 작성했는데 문서화 테스트 작성은 지금 issue에서 하는 일이 너무 많아서 다른 이슈로 등록해서 작성하는게 나을것 같음

## Vue
- vuex 코드에서 [공식문서](https://docs.vuestorefront.io/guide/vuex/vuex-conventions.html)에서 권장하는 네이밍으로 변경했음
  - 꼭 보고 다들 고치는 방향으로 하는게 좋을듯..
- axios 사용하는것도 글로벌에서 사용하고 있던것 각 store 모듈로 변경했음
  - 일단은 kakao 쪽만 insta쪽은 리팩토링 이슈따는게 좋을듯
- snackbar 전역등록도 전역아니게 바꿨음

closes #27

2020-08-10 04:55 UTC, ordinCode requested changes
비밥 많은 내용을 구현해주었네요.
프론트쪽도 코드가 깔끔해지고 좋았습니다. 그래서 한편으로는 최우선으로 머지되어야할 pr이라는 생각도 드네요
몇가지 코멘트 남겼습니다. 비밥의 생각을 달아주세요

2020-08-10 04:55 UTC, ordinCode commented on hashtagmap-admin/front/src/request/index.js
> +}
이건 아직 미완성상태인가요?
어떤의도로 만들었는지 궁금합니다. 그냥 바로

```javascript
function customAxios(timeout) {
    return createAxios(timeout);
}
```
해도되는거였을텐데

2020-08-10 04:55 UTC, ordinCode commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +        });
customAxios 만든거 깔끔하고 좋았던거 같아요.
보통 헤더는 콘텐트타입을 위와 같이 자주 주니까 애초에 axios 인스턴스를 만들때 헤더는 정의 해주는건 어떤가요?

```
const instance = axios.create({
  ...
  headers: {'X-Custom-Header': 'foobar'}
});
```

딱히 저게 필요없는 통신일 경우에는 불필요한 비용일까요?

2020-08-10 04:55 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleQueryService.java
> +                .map(PeriodHistory::toDto)
보통 dto구조가 바뀌는 경우가 많나요, entity가 바뀌는 경우가 많나요?
제 생각에는 아무래도 dto가 바뀌는 경우가 많을 것 같은데 PeriodHistory로부터 dto를 만들지말고 dto에서 PeriodHistory를 받아 dto를 만드는게 유지보수에 더 좋을 것 같습니다.

2020-08-10 04:55 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/kakao/schedule/model/Schedule.java
> +    private String userName;
editor라는 네이밍은 어떨지 조심스럽게 제시

2020-08-10 05:46 UTC, giantim requested changes
비밥 고생하셨습니다 :)
옆에서 보면서 에러 바로 수정해 주셔서 그 외에는 크게 리뷰 남길 내용이 없네요.
코드 스타일에 따른 몇 가지 리뷰 남겼습니다!

2020-08-10 05:46 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/api/KakaoSchedulerController.java
> +    public CustomResponse<Void> toggleScheduler(@RequestBody final KakaoScheduleToggleDto kakaoScheduleToggleDto) {
여기 RequestBody 에 대한 Valid 어노테이션이 빠졌습니다 :)
405 에러도 해결해 주세요 :)

2020-08-10 05:46 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/config/schedule/KakaoScheduleAutoConfigurationTest.java
> +    @Autowired
컨벤션으로 공백 한줄이요 ! :)

2020-08-10 05:46 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/config/schedule/KakaoScheduleAutoConfigurationTest.java
> +    void tearDown() {
tearDown은 테스트 코드 실행 후 실행되니 테스트 메서드 아래에 위치하면 가독성이 더 좋아질것 같네요 :)

2020-08-10 05:46 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandServiceTest.java
> +    void tearDown() {
위에 비슷한 리뷰 남겼습니다 :)

2020-08-10 05:46 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleQueryServiceTest.java
> +    @Autowired
위에 비슷한 리뷰 남겼습니다 :)

2020-08-10 08:37 UTC, DunDung commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +    },
```javascript
    getExpression(state) {
      return state.expression;
    },
```
이런식으로 하기로 컨벤션 정했었는데
혹시 mutation과 다르게 getter만 화살표를 쓰신 이유가 있나요?

2020-08-10 08:37 UTC, DunDung commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/api/KakaoSchedulerController.java
> +}
Service에서 Dto를 리턴하고 컨트롤러에서  CustomResponse로 포장하도록 수정하는게 좋을 것 같아요!

2020-08-10 08:37 UTC, DunDung commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandService.java
> +    private Schedule findScheduleByTarget(final String name) {
이 메소드에는 특별히 파라미터에 final이 붙어있는 이유가 궁금합니다!

2020-08-10 08:52 UTC, pci2676 commented on hashtagmap-admin/front/src/request/index.js
> +}
의도는 customeAxios에 각종 설정을 넣어주기 위해서 했습니다.
지금 하기에는 이슈 상태가 너무 커져서 추후 이슈로 하는게 나을것 같아서 일단 멈췄습니다!

2020-08-10 08:52 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +        });
맞습니다 ㅠㅠ
현재 이슈 크기가 너무 커져서 추후 이슈에서 해결하는게 좋을것 같습니다..

2020-08-10 08:53 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleQueryService.java
> +                .map(PeriodHistory::toDto)
이런 코드가 있었네요...
걷어내도록 하겠습니다.
@moonyoungCHAE 타미도 알아두세요

2020-08-10 08:54 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +    },
아 실수입니다! 고마워요 둔덩!

2020-08-10 08:55 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/api/KakaoSchedulerController.java
> +}
수정했습니다!

@moonyoungCHAE 도 알아두면 좋을것 같아요!

2020-08-10 08:55 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandService.java
> +    private Schedule findScheduleByTarget(final String name) {
자동완성으로 작성된 final 입니다..!

2020-08-10 08:56 UTC, DunDung approved these changes
고생하셨습니다 :)
공부가 많이 되는 코드네요... 역시 비밥 👍

2020-08-10 16:55 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +    },
준과 얘기후 전부 화살표 함수로 변경되었습니다

2020-08-10 16:56 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/kakao/schedule/model/Schedule.java
> +    private String userName;
이미 디비에 반영이 되었습니다 ㅎㅎ...
나중에 Admin권한을 가진 Member엔티티로 변경될것 같네요!

2020-08-11 01:36 UTC, ordinCode approved these changes

2020-08-11 02:02 UTC, moonyoungCHAE approved these changes
비밥 코드 잘 봤어요~~~ 최고의 코드네요

2020-08-11 02:02 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +      } catch (error) {
```suggestion
        );
        snackbarContents.type = SNACK_BAR_TYPE.SUCCESS;
        snackbarContents.message = MESSAGE.SUCCESS;
      } catch (error) {
```

2020-08-11 02:02 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandService.java
> +    @Transactional
```suggestion
```
여기 repo save에서 에러 났을 때 kakaoScheduler는 변화된 상태 유지되는 문제 좀 고민해볼게요

2020-08-11 02:34 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/api/KakaoSchedulerController.java
> +    public CustomResponse<Void> toggleScheduler(@RequestBody final KakaoScheduleToggleDto kakaoScheduleToggleDto) {
수정했습니다~

2020-08-11 04:26 UTC, giantim approved these changes
좋은거 하나 배워갑니다 :)
고생하셨어요 !

2020-08-11 05:09 UTC, merged