[FEAT] 태그레벨 정보보기
woowacourse-teams/2020-songpa-people pull request #121
Opened 2020-08-10 02:27 UTC by giantim

- 뷰티파이를 이용해서 구현했습니다.

- 데이터는 현재 동적으로 가지고 오지 않습니다.

fixes: #23

2020-08-10 04:32 UTC, moonyoungCHAE reviewed
라빈 너무 수고했습니다 ^________^ 웰컴투 css
1. 높은 태그레벨부터 출력됐으면 좋겠어요.
2. 버튼 선택시 카페/식당 중 하나만 선택되게 해주세요.
3. 버튼 선택시 변하는 것 팀원끼리 좀 상의해봐야겠네요.
4. 태그레벨 선택시 네모칸 두께가 두꺼워지도록 해주세요~ (검정색으로)
5. 태그레벨 정보보기에서 뒤에 슬라이더 색이 흰색이었으면 좋겠어요.
6. 만약 태그레벨 정보보기를 클릭하게 할거면 그에 맞춰 태그레벨 네모칸도 선택되게 해주세요.

2020-08-10 04:32 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/App.vue
> +  import KakaoMap from "@/views/KakaoMap";
코드 포맷팅해주세요

2020-08-10 05:05 UTC, DunDung approved these changes
CSS 하기 싫으셨을텐데 고생하셨습니다 👍 
전 디자인 갠적으로 맘에 쏙들어요 ㅎ

2020-08-10 05:05 UTC, DunDung commented on hashtagmap-web/front/src/App.vue
> +  };
```
data() {
    return {
    }
}
```
처럼 하기로 그때 합의봤습니다!

2020-08-10 05:05 UTC, DunDung commented on hashtagmap-web/front/src/components/tag-level/TagLevelContainer.vue
> +@media all and (min-width: 768px) {
반응형 굿.... 고생하셨습니다..

2020-08-10 05:05 UTC, DunDung commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +      }
정녕 다섯 개의 if문 밖에 방법이 없는 것인가요..
저도 해결책은 생각나지 않네요... 같이 고민해봐요 ㅎ

2020-08-10 17:14 UTC, pci2676 commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +      }
자바스크립트는 이넘이 없지 않나요? 어쩔수 없는 문제일것 같네요 ㅠㅠ

2020-08-10 17:16 UTC, pci2676 commented on hashtagmap-web/front/src/App.vue
> +  };
화살표 함수로 하는게 더 나을것 같아요!

2020-08-10 17:17 UTC, pci2676 approved these changes
엄청난 css의 수고가 느껴지네요.. 대단합니다..!
타미가 많은 리뷰를 해줘서 저는 approve 하겠습니다!

2020-08-11 01:42 UTC, ordinCode requested changes
라빈 고생했슴다!

2020-08-11 01:42 UTC, ordinCode commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +      if (value === "0") {
예전에 if문에서 return이 없었던 문제를 준에게 지적받은 기억이 나네요.
return을 추가해도 동작하는데 문제가 없다면 return을 달아주는게 성능상 좋을것 같습니다.

2020-08-11 09:55 UTC, giantim commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +      if (value === "0") {
디자인 바꾸면서 사라졌습니다 :)

2020-08-11 09:55 UTC, giantim commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +      }
디자인 바꾸면서 사라졌습니다 :)

2020-08-11 11:04 UTC, ordinCode approved these changes
고생했어요!

2020-08-12 01:53 UTC, moonyoungCHAE approved these changes

2020-08-12 02:27 UTC, merged