[FEAT] 지도 출력 시 태그레벨에 따라 다른 색의 핀 출력
woowacourse-teams/2020-songpa-people pull request #126
Opened 2020-08-11 06:41 UTC by moonyoungCHAE

fixes: #15

2020-08-11 14:59 UTC, giantim requested changes
타미 수고하셨어요!
현재 로컬에서는 데이터가 없어서 마커를 확인해 볼 수 없네요 :)
로컬에서 확인해 볼 수 있도록 변경한 후 다시 테스트 해보겠습니다.

2020-08-11 14:59 UTC, giantim commented on hashtagmap-web/front/src/utils/markerImages.js
> +import mapMarker5 from "../assets/markers/mapMarker1.png";
모두 같은 파일을 import 하고 있네요! 수정 부탁 드릴게요 :)

2020-08-12 06:35 UTC, ordinCode approved these changes
고민한 흔적이 보이네요! 수고했어요

2020-08-12 06:35 UTC, pci2676 approved these changes
고민을 꽤 한것 같군요! 고생하셨습니다!

2020-08-12 06:36 UTC, DunDung approved these changes
고생하셨습니다 :)
파일 분리 고생한 흔적이 보이네요.

2020-08-12 11:17 UTC, giantim approved these changes
고민을 꽤 한것 같군요! 고생하셨습니다!

2020-08-12 13:07 UTC, merged