[FEAT] 태그레벨 필터링
woowacourse-teams/2020-songpa-people pull request #141
Opened 2020-08-13 18:00 UTC by giantim

- 서비스를 실행했을 때 모든 태그 레벨 필터가 체크되어있습니다.
- 체크를 해제하면 해당 태그 레벨에 해당하는 가게의 마커가 지도에서 사라집니다.
- 체크가 해제되어있는 태그 레벨을 클릭하면 가게의 마커가 지도에 표시됩니다.

closes: #22

2020-08-14 07:15 UTC, ordinCode requested changes
점점 프론트의 고수가 되가는군요
고생했슴다

2020-08-14 07:15 UTC, ordinCode commented on hashtagmap-web/front/public/index.html
> +    <title>themiso</title>
우리 이거 한글로해서
"당신이 몰랐던 그 곳, 미소"
요렇게 하는건 어때
투표 고고

2020-08-14 07:15 UTC, ordinCode commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +
오호 created 단계에서도 vuex접근이 가능하군요 배워갑니다

2020-08-14 07:15 UTC, ordinCode commented on hashtagmap-web/front/src/views/KakaoMap.vue
>      ...mapActions(["setDetailModal", "setPlaces"]),
한칸씩 띄우는거 은근히 가독성괜찮은거 같은데 다른사람들은 어케 생각하나요

이것도 투표 고고

2020-08-14 07:15 UTC, ordinCode commented on hashtagmap-web/front/src/store/index.js
> +    },
이거 무슨함수인지 잘 이해가 안되서;;; 설명 부탁드립니다.

2020-08-14 07:58 UTC, DunDung approved these changes
굿굿 고생하셨습니다.
가벼운 코멘트달았어염

2020-08-14 07:58 UTC, DunDung commented on hashtagmap-web/front/src/store/index.js
> +      });
getters의 역할이 아닌 것 같아요.
vuex에 있는 markers에 taglevel 속성넣어주고
태그 레벨 선택 이벤트가 발생하면 actions에 메서드 하나 만들어서
vuex에 있는 markers들 중 해당 테그레벨 marker를 setMap해주는 방식은 어떨까요??
가벼운.. 제안입니다..

2020-08-14 07:58 UTC, DunDung commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +  },
흠 전 activeMarker is not a function 에러가 뜨네요
`activeMarker;` 로 수정해야 할 듯 합니당

2020-08-14 08:10 UTC, giantim commented on hashtagmap-web/front/public/index.html
> +    <title>themiso</title>
저는 구글, 네이버 등과 같은 서비스에서 메인 페이지의 타이틀은 서비스 대표 명이 더 좋을 것 같네요 :)

2020-08-14 08:15 UTC, giantim commented on hashtagmap-web/front/src/store/index.js
> +    },
https://vuex.vuejs.org/guide/mutations.html#mutations-follow-vues-reactivity-rules

vuex를 이용해서 객체를 초기화할 때 해당 객체의 상태 변화를 감지하기 위해서는 위 공식 문서에서 제시하는 방법을 따라야 합니다.
저는 그 중 객체를 새로 초기화하는 방법을 이용했습니다.
```...``` 의 경우는 javascript object spread syntax 라고 검색해보시면 어떤 원리인지 알 수 있습니다 :)

2020-08-14 08:20 UTC, giantim commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +  },
지적 감사합니다 :)

2020-08-14 08:22 UTC, giantim commented on hashtagmap-web/front/src/store/index.js
> +      });
markers에 taglevel 속성 넣어주는 것은 좋은 방법이네요 :)
선택 이벤트 발생 시 actions에는 따로 메서드를 만드는 것은 안해도 될 것 같습니다.
왜냐하면 선택 이벤트가 발생하면 tagLevels의 값이 변경되는데 이 상태 변경을 감지해서 marker의 setMap을 변경하는 방법으로 변경하면 로직이 훨씬 단순해 지겠네요.
피드백 굿 👍

2020-08-14 13:30 UTC, moonyoungCHAE approved these changes
라빈!! 정말 정말 수고하셨습니다. ~ 💯 
크고 작은 이슈가 정말 많았을 것 같아요.
store가 꽤 커져서 나중에 분리하는 이슈 따면 좋을 것 같아요.
그리고
`store에서 지도에 뿌려줄 정보를 정하는 게 조금 어색하게 느껴지는 데 어떻게 생각하시나요?` 이거는 이런 저런 시도해봤는데 어떻게 해야할 지는 잘 모르겠어서 라빈이 좋은 생각이 있다면 고치고 아니라면 넘어가도 될 것 같아요~

2020-08-14 13:30 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/store/index.js
> +      {
레벨과 rgb를 상수 파일로 분리하면 좋을 것 같아요

2020-08-14 13:30 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/store/index.js
> +      return state.markerDetails.filter(markerDetail => {
store에서 지도에 뿌려줄 정보를 정하는 게 조금 어색하게 느껴지는 데 어떻게 생각하시나요?

2020-08-14 14:55 UTC, giantim commented on hashtagmap-web/front/src/store/index.js
> +      {
좋은것 같습니다 :)

2020-08-14 15:08 UTC, giantim commented on hashtagmap-web/front/src/store/index.js
> +      return state.markerDetails.filter(markerDetail => {
vuex를 사용하는 이유는 상태를 갖는 데이터들을 전역으로 접근할 수 있게 해주고 변경을 감지해서 컴포넌트들을 효율적으로 관리하기 때문이라고 생각합니다.
지도에 보여주는 정보는 다른 컴포넌트에 포함된 여러 데이터들을 조합해서 보여줍니다.
사용자가 선택한 카테고리와 태그 레벨에 해당하는 정보들만 노출해야 합니다.
따라서 해당 데이터들의 변경을 자동으로 감지하고 그에 따라서 한 번의 통신으로 불러온 데이터를 가공해서 전달하는 기능을 위해 store를 사용하고 있어서 어색하다고 느껴지지는 않습니다.

추후에 web에 다른 컴포넌트들이 추가될 수도 있으니 store의 크기를 줄이는 리팩토링건만 이슈로 발급하고 데이터 관리 구조는 지금처럼 하는게 맞는 것 같습니다 :)

2020-08-15 03:20 UTC, ordinCode commented on hashtagmap-web/front/public/index.html
> +    <title>themiso</title>
"themiso"와 "당신이 몰랐던 그곳, 미소"를 비교했을 때 아무래도 우리가 전달하고자하는 의미는 후자에 더 잘 실려있고, 전자는 그냥 어쩔수 없이 도메인정해야하니까 했던 느낌이 조금 개인적으로 있어서요..
우테코도 우아한테크코스라고 하기도하고

일단 의견을 남김없이 얘기해봤는데 그럼에도 themiso가 좋을것 같다고하면 바로 수긍은 가능합니다!

2020-08-15 03:26 UTC, ordinCode commented on hashtagmap-web/front/src/views/KakaoMap.vue
>      ...mapActions(["setDetailModal", "setPlaces"]),
통일을 위해서 띄울지 안띄울지 오프라인으로 얘기해봅시다 그냥(안보는것 같으니)

2020-08-15 03:26 UTC, ordinCode approved these changes

2020-08-15 05:40 UTC, pci2676 approved these changes
pakage.json에 name:front 만 themiso로 바꿔주면 될것 같아요!
다른 부분은 팀원들이 충분히 리뷰해줬네요!
고생하셨습니다~

2020-08-15 06:40 UTC, merged