[FEAT] 카테고리에 해당하는 마커만 지도에 출력하기
woowacourse-teams/2020-songpa-people pull request #153
Opened 2020-08-15 06:56 UTC by giantim

- 카테고리 선택 시 해당 카테고리에 해당하는 마커만 출력하도록 변경했습니다.
- 처음 지도가 켜졌을 때 모든 카테고리가 활성화 되어있고 이후에 클릭한 카테고리만 활성화 시킵니다. 활성화되어있는 카테고리를 다시 클릭하면 모
든 카테고리가 활성화됩니다.
- 현재 카테고리는 엔티티로 관리하지 않기 때문에 데이터베이스에서 받아오지 않고 코드에 상수로 값이 추가되어있습니다 -> 이슈를 새로 발급해서 데모 이후에 처리해야 할 것 같습니다.

closed: #147

2020-08-15 07:07 UTC, pci2676 approved these changes
고생하셨습니다.
카테고리 코드는 Kakao에서 제공하는 코드라서 쉽게 바뀌지 않을것 같아요
만약 바뀐다면 Kakao Map을 사용하는 모든 라이브러리들이 바뀌게 될테니까요!
저는 그대로 enum을 활용해서 사용해도 될 것 같다는 생각이 드네요!

2020-08-15 11:07 UTC, ordinCode requested changes
라빈 작업속도가 엄청빠르네요! 고생했슴다

2020-08-15 11:07 UTC, ordinCode commented on hashtagmap-web/front/src/store/index.js
> +    CHECK_CATEGORY(state, category) {
개인적으로 CHECK_CATEGORY보다 SET_으로 해서 카페고리 상태를 SET해준다는 느낌의 네이밍이 더 좋아보여요.
무언가 CHECK는 상태의 변화가 일어나지 않을 것 같은 느낌? 그냥 확인만 할 것 같은 느낌?
(이전에는 메서드 파악하느라 말을 못했는데 CHECK_TAG_LEVEL도 동일합니다.)

2020-08-15 11:07 UTC, ordinCode commented on hashtagmap-web/front/src/store/index.js
> +        state.categories = state.categories.map(c =>
```suggestion
      if (isAllActive()) {
```
같은 메서드 분리 어떤가요

2020-08-15 11:07 UTC, ordinCode commented on hashtagmap-web/front/src/store/index.js
> +        if (activeCategory.name === category.name) {
여기도 적절한 네이밍으로 메서드 분리를 해주면 가독성이 좋아질 것 같아요!

2020-08-15 11:07 UTC, ordinCode commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/InstagramApiController.java
> +import org.springframework.web.bind.annotation.*;
이거 *처리 괜찮은건가요? 저는 잘 몰라서 혹시나 해서 말씀드립니다.

2020-08-15 12:24 UTC, giantim commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/InstagramApiController.java
> +import org.springframework.web.bind.annotation.*;
인텔리제이에서 자동으로 코드 포매팅 해주면서 바뀌었네요 :)
성능 차이는 없어서 괜찮습니다!

2020-08-15 12:26 UTC, giantim commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/InstagramApiController.java
> +import org.springframework.web.bind.annotation.*;
* 로 쓰는게 성능상 문제는 없지만 나쁜 습관이라고 하니 바꾸는게 맞겠네요....

2020-08-15 12:27 UTC, moonyoungCHAE reviewed
라빈 핵 빠르네요 대단해요~~ 💯 💯 
몇 가지 리뷰 남겼습니다!
저도 카테고리는 enum으로 남겨도 괜찮을거같아요

2020-08-15 12:27 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/store/index.js
> +    CHECK_CATEGORY(state, category) {
알아보기가 조금 어렵네요 ㅠㅠ
```
      const categoryState = category.active;
      state.categories = state.categories.map(c =>
        c.name === category.name
          ? { ...c, active: !categoryState }
          : { ...c, active: categoryState },
      );
```
이런 식으로 하면 이슈 있나요?

2020-08-15 12:27 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/components/tag-level/PlaceCategoryFilter.vue
> +.v-chip-group .v-chip {
디자인적으로 on / off가 반대같이 보여서 고쳐야 할 것 같아요.
색깔있을 때 on 이고 하얀 색일 때 off 같이 느껴져요!

저번에 이거 잘 안된다고 해서 좀 찾아봤어요~

방법 1.
[Vuetify primary 색 꾸어 적용하기](https://vuetifyjs.com/en/customization/theme/)

방법 2.
```
#test {
  color:rgb(100,100,100)
}
#test.v-chip--active {
  color: rgb(180,180,180);
  border-style: none;
  background-color:rgb(244,244,244) !important;
}
```
왜인지 id 들어가야 하네요.


그런데 이거 두개다 v-chip의 active를 보고 색이 바뀌는거라
store에 있는 active랑 맞지 않아서 그런지 잘 안나올 때가 있네요.
store에 있는 active에 따라 v-chip의 active도 동기화될 수 있게 하면 좋을 것 같아요.

다른 방법이 있다면 다른 방법으로 아무튼 on / off가 명확하게 표현되었으면 좋겠습니당 ~~ ^ㅋ^

2020-08-15 12:43 UTC, giantim commented on hashtagmap-web/front/src/store/index.js
> +    CHECK_CATEGORY(state, category) {
헉 죄송합니다! 다들.....
자바스크립트도 객체지향적으로 짜도록 노력하겠습니다....

2020-08-15 12:44 UTC, giantim commented on hashtagmap-web/front/src/components/tag-level/PlaceCategoryFilter.vue
> +.v-chip-group .v-chip {
처음에 서비스에 접속했을 때 모든 카테고리 / 필터에 해당하는 가게를 출력하니까 카테고리의 색을 모두 회색인 상태로 바꿀게요~~
방법 찾아봐주셔서 감사합니다 :)

2020-08-16 01:16 UTC, ordinCode approved these changes

2020-08-16 14:17 UTC, giantim commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/api/InstagramApiController.java
> +import org.springframework.web.bind.annotation.*;
인텔리제이에서 자동으로 포맷팅을 ```*```로 바꿔주네요 :)

2020-08-17 06:16 UTC, DunDung approved these changes
고생하셨습니다 💯 저도 개수가 많지 않으니 카테고리는 그대로 enum사용해도 괜찮을 것 같아요!

2020-08-17 06:16 UTC, DunDung commented on hashtagmap-web/front/src/components/tag-level/PlaceCategories.vue
> +    ...mapState(["categories"]),
저희 getters로 state값 가져오기로 하지 않았나요!

2020-08-17 08:08 UTC, moonyoungCHAE approved these changes

2020-08-17 08:10 UTC, giantim commented on hashtagmap-web/front/src/components/tag-level/PlaceCategories.vue
> +    ...mapState(["categories"]),
맞네요!
다른 컴포넌트들에서도 state를 mapState로 직접 가져오는 부분을 수정하는 이슈도 새로 발급해야겠네요 :)

2020-08-17 10:20 UTC, merged