[FEAT] 어드민 로그인 로그아웃 기능 구현
woowacourse-teams/2020-songpa-people pull request #159
Opened 2020-08-18 04:03 UTC by ordinCode

- login -> localStorage에 키 저장

- logout -> localStorage에 키 삭제

close #142

2020-08-18 06:43 UTC, giantim requested changes
학성 수고많았습니다!

이제 저희 prod 환경은 직접 건드리지 않기로 해요.....ㅎㅎ
그리고 지금 작업의 경우 데이터베이스 스키마가 변경되었으니 실행 환경이 다를 때 어플리케이션이 실행 안되는 문제가 있으니까 실행 환경도 pr 메세지에 적어주세요!

또 hashtagmap-web 모듈 처럼 devServer를 도입해서 개발을 했는데 이 부분에 대해서도 언급을 한번 해주셨으면 좋았을 것 같네요!
왜냐하면 pr이 머지된 후 앞으로 hashtagmap-admin 모듈의 view를 다른 팀원들이 개발할 때 문제가 좀 될것 같아요.
지금 admin의 application.yml에 보면 스프링 서버를 9000으로 실행하지 않고 있는데 이때 통신을 해야 하는 부분에서 proxy에러가 발생해서 매번 application.yml을 수정하면서 개발을 하거나 아니면 이번 pr에서 application.yml을 수정해서 머지를 하는게 좋을 것 같네요 :)

간단한 리뷰 몇가지 남겼으니 반영해주세요 수고 하셨습니다 :)

2020-08-18 06:43 UTC, giantim commented on hashtagmap-admin/front/src/App.vue
> +  data: () => {
컴포넌트 내부 스크립트의 항목들 공백으로 구분해서 가독성 높여주세요 :)

2020-08-18 06:43 UTC, giantim commented on hashtagmap-admin/front/src/components/Login.vue
> +          label="비밀번호"
비밀번호를 다 입력하고 엔터를 눌렀을 때 자동으로 로그인 되도록 하는 이벤트가 걸려있었으면 조금 더 편했을 것 같네요 :)

2020-08-18 06:43 UTC, giantim commented on hashtagmap-admin/front/src/store/modules/member.js
> +  mutations: {},
위에 비슷한 리뷰 남겼습니다 :)

2020-08-18 06:43 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/member/service/AdminMemberServiceTest.java
> +    void loginWithError1() {
DisplayName에 한글로 구체적으로 무엇에 대한 테스트인지 적어주셨는데 이에 맞게 메서드 명도 영어로 적어주셨으면 좋겠어요 :)
왜냐하면 우리가 gradle을 이용해서 bulid를 했을 때 테스트에 대해 성공 / 실패 여부를 html 파일로 만들어주는데 그 때 DisplayName의 한글이 깨져서 나오거든요!

2020-08-18 07:59 UTC, pci2676 approved these changes

2020-08-18 07:59 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/member.js
> +        await customWrapAxios().post("/admin-member/login", member);
제 경우에 vuex는 상태값 관리로만 사용하고 외부 통신은 api 모듈에서 따로 관리를 했는데 어떻게 생가하시나요?

2020-08-18 07:59 UTC, pci2676 commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/member/service/AdminMemberServiceTest.java
> +    }
저는 prefix하는 데이터가 있는걸 지양하는편인데요..!
해당 서비스가 prefix에 의존한 테스트밖에 작성을 하지 못하거든요!
어떻게 생각하시나요?

2020-08-18 08:27 UTC, ordinCode commented on hashtagmap-admin/front/src/App.vue
> +  data: () => {
이부분은 우리 다같이 딱 정하지는 않은 것 같아서 안했었는데 그럼 이제 그렇게 하는걸로 해요!!ㅎㅎ

2020-08-18 08:38 UTC, ordinCode commented on hashtagmap-admin/front/src/components/Login.vue
> +          label="비밀번호"
추가했슴다!

2020-08-18 08:40 UTC, ordinCode commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/member/service/AdminMemberServiceTest.java
> +    void loginWithError1() {
그렇구요! 자코코말하는건가요?

2020-08-18 08:45 UTC, ordinCode commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/member/service/AdminMemberServiceTest.java
> +    }
비밥 말씀은 setup에 있는 내용을 아래 메서드로 각각 내리자는 말이죠?
저도 공감합니다! 다만 지금 단계에서는 다른 테스트가 없고 추후 생기지 않을 것 같기도 하더라구요.
만약에 생기면 그때 내려도 괜찮을 것 같아요

2020-08-18 08:48 UTC, DunDung approved these changes
고생하셨습니다 학성!!!!!!
간단하게 구현해주셔서 좋았어요 💯

2020-08-18 08:52 UTC, ordinCode commented on hashtagmap-admin/front/src/store/modules/member.js
> +        await customWrapAxios().post("/admin-member/login", member);
좋은 방법이네요! 일단은 반영했는데 admin에 반영안된 코드들이 많이 있네요. 추후 리펙토링건으로!

2020-08-18 11:05 UTC, giantim approved these changes

2020-08-19 04:58 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/member/service/AdminMemberServiceTest.java
> +    void loginWithError1() {
gradle에서 제공하는 verification/test를 수행했을 때 결과도 역시 리포트로 만들어주는데 거기서 한글 지원을 안해서요!
intellij의 gradle 탭에서 Tasks/verification/test를 수행했을 때 buil/reports/tests/test에 index.html이 생기면서 테스트 결과를 문서화 해주는데 여기 html에는 encoding값이 자동으로 설정이 안되어있더라구요!
아주 가끔이기는 하지만 인스턴스에서 직접 이 리포트를 열어보는 일이 있었어서 말씀드린겁니다 :)

2020-08-19 04:59 UTC, giantim approved these changes
고생 많았습니다 👍 
점점 서비스가 갖춰야할 기능들이 생기는것 같아서 보기 좋네요 :)

2020-08-19 05:38 UTC, moonyoungCHAE approved these changes
학성 수고했어요 !! 이제 admin도 공개할 수 있겠네요 :)
approve할게요

2020-08-19 06:03 UTC, merged