[FEAT] Tag Level 기준 정하기
woowacourse-teams/2020-songpa-people pull request #160
Opened 2020-08-18 05:23 UTC by moonyoungCHAE

## Admin에서 TagLevel 관리
5개보다 추가, 삭제하게 되면 web - front가 뻑나서 update/조회 기능만 넣어놓음

## TagLevel 정하는 방법
1. Query문으로 작성
```
   @Query(value = "select min(hashtag_count), max(hashtag_count) "
            + "from (select *, ntile(:tileSize) over (order by hashtag_count asc) tile_group from instagram) temp "
            + "group by temp.tile_group", nativeQuery = true)
    List<List<Long>> findTiledHashtagCount(@Param("tileSize") Integer tileSize);
```
2. Java에서 작성 (현재 올린 코드)

1번 방법으로 하면 현재 DB 버젼이 낮아서 ntile을 못 쓰게 되어서 DB 버전 올린다음에 결과 비교해보려고 함!
(ntile(5) list를 5등분하는 것)

profile dev로 놓고 보면 됨!

2020-08-18 08:09 UTC, giantim requested changes
타미 수고하셨어요 :)
다양한 방법으로 해결할 수 있는 이슈여서 많은  고민을 하셨네요!
자바로 설계한 로직을 보니까 단순하지만 논리적으로 아주 잘 작성한거 같아요.
그래서 저는 나중에 정말 유의미하게 데이터가 많이 쌓이지 않는 이상 비밥의 의견대로 굳이 native query를 사용하지 않고 자바에서 로직을 처리해도 될 것 같네요!
물론 데이터베이스 버전 올린 후 성능 비교도 한번 부탁드릴게요 😉

몇가지 리뷰 남긴내용 반영해주세요!

2020-08-18 08:09 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +        List<Long> hashtagCounts = instagramRepository.findAllHashtagCountByOrderAsc();
여기 트랜잭션 전파 레벨을 REQUIRED로 설정한 이유 설명해주세요 :)

2020-08-18 08:09 UTC, giantim commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/MarkerResponse.java
> +                .tagLevel(tagLevel.intValue())
tagLevel값을 형변환 하지 말고 MarkerResponse의 tagLevel이 Long으로 바꾸는게 더 좋을거 같습니다 :)

2020-08-18 08:09 UTC, giantim commented on hashtagmap-web/src/main/resources/application.yml
> +  port: 8080
이거 8080으로 다시 바꾸신 이유가 지금 하신 작업이 태그 레벨 값만 확인하고 뷰는 변경 사항이 없어서 스프링 서버를 직접 실행해서 테스트 했기 때문이라고 생각되는데요 :)
hashtagmap-web 모듈의 경우 뷰에 대해 잦은 변경사항이 개발할 때 devServer 포트를 9000으로 열어놓고 사용하는게 더 개발이 편리하더라고요! 물론 서버를 두 개 켜놓고 작업해야 하는 귀찮음은 있습니다. 처음에 둔덩이 모듈에 적용해 놓은 사항이었는데 이 방법이 뷰를 수정한 내용에 대해 바로바로 잘 보여지고 좋은 것 같더라고요.
그리고 지금 서비스 인스턴스의 nginx 포트도 9000으로 변경되어 있습니다!
테스트할 때 조금 번거롭겠지만 다시 바꿔주세요 :)

2020-08-18 11:02 UTC, DunDung approved these changes
타미 고생하셨습니다 👍 
tagLevel이 구하는 과정이 상당히 논리적이에요!
고민한게 보이는 코드였어요. 수고많으셨습니다!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +    }
그냥 가벼운 의견인데 update할 때 tagLevel 비어있으면 5개 넣어주고
delete는 다지워버리는건 어때요?!
delete에서 한개만 지우는 경우가 어떤 경우가 있는지 궁금해요!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/dto/TagLevelDto.java
> +    Long maxHashtagCount;
private 의도를 가지고 안붙이신건가요??

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/taglevel/api/TagLevelApiControllerTest.java
> +    @Autowired
setUp에서 mockMvc를 초기화 해주고 있으니 @Autowired를 빼도 될것같아요!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandServiceTest.java
> +        assertThat(actual.get(1).getMaxHashtagCount()).isEqualTo(109);
assertAll로 묶는거 어때요!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +    Long maxHashtagCount;
이 곳도 private가 없네요!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
AccessLevel이 PUBLIC인 이유가 있나요?!

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevelFinder.java
> +    public static Long findTagLevelIdByHashtagCount(List<TagLevel> tagLevels, Long hashtagCount) {
tagLevels가 비어져서 오는 경우를 고려하는건 오바겠죠??

2020-08-18 11:02 UTC, DunDung commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/service/InstagramQueryService.java
> +            Long tagLevelId= TagLevelFinder.findTagLevelIdByHashtagCount(tagLevels, instagram.getHashtagCount());
코드 포맷팅 해주세욤

2020-08-19 05:37 UTC, ordinCode approved these changes
taglevel 측정하는거는 중요하고 어려운 이슈였는데 수고많았습니다.
타미가 말해준대로 추후에 또 한번 다른 방식도 고려해보도록하죠
자잘한 코멘트남겼는데 확인해주세요.

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +    }
// Todo check 는 뭔가요?

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +    Long maxHashtagCount;
해당 테그레벨이 무슨 단계일지 emun으로 주면 좋을 것 같은데 어떻게 생각하세요. 
TagLevelDto를 보니까 id값으로 taglevel을 매기는것 같던데 id 값으로만 해놓은거는 무언가 불안한마음도 들어요

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +
혹시나해서 남아있는 todo 환기시켜드리겠습니다~!ㅋㅋㅋ(처리한거라면 삭제)

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +        return hashtagCount >= minHashtagCount && hashtagCount <= maxHashtagCount;
isContains 는 어때요

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
> +                tagLevels.add(new TagLevel());
for문이 어디는 0부터 시작하고 어디는 1부터시작하는 것이 통일해주면 좋을 것 같습니다.
1부터 시작하길래 혹시 무슨 1부터 시작해야하는 로직이 있나 한번더 보게 되었어요.
(0부터시작해도되는거 맞죠? 그렇다면 0으로 수정해주면 감사하겠습니다^^)

2020-08-19 05:37 UTC, ordinCode commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/taglevel/api/TagLevelApiControllerTest.java
> +// todo ascii 추가
todo

2020-08-19 05:47 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +    Long maxHashtagCount;
그럴 수 있겠네요~
구체적으로 어떤 enum을 말하는 건지 궁금합니다~
LEVEL.ONE 이런 식으로 숫자만 있는 enum을 의미한 건가요?

2020-08-19 05:48 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +        List<Long> hashtagCounts = instagramRepository.findAllHashtagCountByOrderAsc();
추가, 삭제할 때 update가 안되면 추가, 삭제가 안되게하려고 REQUIRED로 했습니당 근데 이거는 디폴트라서 빼도 되겠네요.

2020-08-19 05:48 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/MarkerResponse.java
> +                .tagLevel(tagLevel.intValue())
Long으로 했을 때 이상하게 vue에서 깨지는 문제가 있었어요 ㅠㅠ Long으로 한 후 다시 확인해보겠습니다.

2020-08-19 05:50 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/resources/application.yml
> +  port: 8080
그 때 카카오 api가 막혀있어서 8080으로 바꿨었던 거 같네요 라빈 말대로 수정하겠습니다~

2020-08-19 12:56 UTC, pci2676 requested changes
고생하셨습니다
리뷰 남겼으니 같이 생각하고 반영할 부분은 반영해주세요~

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/front/src/App.vue
> +        </v-list-item>
이거 생길때마다 수기로 작성해주는거 넘 귀찮은거 같은데 v-for로 각 항목들 객체로 만들어서 뿌려주는 방식으로 리팩토링 해주실 수 있을까요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/front/src/views/TagLevel.vue
> +        const response = await this.axios.get("/tag-levels");
저는 api를 호출하는 부분을 request 디렉토리 아래에 관리하고 있는데요 어떻게 생각하시나요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
> +        }
메소드로 각 라인이 어떤 데이터를 입력하는지 분리해주는게 더 좋지 않을까요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
>      public void run(final ApplicationArguments args) throws Exception {
불필요한 throws Exception 을 같이 지워주시면 좋을 것 같아요!
보이스카웃 법칙..!

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
>  public class ScheduleDataConfiguration implements ApplicationRunner {
TagLevel에 대한 데이터가 들어가기 시작했기때문에 해당 클래스의 이름은 더이상 어울리지 않네요!
LocalDefaultDataConfiguration 같은 다른 네이밍은 어떨까요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/dto/TagLevelDto.java
> +    Long maxHashtagCount;
private 붙여주세요

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/dto/TagLevelDto.java
> +@AllArgsConstructor
롬복으로 전체생성는 지양해주세요
최대한 디롬복을 하는게 좋아요..

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +        tagLevelRepository.saveAll(updatedTagLevels); // Todo check
update 내부 로직을 보니까 tagLevels가 없으면 update하는 for문을 타지 않을것 같은데요 의도된 건가요?
그리고 saveAll하는 이유가 있나요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelFactory.java
> +    public List<TagLevel> update(List<Long> hashtagCounts, List<TagLevel> tagLevels) {
팩토리가 update하는거 이상해요
factory는 단순히 해당 객체를 생성만하는 역할을 가지고 있어야하는 네이밍이라고 생각해요.

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelFactory.java
> +    }
로직이 너무 흩어져있습니다.
일급컬렉션을 도출해서 각 일급컬렉션에게 메세지를 보내는 형식으로 리팩토링 해주세요

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelFactory.java
> +            log.error("AdminException:" + detailErrorMessage);
이 로그는 error에 해당하는 로그가 맞을까요?
저는 요즘 로그 레벨에 대해 생각하고 있는데 우리가 의도한 exception에서 발생하는 로그라면 info로 내리는게 맞는것 같아요

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelQueryService.java
> +        return tagLevels;
```suggestion
       return tagLevelRepository.findAll()
                .stream()
                .map(TagLevelDto::from)
                .collect(Collectors.toList());
```

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevelFinder.java
> +    }
TagLevel 일급컬렉션에서 해줄수 있지않을까요?

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramRepositoryCustomImplTest.java
> +        Collections.shuffle(hashtagCounts);
굳이 10개를 만들어서 셔플 하면서 테스트를 할 필요가 있나요?
그냥 3개 역순으로 만들어서 테스트해도 충분 할 것 같아요
for문이 들어가면 테스트 가독성이 너무 떨어져요...

2020-08-19 12:56 UTC, pci2676 commented on hashtagmap-web/src/main/resources/application.yml
> +  port: 8080
was 포트가 지금 9000번 아닌가요?

2020-08-20 05:21 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +    }
저는 태그레벨 추가/삭제 기능을 구현하려고 하다가 생각해보니 Admin애서 추가/삭제하지 않는 게 나을 것 같아서 Admin에서 안보이게 빼놨어요! 그냥 delete 기능을 없앨게요~ 어차피 안 쓸 것 같네여

2020-08-20 05:31 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevelFinder.java
> +    public static Long findTagLevelIdByHashtagCount(List<TagLevel> tagLevels, Long hashtagCount) {
TagLevel Update하는 부분은 Admin이 관리하게 두는 게 낫지 않을까요??
대신 tagLevel이 비면 이 메서드 자체가 오류 나니까 return 1L로 바꿔둘게요!

2020-08-20 05:34 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
다른 package인 config에서 사용해서 Public으로 되었어요~,,

2020-08-20 05:37 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +
감사합니당

2020-08-20 05:39 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +    }
개인적으로 궁금한 거 찾아보려다가 보냈네요 ㅋㅋ; 삭제할게욤

2020-08-20 05:40 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevel.java
> +        return hashtagCount >= minHashtagCount && hashtagCount <= maxHashtagCount;
수정했습니당

2020-08-20 05:42 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
> +                tagLevels.add(new TagLevel());
수정하겠습니당~

2020-08-20 06:34 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/App.vue
> +        </v-list-item>
좋네요~ 반영했습니다

2020-08-20 06:40 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/views/TagLevel.vue
> +        const response = await this.axios.get("/tag-levels");
더 깔끔하네요 수정했습니다!

2020-08-20 06:47 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/ScheduleDataConfiguration.java
>  public class ScheduleDataConfiguration implements ApplicationRunner {
앗 못봤네요 감사함당 DefaultDataConfiguration으로 수정했습니다

2020-08-20 06:50 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/dto/TagLevelDto.java
> +@AllArgsConstructor
넹 알겠습니다 근데 Dto에서는 괜찮지 않나요?!

2020-08-20 06:51 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/dto/TagLevelDto.java
> +@AllArgsConstructor
외부 라이브러리에 대한 의존성은 최대한 걷어내는게 좋다는 생각이 들어서요!

2020-08-20 06:56 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/taglevel/service/TagLevelCommandService.java
> +        tagLevelRepository.saveAll(updatedTagLevels); // Todo check
네 tagLevels가 없으면 update를 할 수 없으니까 for문 타지 않게 했어요.
saveAll은 전에 없으면 에러나길래 했는데 지금 확인해보니까 안나네요..??;; 지웠습니다!

2020-08-21 02:18 UTC, giantim approved these changes
수고많았습니다 👏👏👏👏👏

2020-08-21 03:51 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/domain/TagLevelFinder.java
> +    }
일급컬렉션은 상태와 행동을 한곳에서 관리하기 위해 사용한다고 생각합니다!
타미는 어떻게 생각하나요?

2020-08-21 06:50 UTC, pci2676 approved these changes

2020-08-21 11:52 UTC, merged