[FEAT] Index Page 구현
woowacourse-teams/2020-songpa-people pull request #183
Opened 2020-08-19 17:55 UTC by moonyoungCHAE

![image](https://user-images.githubusercontent.com/37133536/90671650-f6616480-e28f-11ea-9de4-0317523d088f.png)

1. 외부 오픈 소스 긁어서 추가/수정하고, css가 많이 들어가서 vue보다는 js스러운 코드인 점 양해부탁드립니당,,
2. 반응형 안됨 ㅠ
3. App.vue에서 KakaoMap.vue 덜어냄
```
<template>
  <div>
    <router-view></router-view>
  </div>
</template>
```
4. 맨첨에 포스팅 영역에 있는 사진은 배포 마지막 상태 보고 고칠까 생각중,, 이미지만 바꾸면 되는거라

2020-08-20 00:58 UTC, giantim requested changes
타미 디자인 하시느라 수고 많았어요!
반응형으로 제작하는 거에 대해서는 새로 이슈 발급해서 작업하는게 좋겠네요 :)
빌드 안되는 문제에 대해서 코멘트 남겼습니다.
그리고 문제가 하나 더 있는데요!
메인 페이지에서 start 버튼을 눌러서 지도 화면으로 이동했을때 부트스트랩이 적용이 안되서 css가 나오네요
![image](https://user-images.githubusercontent.com/39546083/90704489-94265500-e2cb-11ea-8cf3-1736bf53a046.png)
![image](https://user-images.githubusercontent.com/39546083/90704494-9a1c3600-e2cb-11ea-9b44-dd4517ff68a1.png)

확인 한번 부탁 드릴께요!
늦은 시간까지 고생 많았습니다 :)

2020-08-20 00:58 UTC, giantim commented on hashtagmap-web/front/src/views/KakaoMap.vue
> +import DetailModal from "@/components/DetailModal";
경로가 잘못되어서 빌드가 안되네요 😂

2020-08-20 03:01 UTC, ordinCode requested changes
타미 진짜 인스타처럼 잘 꾸며주었네요.
그런데 지금 모바일에서는 이쁘게 안나오는게 치명적인것 같아요. 이제 시간이 얼마 없는만큼 지금 모파일에서도 이쁘게 나오도록 수정해주었으면 합니다.

그리고 디자인적으로 추가의견은 어플소개가 조금 더 위로 올 수 있도록 했으면 좋겠어요. 그냥 아무도 안보고 스킵할것 같은 느낌이 있네요
(윗부분의 공간을 줄였으면 좋겠습니다)

2020-08-20 05:31 UTC, DunDung approved these changes
고생하셨스비다 역시 디자인은 타미네요.
아까 말한대로 start버튼 잘보이게 하는거랑 위에 영역만 줄이면 완벽할 듯!

2020-08-20 05:53 UTC, pci2676 approved these changes

2020-08-21 02:27 UTC, giantim approved these changes
반응형 깔끔해서 보기 좋네요! 수고많았습니다 :)

2020-08-21 04:51 UTC, ordinCode approved these changes

2020-08-21 06:29 UTC, moonyoungCHAE commented
CSS 깨진 이유: MainPage.vue에 적용된 css랑 KakaoMap에  적용된 css랑 중복 적용 되었다. 따로 분리는 어떻게 하는 지 모르겠다. element class 이름을 독립적으로 바꿈 (ex. container -> instagram-container)

2020-08-21 06:34 UTC, merged