[REFACTOR] : KakaoScheduler 동작방식 변경
woowacourse-teams/2020-songpa-people pull request #185
Opened 2020-08-20 11:11 UTC by pci2676

refactor : KakaoScheduler 동작방식 변경
 - 애플리케이션이 새롭게 시작될때 가장 최근 period history를 가지고 실행한다.
  - 없으면 기본값으로 실행한다.
 - toggle -> start/stop 방식으로 변경
 - status 확인할때 db와 실제 스케쥴러가 일치하지 않으면 스케쥴러쪽에 db를 동기화
 - instagram이 크롤링 중일때 확인 할 수 있는 방법이 없어서 instagram 크롤링 중 시작을 막는 로직은 추가 못함

closes #168

2020-08-21 03:10 UTC, giantim requested changes
비밥 고생 많았습니다~ 👏
질문 몇가지 남겼으니 확인해주세요!

2020-08-21 03:10 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/integration/KakaoScheduleIntegrationTest.java
> +    public void changePeriodTest() {
테스트 코드는 package-protected 로 해주세요 :)

2020-08-21 03:10 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandServiceTest.java
> +        Schedule schedule = scheduleRepository.findByName(KAKAO).orElseThrow(RuntimeException::new);
스케쥴러를 찾지 못했다는 예외를 던져주는게 더 구체적이지 않을까요? :)

2020-08-21 03:10 UTC, giantim commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTest.java
> +    @Test
이 테스트 코드랑 아래 테스트 코드에 대한 리뷰인데요!
이 두 가지 기능은 데이터베이스와 통신해서 저장된 값을 불러온 후 카카오 스케쥴러의 동작을 제어하는 로직을 테스트해야 하는데 실제 엔티티가 어떻게 변하는지에 대해 검증하는 부분은 없네요!
실제 데이터베이스에 싱크가 맞지 않는 값을 저장한 후 그 값이 제대로 변경되는지도 확인해보는게 좋지 않을까요? :)

2020-08-21 03:54 UTC, pci2676 commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleCommandServiceTest.java
> +        Schedule schedule = scheduleRepository.findByName(KAKAO).orElseThrow(RuntimeException::new);
테스트 코드에서 사용하지 않을 예외를 굳이 명시해줄 필요가 없다고 느꼈는데요!
최대한 관리 포인트를 줄이고자 단순히 RuntimeException을 던졌습니다!

2020-08-21 03:57 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTest.java
> +    @Test
KakaoSchedulerTest 는 단위 테스트이기 때문에 Spring Context가 없어서 위와 같이 작성했습니다!
해당 부분의 테스트는 admin 모듈에서 테스트를 해줘야 하는데 단위 테스트에서 값이 제대로 바뀌는 것을 테스트했는데 통합테스트에서 단위 테스트에서 검증한 부분을 한번 더 검증 할 필요가 있는가? 라는 생각이 들어서 해당 테스트는 작성하지 않았습니다!

2020-08-21 04:52 UTC, moonyoungCHAE reviewed
비밥 수정하느라 수고하셨습니다!

코드를 보면서 Schedule의 active 여부와 KakaoScheduler의 active 여부와 동일한 정보인데 분리되어 동작한다고 생각이 들었습니다. 개인적으로 조금 헷갈리고 관리가 어렵지 않나 생각했어요,,

Schedule의 active 여부는 애플리케이션을 
"실행할 때" 동작 여부를 나타내면 어떨까요? Schedule를 처음에 만든 이유가 running 중인 스케줄을 실행 여부를 관리하기 위해서가 아니라 처음 실행할 때의 상태를 관리하기 위해서 였고, 2가지가 분리되어도 괜찮은 거 같은데 어떻게 생각하시나요 ??! 실행 on/off 여부는 log로 봐도 될 것 같고요.

만약에 Admin 입장에서 번거로우면 PreDestory로 마지막 상태만 Schedule에 넣으면 안되나요?

2020-08-21 06:10 UTC, pci2676 commented
> 비밥 수정하느라 수고하셨습니다!
> 
> 코드를 보면서 Schedule의 active 여부와 KakaoScheduler의 active 여부와 동일한 정보인데 분리되어 동작한다고 생각이 들었습니다. 개인적으로 조금 헷갈리고 관리가 어렵지 않나 생각했어요,,
> 
> Schedule의 active 여부는 애플리케이션을
> "실행할 때" 동작 여부를 나타내면 어떨까요? Schedule를 처음에 만든 이유가 running 중인 스케줄을 실행 여부를 관리하기 위해서가 아니라 처음 실행할 때의 상태를 관리하기 위해서 였고, 2가지가 분리되어도 괜찮은 거 같은데 어떻게 생각하시나요 ??! 실행 on/off 여부는 log로 봐도 될 것 같고요.
> 
> 만약에 Admin 입장에서 번거로우면 PreDestory로 마지막 상태만 Schedule에 넣으면 안되나요?

맞아요 저도 개발하면서 너무 분리되서 관리가 된다는 느낌을 받았습니다!
그러면 Schedule 자체는 애플리케이션이 실행될때 자동 실행되느냐의 여부만 따지게 한다면
api가 아래와 같이 분할 될 것 같아보입니다

1. 자동 실행 ON, OFF
2. 자동 실행 상태 확인
3. 스케쥴러 실행, OFF
5. 스케쥴러 실행상태 확인

다른 팀원들의 리뷰도 받고 수정하도록 할게요!

2020-08-21 06:27 UTC, ordinCode approved these changes
비밥 코드가 깔끔해서 잘 읽혔던것 같네요 간단한 코멘트달고 어프로브하겠습니다

2020-08-21 06:27 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/KakaoScheduleAutoConfiguration.java
>              kakaoScheduler.start();
사실 지금까지는 log를 사용해 본 적이 없었는데 코드를 보면서 log를 이런식으로 쓸수도 있겠구나 하면서 많이 배웠습니다. 블랙리스트이슈에도 적용해보고 싶다는 생각이 들었어요.

kakaoScheduler.start()할때도 이전에 상태를 이어서 시작한다는 정보제공 느낌으로 log를 달아주는것도 어떨까 생각해봤습니다

2020-08-21 06:27 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleQueryService.java
>          return schedule.isActive();
이 부분이 잘 이해한게 맞는지 모르겠네요.
1. db상의 scheduler와 실제 돌고있는 kakaoScheduler의 액티브상태가 다를수 있다.(시스템이 갑자기 죽는다거나 여러가지 이유로...?)
2. 그 상태에서 어드민을 다시 켰을때 상태값을 가져오면서 둘의 싱크를 맞춰준다

맞나요?

2020-08-21 06:52 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/kakao/service/KakaoScheduleQueryService.java
>          return schedule.isActive();
1. 맞아요 다를 경우가 있을수도 있어요!
2. 맞습니다 싱크를 맞추는데 싱크를 맞추는 기준은 실제로 동작중인 스케쥴러를 기준으로 DB의 값이 따라갑니다!
그래서 타미가 아예 두개의 용도를 나눠 버리자! 라고 의견을 줬어요! 저도 그게 더 관리, 코드 가독성 측면에서 나을것 같다는 생각이 들기도 하구요!

2020-08-21 06:52 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/config/schedule/KakaoScheduleAutoConfiguration.java
>              kakaoScheduler.start();
chagePeriod 내부에 chage 한다는 log를 남기고 있어서 그부분은 따로 남기지 않았습니다!

2020-08-21 09:02 UTC, DunDung approved these changes
고생하셨습니다 비밥 👍

2020-08-22 01:13 UTC, giantim approved these changes
비밥 답변 리뷰에 대해 답변 달아준 내용 잘봤어요!
타미가 리뷰 남겨준 내용대로 변경 하는거에 대해 찬성합니다~
그렇게 수정 하시고 머지하면 될것 같네요 :)
수고 많았습니다!

2020-08-22 06:59 UTC, moonyoungCHAE approved these changes

2020-08-22 07:00 UTC, merged