[FEAT] 서비스에 보여줄 데이터를 쌓기
woowacourse-teams/2020-songpa-people pull request #188
Opened 2020-08-21 10:00 UTC by giantim

- 카카오 스케쥴러, 인스타그램 스케쥴러가 기존 구조에서는 데이터를 수집하는 동안 데이터베이스와 연결이 끊어질 가능성이 있던 부분을 수정했습니다.
- 카카오 스케쥴러가 수집한 데이터를 저장하는 과정에서 Document를 변환할 때 x, y 좌표 값이 잘못 들어가던 문제를 데이터 수집중에 발견해서 수정했습니다.
- 서울 행정구 25곳을 데이터베이스에 저장해 놓았습니다. -> 실험 결과 25개 구 정보를 한번에 카카오 스케쥴러에 넣고 돌리면 429를 던져줘서 더 이상 데이터 수집을 못합니다. 20번째 구에 대한 가게 정보를 탐색하던 도중 429 요청이 넘어오고 더 이상 카카오에서 정보 수집을 하지 못하도록 막았습니다. 질문 게시판 확인 결과 카카오에서는 시간 당 요청수로 봇을 탐지한다고 합니다. 따라서 카카오 스케쥴러가 한번에 최대 10개 구 정도만 탐색하도록 변경해야 합니다.
- kakao-scheduler모듈에 PlaceCollect 이라는 테스트 코드로 데이터를 수집했습니다. approve되면은 해당 테스트 코드는 삭제하고 머지하도록 하겠습니다. 

- 인스타그램 스케쥴러는 현재 기존 데이터를 데이터베이스에서 모두 지운 후 새로 수집합니다. 그래서 instagram-scheduler모듈에 InstagramCollect 이라는 테스트 코드를 만들어서 데이터를 수집했습니다.
- 인스타그램 스케쥴러가 모든 가게 정보를 받아와서 크롤링을 시도하면 자꾸 중간에 에러가 발생해서 1만개 씩 가게 정보를 나눠서 데이터를 수집했습니다.
- 결과가 너무 부정확해서 로직 개선이 필요합니다. 

closed: #179

2020-08-21 12:45 UTC, moonyoungCHAE reviewed
라빈! 이런 저런 실험하느라 고생했습니당!!! 👍 덕분에 배포할 때 데이터 따악 생겼네요
그리고 429의 정체는 카카오였다는 거죠?
그러면 key를 여러 개 파서 proxy처럼 돌려끼는 방법도 있겠네요.

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/factory/PlaceFactory.java
> +        /*
lat lon 정말 문제군요 ㅜㅜ

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
>          for (CrawlingResult crawlingResult : crawlingResults) {
deleteAll을 여기다가 해줘야 할 것 같아요!
deleteAll하고 save하다가 오류 생기면 롤백하는 형식으로

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/InstagramCollect.java
> +public class InstagramCollect {
```suggestion
public class InstagramCollectTest {
```

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/InstagramCollect.java
> +        List<Place> places = placeRepository.findAll();
여기 ParameterizedTest로 했으면 조금 덜 귀찮았을 것 같아요! 어차피 지울거니까 하자는 건 아니구요~

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +    void savePlaces(List<Place> places) {
개인적으로 궁금해서 실험해봤는데
saveAll이나 updateAndInsert에서 쓰인 batch성 쿼리에서는 transactional을 안 붙여도 알아서 rollback되네요~~ 공유

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +public class PlaceCollect {
```suggestion
public class PlaceCollectTest {
```

2020-08-21 12:45 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +        List<Rect> otherRects = new ArrayList<>(rects.subList(19, 25));
이 메서드는 조금 이해가 안됩니당,, rects와 otherRects의 의미는 뭔가요?

2020-08-22 01:17 UTC, giantim commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
>          for (CrawlingResult crawlingResult : crawlingResults) {
맞네요!
그럼 deleteAll도 다른 메서드로 분리해서 트랜잭션 범위를 나눠서 가져가는게 좋아보이네요 :)

2020-08-22 01:19 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/InstagramCollect.java
> +        List<Place> places = placeRepository.findAll();
데이터 수집 테스트 코드들이 findAll한 엔티티들을 범위를 나눠서 수동으로 실행한 이유가 요청이 너무 많아지면 429가 발생하더라고요!
인스타 뿐만 아니라 카카오 api도 429를 내려주더라고요. 그래서 직접 값을 나눠가면서 시간을 두고 수동으로 실행했습니다 🙃

2020-08-22 01:27 UTC, giantim commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +    void savePlaces(List<Place> places) {
saveAll도 내부에 그런 기능이 있는지 몰랐네요~ 역시 호기심천국 👍 👍 👍 👍 👍

2020-08-22 01:27 UTC, giantim commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +public class PlaceCollect {
데이터 수집한 테스트 코드는 머지할 때 지우고 머지하려고 하는데 어떻게 생각하세요? :)

2020-08-22 01:28 UTC, giantim commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +        List<Rect> otherRects = new ArrayList<>(rects.subList(19, 25));
이거는 25개 구를 한번에 가게 데이터 수집 요청을 보내면 429가 나서 수동으로 잘라서 넣어줬어요 :)
위에 써놓았습니다!

2020-08-22 03:27 UTC, ordinCode approved these changes
라빈 데이터수직하느라 고생많았습니다! 큰일을 해냈네요.

- PlaceNameParserTest에 본점 반점 직영점 케이스에 대해서도 테스트 추가하면 좋을 것 같아요.

2020-08-22 03:27 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/util/PlaceNameParser.java
>          return parsedPlaceName;
```suggestion
        Optional<PlaceNameType> optionalPlaceNameType = PlaceNameType.find(parsedPlaceName);
        return optionalPlaceNameType
                .map(placeNameType -> placeNameType.parsePlaceName(parsedPlaceName))
                .orElseGet(()->parsedPlaceName);
```

isPresent 말고 이렇게 하면 더 좋을것 같아요!

2020-08-22 03:27 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/util/PlaceNameType.java
> +
이넘 굿!

2020-08-22 03:27 UTC, ordinCode commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +public class PlaceCollect {
음...나도 지우는게 맞는거 같은데 혹시 모를 상황이 있으니까 그냥 놔두는게 나을 것 같기도하네요
차피 active를 collect로 해야 도는거니까

그리고 최대한 빨리 수집로직으로 개선해서 그때지우는 걸로..?

2020-08-22 04:07 UTC, giantim commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/util/PlaceNameParser.java
>          return parsedPlaceName;
굿 :)

2020-08-22 08:21 UTC, pci2676 requested changes
애증의 위도 경도...ㅠㅠ
고생하셨습니다!
질문남겼으니 답변 부탁드립니다!

2020-08-22 08:21 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> -    @Transactional
`@Transactional` 땐 이유가 뭔가요??
`instagramPostRepository.deleteAll();`가 실행된 이후에 에러가 터지면 `deleteAll()` 했던게 롤백이 안될것 같은데 의도된건가요?
`@Transactional` 붙이고 테스트 돌려보니까 정상적으로 돌아가는것으로 보이거든요!

2020-08-22 08:21 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +    void savePlaces(List<Place> places) {
그래도 붙여주는게 좋을 것 같아요
다른 사람이 그 정보를 모르면 롤백이 안된다고 생각하고 그게 전략이라고 오해할 수 있을 것 같아요~

2020-08-22 08:21 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/factory/PlaceFactory.java
> +        Location location = new Location(new Point(document.getLongitude(), document.getLatitude()),
`point` 도메인에서는 `public Point(final String latitude, final String longitude)` 이렇게 받고 있는데 이게 무슨일인거죠..ㅠㅠ
`document`에서 들고있는게 반대라는 건가요? 그렇다면 메서드를 바꿔줘야 할 것 같아요!

2020-08-22 10:22 UTC, DunDung approved these changes
라빈 고생하셨슴다:)

2020-08-22 10:22 UTC, DunDung commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/util/PlaceNameType.java
> +    CHINESE_BRANCH("반점",
네이밍 센스 굿

2020-08-22 10:34 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/InstagramCollect.java
> +        List<Place> places = placeRepository.findAll();
아하 시간 때문에 그랬군요

2020-08-22 10:36 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +public class PlaceCollect {
전 그냥 지워도 될 거 같아요~
이번에 데이터 수집이 일단은 끝났기 때문에!

2020-08-22 10:45 UTC, giantim commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/collect/PlaceCollect.java
> +public class PlaceCollect {
그럼 이번에 머지할 때 빼고 올리고 제 로컬에는 코드를 남겨둘게요!
나중에 다른 분들이 데이터를 수집하고 싶다 할 때 코드를 공유할 수 있도록 하겠습니다 :)

2020-08-22 10:46 UTC, giantim commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/factory/PlaceFactory.java
> +        Location location = new Location(new Point(document.getLongitude(), document.getLatitude()),
이 부분이 정말 헷갈려서 내일 다시 꼼꼼히 짚어보고 수정해서 리뷰 보내도록 해볼께요 😥
사실 지금 저도 너무 헷갈려요!

2020-08-22 10:47 UTC, giantim commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> -    @Transactional
이 부분 제 실수가 있었네요 :)
지적 감사합니다!

2020-08-23 03:33 UTC, moonyoungCHAE approved these changes

2020-08-23 03:33 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
>          for (CrawlingResult crawlingResult : crawlingResults) {
엇 이 부분 하나의 transaction 안에서 delete + save 하자는 말이었어요!!
1. findAll
2. 크롤링
3. 메서드 (deleteAll + saveAll)

저렇게 하면 크롤링하다가 문제 생기면 지운 게 복구 안 되지 않나요?!

2020-08-23 04:09 UTC, pci2676 approved these changes

2020-08-23 04:54 UTC, merged