[REFACTOR] 카카오 스케쥴러 뷰 버튼 분할
woowacourse-teams/2020-songpa-people pull request #190
Opened 2020-08-22 08:07 UTC by pci2676

api가 늘어나서 뷰 버튼도 늘어났음!
1. 스케쥴러 자체를 실행하는 버튼
2. 애플리케이션이 실행될 때 스케쥴러를 실행할지 말지에 대한 기능

![image](https://user-images.githubusercontent.com/13347548/90951871-d8ffe680-e499-11ea-8797-cd7ecf1a9a65.png)

closes #176

2020-08-22 18:44 UTC, DunDung approved these changes
고생하셨슴다 비밥 👍

2020-08-22 18:44 UTC, DunDung commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +        await dispatch("fetchScheduleAutoRunnable");
try, finally로 처리한 이유가 궁금합니다!

2020-08-23 00:55 UTC, ordinCode approved these changes

2020-08-23 00:55 UTC, ordinCode commented on hashtagmap-admin/front/vue.config.js
> +      }
👌

2020-08-23 00:55 UTC, ordinCode commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +      );
지금은 사용하지 않는것으로 보이네요 혹시 실수로 남겨놓으신건 아닌지해서 알려드려요.
아니면 특별히 남겨놓은 이유가있나용

2020-08-23 01:10 UTC, giantim requested changes
고생 많았어요 비밥!
스케쥴러의 실행에 관하여 많은 고민을 해주셔서 점점 구조가 잘 갖춰지네요 :)
간단한 리뷰 몇개 남겼는데 확인해주세요~

2020-08-23 01:10 UTC, giantim commented on hashtagmap-admin/front/vue.config.js
> +        target: `http://localhost:${proxyPort}`,
web 모듈도 이런 방법으로 바꾸는게 좋겠네요 :)

2020-08-23 01:10 UTC, giantim commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +        >상태 : {{ getScheduleActiveStatus.message }}
상태를 나타내는 버튼은 readOnly 속성을 주어서 클릭을 못하게 하는거는 어떨까요?
마우스를 갖다 대었을 때 hover 이벤트가 발생해서 약간 헷갈리네요 :)

2020-08-23 01:10 UTC, giantim commented on hashtagmap-admin/front/src/request/api/kakao.js
> +    const toggleDto = { name: scheduleName };
변수명 schedulerName 어떠세요? :)

2020-08-23 01:13 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +      );
오잉 불필요한 녀석이었네요! 제거하겠습니다~

2020-08-23 01:15 UTC, pci2676 commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +        >상태 : {{ getScheduleActiveStatus.message }}
클릭했을때 통신을 통해 상태갱신이 가능하도록 했는데 불필요한 기능일까요???

2020-08-23 01:15 UTC, pci2676 commented on hashtagmap-admin/front/src/request/api/kakao.js
> +    const toggleDto = { name: scheduleName };
좋습니다! :)

2020-08-23 01:18 UTC, pci2676 commented on hashtagmap-admin/front/src/store/modules/kakao.js
> +        await dispatch("fetchScheduleAutoRunnable");
생각해보니 try 블럭이 필요가 없어보이네요!

2020-08-23 02:48 UTC, giantim commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +        >상태 : {{ getScheduleActiveStatus.message }}
스케쥴러 동작 상태 갱신은 카카오 스케쥴러 실행 / 카카오 스케쥴러 정지 버튼으로 제어하고 있고
상태: on 버튼에 달려있는 클릭 이벤트에 대한 메서드는 단순히 카카오 스케쥴러의 isActive값만 받아오도록 되어있는데 어떤 의도록 클릭 이벤트를 달아놓으신건가요?
지금 의도하신 기능대로 동작하고 있는게 맞는지 설명 부탁드릴께요 :)

2020-08-23 03:52 UTC, moonyoungCHAE approved these changes
비밥 수정할 거 많았을 텐데 수고하셨습니다~
다른 분들이 리뷰 많이 달아줘서 별도로 달 건 없네요.

2020-08-23 03:52 UTC, moonyoungCHAE commented on hashtagmap-admin/front/src/utils/validator.js
> +      v => v.trim() !== "* * * * * *" || "주기가 너무 빠릅니다.",
👍

2020-08-23 04:11 UTC, pci2676 commented on hashtagmap-admin/front/src/views/KakaoScheduler.vue
> +        >상태 : {{ getScheduleActiveStatus.message }}
단순히 새로고침용으로 만들었습니다!

2020-08-23 04:18 UTC, giantim approved these changes
비밥 수고하셨습니다~ 답변 감사해요 :)

2020-08-23 10:53 UTC, merged