[FEAT] 태그레벨 데이터 뷰에서 DB 데이터로 보여주기
woowacourse-teams/2020-songpa-people pull request #191
Opened 2020-08-22 13:28 UTC by giantim

- 지금 태그 레벨을 수치화해서 보여줄 때 모습이 다음과 같습니다.
![image](https://user-images.githubusercontent.com/39546083/90957040-61947c00-e4c6-11ea-84e6-a2d698c0cfbf.png)

그림을 보면은 각 태그 레벨 별 최소 해시태그 수 만 필요로 하고 있고 마지막 레벨에 대해서는 아무 값도 필요하지 않습니다.
왜냐하면 html로 저 막대를 만들었을 때 가장 앞과 가장 뒤에는 글씨를 넣을 수 없기 때문입니다.
지금 TagLevelResponse를 만들었을 때는 태그 레벨, 최소 해시태그 수, 최대 해시태그 수를 모두 담아서 응답을 보내도록 설계를 했습니다.
여러분들은 사용하는 값만 응답에 포함시켜서 보내는 것이 더 좋다고 생각하는지 아니면 지금 구조도 상관 없다고 생각하는지 의견을 듣고싶습니다 :)

- 버그를 하나 발견했는데 이거는 설명을 잘 못하겠어서 월요일에 만나서 보여드리도록 하겠습니다 😂

closed: #178

2020-08-22 18:38 UTC, DunDung approved these changes
고생하셨습니다 라빈 👍 
포맷팅 된 코드가 많네용

2020-08-23 01:24 UTC, ordinCode requested changes
라빈 수고했어요~!
코멘트남겼으니 확인해주세요ㅎㅎ

2020-08-23 01:24 UTC, ordinCode commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/service/TagLevelQueryServiceTest.java
> +    }
지금은 repository에서 실제로 데이터를 가져오는걸 테스트하는게 없는거 같은데, service에서는 repository를 mock치지 않고 실제로 찔러보는 테스트를 해야할 것 같습니다.

2020-08-23 01:24 UTC, ordinCode commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/TagLevelResponse.java
> +                            tagLevel.getMinHashtagCount(), tagLevel.getMaxHashtagCount());
메서드로 분리하면 어때요?

2020-08-23 01:40 UTC, giantim commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/service/TagLevelQueryServiceTest.java
> +    }
단순히 repository에서 findAll 메서드를 테스트를 해야 할까요?
저는 서비스에서는 응답값을 만들어서 주는 역할을 테스트 하는것으로 충분하다고 생각이 듭니다 :)

2020-08-23 02:50 UTC, ordinCode approved these changes

2020-08-23 04:07 UTC, moonyoungCHAE approved these changes
라빈~ 수고하셨습니다.
👍
응답은 지금 구조로 가도 될 것 같아요. 변경될 일이 없을 것 같진 않지만 그럴 경우를 고려해서 최소,최대 다 받아오는 게 좋은 것 같아요.

2020-08-23 04:07 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/model/TagLevel.java
> +            throw new CoreException(CoreExceptionStatus.INVALID_TAG_LEVEL, detailMessage);
오타 있었군요 ㅋㅋ 바꿔줘서 고맙습니다~

2020-08-23 04:07 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/components/detail-modal/DetailModal.vue
> +      // return (this.getDetailModal.hashtagCount / 1000).toFixed(1);
```suggestion
```

2020-08-23 04:07 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +    ...mapActions(["setTagLevelDetails"]),
이 부분 없어도 되지 않나요?!

2020-08-23 05:06 UTC, giantim commented on hashtagmap-web/front/src/components/detail-modal/DetailModal.vue
> +      // return (this.getDetailModal.hashtagCount / 1000).toFixed(1);
홀리~ 고마워요 :)

2020-08-23 05:07 UTC, giantim commented on hashtagmap-web/front/src/components/tag-level/TagLevelDetail.vue
> +    ...mapActions(["setTagLevelDetails"]),
```
async created() {
    await this.setTagLevelDetails();
  },
```
여기서 호출해야 해서 필요합니다 :)

2020-08-23 11:06 UTC, pci2676 commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/service/TagLevelQueryServiceTest.java
> +    }
저는 이 테스트가 그렇게 유의미해 보이지 않아요. mock으로 5개를 뱉도록 만들고 5개를 가져오는지 테스트 한다라는게 큰 의미를 갖지 못하는 것 같네요!
차라리 tagLevelRepository에서 findAll() 메서드를 사용하는게 아니라 findTop5ByOrderByCreatedDate() 같은 메서드를 사용하는게 더 의미있을것 같아요 위 테스트 코드만 보고는 findAll()이 5개만 가져올거라는 보장을 해줄수 없는 것 같거든요!
그래서 findTop5ByOrderByCreatedDate()과 같이 limit 5 가 걸린 쿼리문을 날리는 형식의 통합테스트가 필요할 것 같습니다.

2020-08-23 11:11 UTC, pci2676 requested changes
학성이 리뷰한 부분에 대해서 제 생각을 남겼습니다~
확인해주세요~

2020-08-23 11:11 UTC, pci2676 commented on hashtagmap-web/front/vue.config.js
>          target: "http://localhost:9000",
이왕 포맷팅 하는 김에 9000도 proxyPort 변수로 바꿔주시는건 어떨까요?

2020-08-23 11:11 UTC, pci2676 commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/dto/TagLevelResponse.java
> +                            tagLevel.getMinHashtagCount(), tagLevel.getMaxHashtagCount());
저는 그냥 for문을 사용하는게 더 보기 편할것 같다는 생각도 드네요

2020-08-24 01:17 UTC, giantim commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/service/TagLevelQueryServiceTest.java
> +    }
findAll 메서드가 아니라 querydsl을 이용해서 비즈니스 로직에 맞는 메서드를 만드는게 더 적합해 보이네요!

2020-08-24 11:32 UTC, pci2676 approved these changes

2020-08-24 12:11 UTC, merged