[FEAT] 에러로그 슬랙으로 관제할 수 있도록 구축
woowacourse-teams/2020-songpa-people pull request #192
Opened 2020-08-22 20:11 UTC by DunDung

admin과 web 모듈의 error 레벨의 log를 슬랙메세지로 보냅니다. (슬랙 채널 #prod-admin, #prod-web)
시크릿 모듈에 slack폴더를 추가해 슬랙 채널의 admin채널과 web채널의 web hook uri를 관리합니다.

admin채널과 web채널의 web hook uri 가 달라서 admin, web 모듈별로 logback.xml은 따로 가지고있어야 할 것 같긴해요.
PR로 의견남겨주시고 반영 후에 문서화도 할 예정입니다!

빌드가 안됐던 것은 라빈 말대로 build할때 setup전에 secret 모듈의 slack 관련 파일을 복사해와야 하는데 제가 그걸 안했었네요 ㅠ
그래서 파일을 못찾는다는 오류가 났던 걸로 추정돼요.

slack설정은 별 거 없는데 외부 property를 logback.xml에서 읽어오는 데 삽질을 많이해서 오래걸렸습니다 ㅠ

테스트로 보냈던 슬랙은 logback.xml에서 !prod환경에 똑같이 설정을 해주고 직접 요청을 보내서 log.error를 찍었습니다. 그래서 슬랙에 갔던 내용이 알아보기 힘들게 뜬 걸로 추정돼요. 아마 실제 환경에서는 현재 ec2에서 보는 에러로그랑 똑같이 슬랙에 메세지가 올겁니다.

fixes #171

2020-08-23 01:31 UTC, ordinCode approved these changes
둔덩스 덕분에 slack에서 편하게 에러를 확인할 수 있겠군요.
그런데 사실 보면서 뭐가 뭔지 잘은 모르겠어요 문서화 해주실꺼죠?😉

2020-08-23 01:31 UTC, ordinCode commented on hashtagmap-web/src/main/resources/logback-spring.xml
> +            <iconEmoji>:bright-cow:</iconEmoji>
👍

2020-08-23 01:35 UTC, giantim requested changes
둔덩 고생하셨습니다 :)
마지막으로 간단한 리뷰 남겼으니까 반영해주세요!

2020-08-23 01:35 UTC, giantim commented on hashtagmap-admin/build.gradle
> +processResources.dependsOn 'copySlackWebHook'
이 구문은 추가해줄 필요가 없네요 :)
각 task별로 dependsOn으로 실행 순서를 지정해 줬고 가장 마지막에 실행되는 buildFrontEnd를 processResouces로 등록해서 괜찮습니다.

2020-08-23 01:35 UTC, giantim commented on hashtagmap-web/build.gradle
> +processResources.dependsOn 'copySlackWebHook'
위에 동일한 리뷰 남겼습니다 :)

2020-08-23 04:08 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/resources/logback-spring.xml
> +            <iconEmoji>:bright-cow:</iconEmoji>
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2020-08-24 06:37 UTC, moonyoungCHAE approved these changes

2020-08-24 10:42 UTC, giantim commented on hashtagmap-web/build.gradle
> +processResources.dependsOn 'copySlackWebHook'
이 부분은 제가 잘못알고있었네요! 하나 배워갑니다 :)

2020-08-24 10:43 UTC, giantim approved these changes
수고 많았어요 둔덩 :)
혹시 슬랙으로 알람이 오는 환경을 어떻게 설정했는지 공유해 주실래요?

2020-08-24 11:33 UTC, pci2676 approved these changes

2020-08-24 14:18 UTC, merged