[FEAT] admin에 blackList관리 기능 추가
woowacourse-teams/2020-songpa-people pull request #193
Opened 2020-08-23 06:07 UTC by ordinCode

# 구현기능

- 블랙리스트 후보 목록을 가져온다(hashtag수가 많은 순대로)
  - placeId
  - placeName
  - hashtagName
  - hashtagCount
  - Kakao place상의 주소
- Black List 등록 후 instagram **업데이트** 기능(해당 place가 실제로 인기가 있는 경우)
  - placeId와 대체검색어를 전송한다.
  - 블랙리스트 등록을 한다.(placeId, 대체검색어,isSkipPlace-false / isSkipPlace은 대체검색어로 검색해도 인기가 없는 게시물은 나중에 크롤링에서 아예 제외시키기 위함)
  - 대체검색어로 검색한 결과를 instagram과 post에 업데이트한다.
- Black List 등록 후 instagram **삭제** 기능(해당 place가 사실 인기가 없는 경우)
  - 삭제할 항목의 placeId를 전송한다.
  - 블랙리스트 등록을 한다.(위와 동일하지만 여기서 isSkipPlace가 true)
  - placeId에 해당하는 instagram과 post를 삭제한다.
- InstagramScheduler가 돌아갈때 블랙리스트인지 확인
  - 해당 장소가 크롤링할 필요도 없는 인기 없는 장소인지 확인하여 인기없는 장소면 skip하도록 로직 추가
  - 위의 조건을 통과한 상태에서 대체검색어가 등록 되어있는지 확인하고 등록되어있다면 대체검색어로 검색하도록 로직 추가

일단 BlackListApiController의 블랙리스트 등록후 인스타 삭제 / 업데이트 하는 메서드를 시작으로 보시면 이해하기에 좋을 것 같습니다

close #177

2020-08-23 10:20 UTC, moonyoungCHAE reviewed
학성 어려운 이슈였는데 수고하셨습니다~
대략적으로 코드는 훑어봤어요. 자세한 건 내일 코드 리뷰해주세요~~

코드 보면서 든 생각이 있는데 저번에도 말했던건데 꼭 BlackList를 Entity로 따로 관리해야하나 생각이 들었어요.. 그냥 HashtagName에 대체어를 갱신해주면 문제가 있나요?

* 대체어 등록 시 Instagram - HashtagName을 갱신한다.
* 크롤링 시 Instagram을 저장할 때 PlaceRepositoryCustomImpl 처럼 ON DUPLICATE KEY UPDATE 한다.
* 크롤링 시 대체어를 검색한다.
```
    public String findHashtagNameToCrawl(Place place) {
        return blackListRepository.findByPlaceId(place.getId())
                .map(BlackList::getReplaceName)
                .orElseGet(place::getPlaceName);
    }
```
요 부분 대신
```
    public String findHashtagNameToCrawl(Place place) {
        return InstagramRepository.findByPlaceId(place.getId())
                .map(Instagram::getHashtagName)
                .orElseGet(PlaceNameParser로 파싱해주기);
    }
```
이렇게

---
한 번 생각해보고 내일 이야기해주세요!!

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +        return instagrams.stream()
1. Hashtag 검색어가 바뀐 (BlackList가 된) Instagram까지 다 가져오게 되는 건 의도한 건가요?
2. Instagram을 가져올 떄 findAll하지 않고 Orderby + Top20 으로 가져오면 좋을 것 같아요.

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/BlackListCommandService.java
> +    public BlackList save(BlackList blackList) {
```@Transactional```이 필요한 이유가 있나요?

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +    public CustomResponse<Void> deleteInstagramAndPost(@RequestBody BlackListRequest blackListRequest) {
```suggestion
    @DeleteMapping
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public CustomResponse<Void> deleteInstagramAndPost(@RequestBody BlackListRequest blackListRequest) {
```

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +    @RequestMapping("/update-instagram")
```suggestion
```

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +        Instagram instagramToDelete = instagramQueryService.findByPlaceId(blackListRequest.getPlaceId());
컨트롤러에 너무 로직이 노출된 것 같아요.
서비스에 넣어주는 게 어떤가요

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +    private Instagram updateInstagramAndPost(@RequestBody BlackListRequest blackListRequest) {
여기도 서비스로 넣어주는 게 어떤가요?

2020-08-23 10:20 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +    public Instagram updateBlackLists(String replaceName, Instagram instagramToUpdate) {
```suggestion
    public Instagram updateBlackList(String replaceName, Instagram instagramToUpdate) {
```

2020-08-23 12:40 UTC, giantim requested changes
학성 고생하셨습니다 :)
정말 큰 이슈네요! 비즈니스 로직의 매우 중요한 부분이어서 많은 고민이 있으셨던것 같습니다.
오프라인 코드 리뷰 때 좀 더 자세한 설명도 들어보고 다른 팀원들과 의견 공유하는 시간을 갖고 확실하게 로직을 정해서 반영하는게 좋을 것 같습니다.
지금 설계하신 부분에서 몇 가지 궁금증 있는 부분에만 리뷰 남겼습니다 :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-admin/build.gradle
> -        rule {
이거 지우신 이유가 있을까요? :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-admin/front/src/store/modules/blackList.js
> +        placeId: "",
placeId는 auto-increment되는 값인데 만약 place가 다 지워졌을 때 일관성이 깨지니까 kakao_id로 연관을 맺는게 더 정확하지 않을까요? :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/blacklist/acceptance/BlackListAcceptanceTest.java
> +    @DisplayName("인기없는 인스타그램을 블랙리스트 등록후 삭제한다")
인기없는 가게가 아닌 잘못된 검색어로 검색된 가게 아닐까요? :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiControllerTest.java
> +    @DisplayName("대체어로 검색했을 때 인기없는 인스타그램을 삭제하는 요청")
위에 비슷한 코멘트 남겼습니다 :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +    private Long placeId;
제가 잘 기억이 안나서 그러는데 kakaoId가 아닌 placeId로 하신 이유를 오프라인 코드리뷰 때 다시 들어봐야 겠네요 :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-instagram-crawler/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-web'
여기 스프링 의존성이 추가되었네요!
구조 설명을 내일 구체적으로 들어봐야겠습니다 :)

2020-08-23 12:40 UTC, giantim commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/Crawler.java
> +@Component
Crawler를 컴포넌트로 만든 이유가 궁금하네요 :)
instagram-crawler는 스프링 의존성이 없는 모듈로 만들기로 했었던 것 아닌가요?

2020-08-24 12:11 UTC, pci2676 approved these changes
오프라인에서 말했던 내용에 몇가지 피드백을 추가해서 남겼습니다!
확인해주세요~

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/front/src/views/BlackListManager.vue
> +      if (confirm(`${this.blackListDataForUpdateInstagram.replaceName}(으)로 등록합니까?`)) {
제가 `DistrictManage.vue`에서 이 부분 dialog로 처리한 방식으로 해보는건 어떨까요?

```vue
          <v-dialog v-model="dialog" persistent max-width="300px">
            <template v-slot:activator="{ on }">
              <v-btn class="ma-2" color="error" outlined dark v-on="on">
                삭제
              </v-btn>
            </template>
            <v-card>
              <v-card-title class="headline">삭제하시겠습니까?</v-card-title>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="blue darken-1" text @click="dialog = false"
                  >취소
                </v-btn>
                <v-btn color="red darken-1" text @click="deleteSelectedDistrict"
                  >삭제
                </v-btn>
              </v-card-actions>
            </v-card>
          </v-dialog>
```
이렇게 되어있는 부분 보시면 됩니다.

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/front/src/request/api/blackList.js
> +    });
```suggestion
    return customWrapAxios().put("/blacklist/update-instagram", {
      headers: {
        "Content-Type": "application/json"
      },
      data: blackList
    });
```

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +    @PostMapping("/update-instagram")
```suggestion
    @PutMapping("/instagram")
```

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiController.java
> +    @PostMapping("/delete-instagram")
```suggestion
    @DeleteMapping("/instagram")
```

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/BlackListResponse.java
> +    }
```suggestion
    public static BlackListResponse of(Instagram instagram) {
        return new BlackListResponse(instagram.getPlaceId()
                , instagram.getHashtagName()
                , instagram.getHashtagCount());
    }

    private BlackListResponse(Long placeId, String replaceName, Long hashtagCount) {
        this.placeId = placeId;
        this.replaceName = replaceName;
        this.hashtagCount = hashtagCount;
    }
```

static function이 위로 올라오도록 해주세요~

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/BlackListRequest.java
> +    }
여기도 static function이 위로 올라가게 해주세요~

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramCommandService.java
> +    }
```suggestion
    @Transactional
    public void delete(BlackListRequest blackListRequest) {
        Place place = placeRepository.findById(blackListRequest.getPlaceId())
                .orElseThrow(() -> new AdminException(
                        CommonExceptionStatus.NOT_PERSIST,
                        String.format("존재하지 않는 placeId(%d)입니다.", blackListRequest.getPlaceId())));
        Instagram instagram = instagramRepository.findByPlaceFetch(place);

        instagramRepository.delete(instagram);
    }
```

굳이 메서드로 빼지 않아도 충분히 이해가 가는 부분이라 메서드로 추출하지 않아도 될것 같아요!
재사용성을 위해 뺀다면 나중에 재사용하는 부분이 생겼을때 빼는게 맞을것 같아요!
그리고 정 빼야 한다면 public이 아닌 private 메서드가 되어야 할 것 같아요!

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +                .limit(SUB_BLACK_LIST_SIZE)
sort와 limit으로 특정갯수를 가져온다면 타미의 말대로 querydsl을 이용해서 order by 와 limit 구문을 이용해서 가져오는게 더 좋을 것 같아요

2020-08-24 12:11 UTC, pci2676 commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagrampost/service/InstagramPostCommandService.java
> +    }
이 부분도 `findInstagramByPlaceId`로 메서드를 추출할 만큼 복잡하지 않아서 `deleteByInstagramId`구문에 같이 있어도 문제가 없을것 같아요~

2020-08-24 14:56 UTC, DunDung approved these changes
학성 고생하셨슴다.
오프라인 코드리뷰에서 피드백 받은 내용들을 벌써 반영하셨네요.. 역시 👍

2020-08-24 14:56 UTC, DunDung commented on hashtagmap-admin/build.gradle
> +    }
오잉? 들여쓰기가 변한 이유가 무엇이죠!?

2020-08-24 14:59 UTC, ordinCode commented on hashtagmap-admin/build.gradle
> +    }
수정했습니다~!

2020-08-24 17:26 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +                .limit(SUB_BLACK_LIST_SIZE)
이거 jpa에서 top20, orderby 다 제공하는데 jpa repo에서 쓰는 게 낫지 않나요?!

2020-08-25 01:03 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +                .limit(SUB_BLACK_LIST_SIZE)
타미~ 대단하네요! 하나 배워갑니다 :)

2020-08-25 01:44 UTC, giantim requested changes
리뷰 몇가지 남겼으니 확인해주세요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/BlackListCommandService.java
> +            , InstagramPostRepository instagramPostRepository) {
포매팅 해주세요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/BlackListRequest.java
> +    private String replaceName;
어노테이션이 달린 변수들은 공백으로 구분해주면 가독성이 올라갈 것 같네요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/BlackListResponse.java
> +    }
포매팅 해주세요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/SemiBlackListDto.java
> +public class SemiBlackListDto {
semi라는 네이밍 보다 BlackList가 될 수 있는 후보군이라는 의미가 담기는게 더 명확하지 않을까요? :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +                .limit(SUB_BLACK_LIST_SIZE)
instagramRepository에 ```List<Instagram> findTop20ByOrderByHashtagCountDesc();``` 를 추가하니까 되네요!

2020-08-25 01:44 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +    public void setReplaceName(String replaceName) {
setter를 인자를 두 개 받는 메서드 하나로 통일하면 어떨까요? :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +    private Boolean isSkipPlace;
어노테이션이 붙은 변수는 공백으로 가독성 높여주세요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +@Table(uniqueConstraints = @UniqueConstraint(columnNames = "kakaoId"))
지금 테이블 초기화했을 때 unique constraint 이름을 명시하지 않아서 잘못된 값이 들어가네요!
@UniqueConstraint(columnNames="kakaoId", name="UK_KAKAO_BLACK_LIST") 로 변경해주세요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/Instagram.java
> +    public void setHashtagCount(Long hashtagCount) {
여기도 setter 보다 하나의 메서드가 더 좋을것 같네요 :)

2020-08-25 01:44 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramRepositoryCustom.java
> +    Instagram findByKakaoId(String kakaoId);
여기도 메서드 네이밍에 fetch를 넣어주면 eager loading을 하는게 더 명시적으로 나타날꺼 같네요 :)

2020-08-25 01:48 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/BlackListCommandService.java
> +            , InstagramPostRepository instagramPostRepository) {
포맷팅 된거에요:)
아마 "," 때문에 그런거같은데 저렇게 하면 하나가 삭제 되어도 한줄만 지우면 되는 편함이 있어서 저렇게 했습니다.

2020-08-25 01:50 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/dto/SemiBlackListDto.java
> +public class SemiBlackListDto {
이거 정말 많이 고민하다 그런 의미로 semi를 한건데 혹시 다른 네이밍 추천해주세요

2020-08-25 01:55 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +    public void setReplaceName(String replaceName) {
따로두는게 재사용성측면이나 유지보수에 나을것 같아요

2020-08-25 02:51 UTC, giantim approved these changes

2020-08-25 02:54 UTC, moonyoungCHAE reviewed
학성 수정하느라 수고했어요!!!

2020-08-25 02:54 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/blacklist/service/BlackListCommandService.java
> +        blackListRepository.save(BlackListRequest.toSkipBlackList(blackListRequest));
new BlackList(request.getkakaoId(), request.getReplaceName(), ture));
이런 식으로 하는 게 좋은 거 같아요 저 dto가 skip 관련 로직을 처리 할 필요가 없을 듯

2020-08-25 02:54 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +        updateInstagramPostByBlackList(instagram.getId(), crawlingDto);
Instagram 로직도 메서드로 만들어주세요.
동일한 추상화 수준을 만들어주세요

2020-08-25 02:54 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +            , InstagramScheduleService instagramScheduleService) {
서비스를 가지지 않게 해주세요, 순환참조가 생길 수 있어요.
isSkipPlace, findHashtagName을 따로 빼주세요.

2020-08-25 02:54 UTC, moonyoungCHAE commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/blacklist/api/BlackListApiControllerTest.java
> +                .contentType(MediaType.APPLICATION_JSON_VALUE))
response가 있으면 검증해주세요

2020-08-25 03:46 UTC, moonyoungCHAE approved these changes
처음보다 훨씬 나아졌네요~~! approve할게요

2020-08-25 04:26 UTC, merged