[REFACTOR] 상세 모달 드래그 시 인스타 페이지 열리지 않도록 수정(vuetify로 수정)
woowacourse-teams/2020-songpa-people pull request #211
Opened 2020-08-26 12:06 UTC by DunDung

fixes #208

2020-08-26 12:09 UTC, pci2676 requested changes

2020-08-26 12:09 UTC, pci2676 commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
mdi 이미 npm에서 임포트해서가지고 있지 않나요?

2020-08-26 12:09 UTC, pci2676 commented on hashtagmap-web/front/src/components/detail-modal/Posts.vue
> +      e.target.src = require("../../assets/No-Image.png");
절대경로로 바꿔주세요 @ 가 src에요

2020-08-26 12:16 UTC, DunDung commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
저거 없으니까 모달에 화살표랑 밑에 동그라미가안뜨더라구요..

2020-08-26 12:16 UTC, DunDung commented on hashtagmap-web/front/src/components/detail-modal/Posts.vue
> +      e.target.src = require("../../assets/No-Image.png");
넵!

2020-08-26 13:06 UTC, giantim requested changes
둔덩 수고많았어요~
코드에서는 리뷰 남길 내용 따로 없고 디자인적으로는 학성이 이야기한 대로 아래 부분에 여백을 조금 추가하는 것은 어떨까요?
팀원들이랑 의견 한번 나눠보면 좋을 것 같습니다 :)

2020-08-26 14:30 UTC, moonyoungCHAE commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
@mdi/font, @mdi/js 이렇게 2개 있는데 뒤에거만 설치 돼있어서 그런가봐요

2020-08-26 14:32 UTC, moonyoungCHAE approved these changes
둔덩 짱이네요
다음부터 뷰티파이부터 봐야겠어요
시간 오지게 날렸네요 ㅜㅜ
너무 예쁩니다~~~~~

---

    task copySlackWebHook(type: Copy) {
        description = "Copy slack web hook uri from hashtagmap-secret"
        from '../hashtagmap-secret/slack/application-slack-web-hook.yml'
        into 'src/main/resources/'
    }

이런 gradle 관련 파일은 혹시 왜 수정 된건 가요 ???

---

그리고 머지할 떄 혹시 MainPage.vue
	  ```<v-content>``` -> ```<v-main>```
으로 수정해주시면 감사하겠습니다~~

제가 실수로 안 고쳤나봐요

2020-08-26 18:08 UTC, DunDung commented
슬랙에서 아래 여백은 투표받겠습니다~!

2020-08-26 18:13 UTC, DunDung commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
어떻게 하면 좋을까욤..

2020-08-26 23:24 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/components/detail-modal/Posts.vue
> +      <v-row class="fill-height" align="center" justify="center">
row 빼도 될 것 같습니당

2020-08-26 23:29 UTC, moonyoungCHAE commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
```npm install @mdi/font -D ```  로 설치하고
Posts.vue에  ```import '@mdi/font/css/materialdesignicons.css'```
하면 index.html 에 있는 거 지울 수 있어욥

[참고](https://vuetifyjs.com/en/customization/icons/)

2020-08-27 05:37 UTC, DunDung commented on hashtagmap-web/front/src/components/detail-modal/Posts.vue
> +      <v-row class="fill-height" align="center" justify="center">
이미지 크기가 꽉챠면 상관없는데, 줄였을 때 이미지 가운데 정렬을 잡아주는 친구라서 납둬야할 것 같습니다 ㅠ

2020-08-27 05:50 UTC, ordinCode approved these changes

2020-08-27 05:50 UTC, DunDung commented on hashtagmap-web/front/public/index.html
> +    <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
index.html에 있는거 지웠슴다! 땡큐 타미

2020-08-27 05:50 UTC, giantim approved these changes
오프라인 코드리뷰로 어프루브 할께요 고생 많았습니다 :)

2020-08-27 05:55 UTC, pci2676 approved these changes

2020-08-27 05:56 UTC, merged