[FEAT] 블루그린 무중단 배포 적용
woowacourse-teams/2020-songpa-people pull request #233
Opened 2020-09-10 14:39 UTC by ordinCode

- ProdJenkins에서 feature/2020-songpa-people-230을 가져다가 빌드하는 아이템 하나 만들어서 실험한 결과, 잘 동작합니다.
- 머지가되면 develop환경에서도 돌아가도록 몇가지 설정만 수정해주면 될 것 같아요.

구현하면서 이슈가 몇개 있었는데
- curl -s localhost/profile 과 관련하여 http 를 https로 return 하던것을 제거한 상태 (자세한 설명은 회의할 때 하는게 좋을 것 같아요)
- 그리고 더 있었던 것도 같은데.. 생각나면 추가하거나 나중에 다시 말씀드리겠습니다.

2020-09-13 05:06 UTC, giantim requested changes
학성 무중단 배포 구축 수고하셨습니다!
커밋 메세지가 작업 단위를 묶지 않고 개별로 존재해서 중복도 생기고 가독성이 너무 떨어져서 보기 힘드네요 😥
커밋 메세지를 공통 작업 단위 별로 묶어서 수를 줄이는게 좋아보입니다.
구현에 관한 자세한 내용은 오프라인 리뷰때 듣도록 하겠습니다 :)

2020-09-13 08:07 UTC, giantim approved these changes

2020-09-13 14:01 UTC, DunDung approved these changes
고생하셨슴다 :) nginx 에 추가한 설정도 같이 공유가 되면 더 좋을 것 같아요!

2020-09-13 14:34 UTC, pci2676 approved these changes
고생하셨습니다!
yml 공통설정만 조금 수정해주시면 좋을것 같아요~

2020-09-13 14:34 UTC, pci2676 commented on hashtagmap-web/src/main/resources/application.yml
> +      suffix: .html
공통 설정은 맨위로 빼놔도 될것 같아요

2020-09-14 00:35 UTC, moonyoungCHAE commented on hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/controller/WebRestController.java
> +    private Environment environment;
```suggestion
    private final Environment environment;
```

2020-09-14 00:35 UTC, moonyoungCHAE commented on script/nonstop-deploy.sh
> +sleep 10
이런데서 sleep하는 이유가 있나요?

2020-09-14 00:35 UTC, moonyoungCHAE commented on script/nonstop-deploy.sh
> +for retry_count in {1..10}
여기 Health 체크는 어떤 Health 체크인가요?
그리고 10번이나 시도하는 이유가 있나요? 실패를 많이 하나요?

2020-09-14 00:35 UTC, moonyoungCHAE commented on hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/controller/WebRestControllerTest.java
> +    public void checkProfile () {
mockEnviroment로 하면 SpringBootTest를 뺄 수 있겠네요

``` java
public class ProfileControllerTest {

   @Test
   public void real_profile이_조회된다() {
       //given
       String expectedProfile = "real";
       MockEnvironment env = new MockEnvironment();
       env.addActiveProfile(expectedProfile);
       env.addActiveProfile("oauth");
       env.addActiveProfile("real-db");

       ProfileController controller = new ProfileController(env);

       //when
       String profile = controller.profile();

       //then
       assertThat(profile).isEqualTo(expectedProfile);
   }
```

2020-09-14 00:36 UTC, moonyoungCHAE commented
학성 확인하기 어려운 작업이었을 것 같아요! 수고했어요 정말!
curl -s localhost/profile 과 관련하여 http 를 https로 return 하던것을 제거한 상태 (자세한 설명은 회의할 때 하는게 좋을 것 같아요)
-> 이건 https로 하면 502 에러나는 문제 때문인가요?

2020-09-14 03:05 UTC, moonyoungCHAE approved these changes

2020-09-14 05:51 UTC, merged