[REFACTOR] Event Producer/Consumer 구조로 카카오 스케쥴링 개선하기
woowacourse-teams/2020-songpa-people pull request #234
Opened 2020-09-14 17:00 UTC by pci2676

# 이벤트 플로우
KakaoScheduler -> KakaoSchedulerTask.sourceEvent()
KakaoEvent 생성, KakaoEventHistory 저장

KakaoSchedulerTask.sourceEvent() -> EventBrokerGroup.push(event)
이벤트 브로커가 이벤트 대기큐로써 사용된다 실행되지 않은 이벤트는 모두 이곳에 저장된다.

EventConsumer.consume() -> KakaoEvent.doService()
Consumer가 EventThreadPoolExecutor를 이용해서 Broker에게서 이벤트를 가져다가 소비한다.

KakaoEvent.doService()
kakaoApi릉 이용해서 가게정보를 받아와서 업데이트 후 성공 실패 여부에 따라 KakaoEventHistory의 상태값 변경

closes #140

2020-09-15 18:34 UTC, DunDung approved these changes
고생하셨습니다 비밥 :)
꽤 오래 들여다봤는데 어렵네요 ㅠㅠㅠ
~~각각의 역할은 이제 알겠는데 빈으로 등록된  EventConsumer가 어디서 쓰이는지 모르겠슴다..~~
이해했쑵니다!

2020-09-15 18:34 UTC, DunDung commented on hashtagmap-event/build.gradle
> +    implementation project(':hashtagmap-core')
kakao-scheduler 에서도 implement core를 하구있는데
event 에서 core를 compile project 하구 kakao-scheduler는 implement event만 하는거 어떻게 생각해?!
비밥의 의견이 궁금함다

2020-09-15 18:34 UTC, DunDung commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventBroker.java
> +@Slf4j
로그를 찍지 않는 곳에서도 @Slf4j를 붙여주신 이유가 따로 있는건가요"??? 궁금합니당

2020-09-15 18:34 UTC, DunDung commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/config/EventConfiguration.java
> +@RequiredArgsConstructor
없어도 될 것 같슴다 :)

2020-09-16 00:53 UTC, giantim requested changes
비밥 정말 어려운 구조인데 깔끔하게 잘 구현하신것 같습니다. 수고많았습니다 :)
오프라인 코드 리뷰 할 때 큰 틀을 설명 듣고 테스트 코드도 보니까 구조 이해하는데 많은 도움이 되었습니다! 테스트 코드도 꼼꼼하게 잘 작성해 주셨네요.
간단한 리뷰 몇가지 남겼으니 확인해보시고 반영해주세요 :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/build.gradle
> +    implementation project(':hashtagmap-core')
좋은거 같습니다 ~ :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/KakaoEvent.java
> +        this.eventHistoryId = eventHistoryId;
메서드 명이 동작과 매치되지 않는거 같습니다 :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventBrokerGroup.java
> +public class EventBrokerGroup {
여기에도 사용하지 않는 로그가 있네요 :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
> +        for (Class<? extends Event> eventClass : eventBrokerGroup.keySet()) {
생성자에서 멤버 변수 초기화와 for 구문을 이용해서 스레드 실행까지 두 가지 역할을 하고 있는데 for 구문을 메서드로 추출하면 어떨까요? :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
> +    private boolean runnable = true;
값이 변경되지 않는데 final 어떨까요? :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
> +public class EventConsumer {
여기에도 사용되지 않는 로거가 있네요 :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventThreadPoolExecutor.java
> +            log.warn("semaphore interrupted: {}", e.getMessage());
이 메서드와 아래 execute 메서드에서 로깅 레벨을 warn 으로 설정하신 이유가 궁금합니다 :)
info 레벨이어도 충분하지 않나요?

2020-09-16 00:53 UTC, giantim commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/service/EventService.java
> +}
collect 메서드도 매개변수 타입을 E로 변경하면 구현 클래스에서 형변환 과정이 빠져도 될거 같은데 어떻게 생각하시나요? :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
> +            kakaoEventHistory.fail();
로깅을 남기는건 어떨까요? :)

2020-09-16 00:53 UTC, giantim commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskTest.java
> +
불필요한 공백이 있네요 :)

2020-09-16 01:31 UTC, moonyoungCHAE approved these changes
비밥 탈크루 코드 잘 봤습니다 !!!! :) b
구조에 대한 질문이 있어요!

* 기존 카카오 데이터를 저장하는 방식에서 문제점이 너무 많은 요청을 쏴서 429가 발생하는 것이였는데, 429 문제는 이 구조에서도 마찬가지 아닌가요 ???
* 어제 카톡으로 트랜잭션 문제를 말해주셨는데
```
    public void collectData() {
        List<Zone> zones = zoneRepository.findByActivated();
        List<Rect> rects = RectFactory.from(zones);

        for (Rect rect : rects) {
            for (Category category : Category.values()) {
                List<KakaoPlaceDto> kakaoPlaceDtos = findPlacesByRect(category, rect);

                Set<Document> documents = kakaoPlaceDtos.stream()
                        .flatMap(kakaoPlaceDto -> kakaoPlaceDto.getDocuments().stream())
                        .collect(Collectors.toSet());

                List<Place> places = PlaceFactory.from(documents);
                savePlaces(places);
            }
        }
    }

    private List<KakaoPlaceDto> findPlacesByRect(Category category, Rect rect) {
        return kakaoApiService.findPlaces(category.getCategoryGroupCode(), rect);
    }

    @Transactional
    void savePlaces(List<Place> places) {
        placeRepository.updateAndInsert(places);
    }
```
기존 코드를 보면 저장하는 부분만 트랜잭션이 걸려있는데 어제 카톡으로 카카오 문제점을 트랜잭션 길이가 너무 길다고 말해준 이유가 궁금합니다! 제가 놓친 부분이 있나요?!

2020-09-16 01:31 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventServiceTest.java
> +    @MockBean
EventBrokerGroup은 Bean이 아닌데 MockBean으로 들어가있어요! -> Mock

2020-09-16 01:41 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
> +    public void collect(Event event) {
```java
public interface EventService<E extends Event> {

    void provide(E event);

    // void collect(Event event);
    void collect(E event);
}
```
이렇게 고치고

```java
    // public void collect(Event event) {
    public void collect(KakaoEvent event) {
```
이렇게 바꾸면 어떤가요?

2020-09-16 01:55 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
> +    public void collect(Event event) {
이 부분은 잘 몰라서 물어보는건데
여기 메서드에서 실제 카카오에 call 쏘는 부분까지 트랜잭션에 걸리는데 이정도 요청에서 트랜잭션이 길어지면서 생기는 문제는 없나요?
updateAndInsert에만 트랜잭션을 걸지 않는 이유가 있나요

2020-09-16 02:37 UTC, ordinCode approved these changes
비밥 오프라인에서 한번 설명을 들으니 이해가 잘되네요.
고생많았습니다.

2020-09-16 05:42 UTC, pci2676 commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
> +    private boolean runnable = true;
이부분은 나중에 graceful shutdown을 구현할때 값이 변경될 부분이라서 final을 작성하지 않았습니다!

2020-09-16 05:45 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventServiceTest.java
> +    @MockBean
제가 빈으로 생성해뒀답니다
event configuration쪽에 있어요~

2020-09-16 05:49 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
> +    public void collect(Event event) {
1. abstract 클래스인 Event가 KakaoEvent를 모르기때문에 consumer로 collect를 주입할수가 없어요.

2. kakaohistory를 마지막에 상태값을 변경하고 더티체킹을 하기 위해서는 전체 구간에 transactional을 걸어주어야 합니다.

2020-09-16 05:51 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
> +    public void collect(Event event) {
+ 1. 아예 abstract 메서드를 각 구현 클래스쪽에서 사용하게 하는 방법이 나을수도 있겠다라는 생각이 드네요!

2020-09-16 06:04 UTC, pci2676 commented on hashtagmap-event/build.gradle
> +    implementation project(':hashtagmap-core')
저도 고민했던 부분이긴한데 

> 비밥 탈크루 코드 잘 봤습니다 !!!! :) b
> 구조에 대한 질문이 있어요!
> 
> * 기존 카카오 데이터를 저장하는 방식에서 문제점이 너무 많은 요청을 쏴서 429가 발생하는 것이였는데, 429 문제는 이 구조에서도 마찬가지 아닌가요 ???
> * 어제 카톡으로 트랜잭션 문제를 말해주셨는데
> 기존 코드를 보면 저장하는 부분만 트랜잭션이 걸려있는데 어제 카톡으로 카카오 문제점을 트랜잭션 길이가 너무 길다고 말해준 이유가 궁금합니다! 제가 놓친 부분이 있나요?!

수정 직전의 코드는 트랜잭션의 문제는 없었는데 그 전에는 전체 범위에 트랜잭션이 걸려있지않았나요?
사실 인스타그램하고 카카오하고 계속 왔다갔다 하느라 헷갈리는 상태네요!
429 문제는 여기서도 동일하게 발생할 수 있지만 이전 코드와 다르게 실패한 작업들만 따로관리가 가능해졌다는 점이 있습니다

2020-09-16 06:06 UTC, pci2676 commented
> * 기존 카카오 데이터를 저장하는 방식에서 문제점이 너무 많은 요청을 쏴서 429가 발생하는 것이였는데, 429 문제는 이 구조에서도 마찬가지 아닌가요 ???
> * 어제 카톡으로 트랜잭션 문제를 말해주셨는데
> 기존 코드를 보면 저장하는 부분만 트랜잭션이 걸려있는데 어제 카톡으로 카카오 문제점을 트랜잭션 길이가 너무 길다고 말해준 이유가 궁금합니다! 제가 놓친 부분이 있나요?!

수정 직전의 코드는 트랜잭션의 문제는 없었는데 그 전에는 전체 범위에 트랜잭션이 걸려있지않았나요?
사실 인스타그램하고 카카오하고 계속 왔다갔다 하느라 헷갈리는 상태네요!
429 문제는 여기서도 동일하게 발생할 수 있지만 이전 코드와 다르게 실패한 작업들만 따로관리가 가능해졌다는 점이 있습니다

2020-09-16 06:13 UTC, pci2676 commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventThreadPoolExecutor.java
> +            log.warn("semaphore interrupted: {}", e.getMessage());
InterruptedException 이 익셉션은 개발자가 의도한 익셉션이 아니라서 info 레벨로는 적당하지 않다고 생각했어요!

2020-09-16 06:14 UTC, pci2676 commented on hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/KakaoEvent.java
> +        this.eventHistoryId = eventHistoryId;
id 값을 두다라는 의미에서 사용한건데 더 나은 네이밍이 있을까요? ㅠㅠ

2020-09-16 07:42 UTC, giantim approved these changes
수고많았습니다! :)

2020-09-16 07:43 UTC, merged