[REFACTOR] 인스타그램 크롤링할 때 Batch 적용하기
woowacourse-teams/2020-songpa-people pull request #235
Opened 2020-09-15 13:04 UTC by giantim

스프링 배치를 적용하여 크롤링 작업을 수행하도록 변경했습니다.

closed: #231

2020-09-16 17:14 UTC, pci2676 requested changes

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/README.md
> +    - [ ] 존재하지 않는다면 삽입한다.
todo list는 기능 구현이 다 완성되고 나면 다른곳에 정리하는게 좋을것 같아요
readme의 용도로는 적합하지 않다고 생각해요!

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/job/InstagramBatchWriter.java
> +    void saveCrawlingResult(List<CrawlingResult> crawlingResults) {
`@Transcational` 어노테이션은 public 메서드에서 사용해야합니다
```suggestion
    public void saveCrawlingResult(List<CrawlingResult> crawlingResults) {
```

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/job/InstagramCrawlingJobConfiguration.java
> +    private int chunk;
`@ConfigurationProperties`를 이용해서 properties class 를 만들어서 사용하는게 더 좋을 것 같아요!
`@Value`로 주입하는 건 타입에 대한 안정성이 떨어집니다.

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/HashtagMapBatchApplication.java
> +		System.exit(SpringApplication.exit(SpringApplication.run(HashtagMapBatchApplication.class, args)));
지금 현재 모듈에 다른 배치작업을 추가할수 있는건가요?

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/job/InstagramBatchProcessor.java
> +package com.songpapeople.hashtagmap.job;
루트 애그리거트 / job, process, reader, writer 등의 형식으로 패키지 변경을 한번 해주세요!
만약 배치 모듈이 여러개의 배치 작업을 하지 못하는 거라면 그럴필요는 없겠네요 그렇게 된다면 모듈 이름을 바꿔줘야 할것 같아요!

2020-09-16 17:14 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/job/InstagramCrawlingJobConfiguration.java
> +@Slf4j
사용하지 않고 있네요!

2020-09-17 01:45 UTC, giantim commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/HashtagMapBatchApplication.java
> +		System.exit(SpringApplication.exit(SpringApplication.run(HashtagMapBatchApplication.class, args)));
배치 모듈에 새로운 Job에 대한 빈을 만들어주면 자동으로 등록됩니다!

2020-09-17 02:25 UTC, ordinCode requested changes
라빈타미 고생했습니다.
덕분에 우리 서비스에 batch까지 들어오게 되었네요. 보면서 잘 모르겠는 것들을 코멘트 달았어요~ 확인부탁드립니다.

2020-09-17 02:25 UTC, ordinCode commented on hashtagmap-batch/src/test/java/com/songpapeople/hashtagmap/job/InstagramCrawlingJobReaderTest.java
> +    }
이 테스트는 reader가 db에 저장되어있는 place를 하나씩 읽어오는 건가요?
테스트 이해를 위해서 place id를 3L,4L로 해봤는데 테스트가 실패하더라구요. 3L,4L로 하면 원래 테스트가 실패하는게 맞나요?

테스트 이름을 조금 더 보강했으면 좋겠어요
예를들면 reader: OO에 있는 데이터 조회

추가적으로 place에 아이디를 직접 주고 저장하고 있는데 다른 테스트와 영향을 주고받아서 테스트를 실패할 가능성이 있지 않을까요?
아래와 같이 고치는게 좋지 않을까 싶어요

```java
    @DisplayName("reader: 데이터 조회")
    @Test
    void readerTest() throws Exception {
        // given
        //todo 아이디부분 1,2였는데 3,4하면 실패함
        //이 테스트는 무슨 테스트인가
        //그리고 아이디를 명시적으로 주게되면 다른 테스트 영향을 주고 받지는 않는가?
        Place place1 = Place.builder()
                .build();
        Place place2 = Place.builder()
                .build();
        placeRepository.saveAll(Arrays.asList(place1, place2));
        
        // when, then
        reader.open(new ExecutionContext());
        assertThat(reader.read().getId()).isEqualTo(place1.getId());
        assertThat(reader.read().getId()).isEqualTo(place2.getId());
        assertThat(reader.getPageSize()).isEqualTo(2);

        reader.close();
    }
```

2020-09-17 02:25 UTC, ordinCode commented on hashtagmap-batch/src/test/java/com/songpapeople/hashtagmap/job/InstagramBatchIntegrationTest.java
> +
공란발견

2020-09-17 02:53 UTC, moonyoungCHAE commented on hashtagmap-batch/src/test/java/com/songpapeople/hashtagmap/job/InstagramCrawlingJobReaderTest.java
> +    }
place repo가 빈 상태에서 entity에 3L, 4L을 걸어놔도 table에서 auto increment 해주기 때문에 1L, 2L으로 저장되어서 실패가 맞아요.
좋은 의견 감사합니다~

2020-09-17 14:09 UTC, DunDung approved these changes
굿굿 고생하셨슴다 👍 
이해하기 쉽게 잘짜셨네염

2020-09-17 14:09 UTC, DunDung commented on hashtagmap-batch/build.gradle
> +    implementation project(':hashtagmap-core')
오프라인으로 말했던 instagram-scheduler에서 core를 compile로 알게하는 거 리뷰 남겨놉니다!

2020-09-18 05:03 UTC, moonyoungCHAE approved these changes

2020-09-18 06:49 UTC, pci2676 approved these changes

2020-09-18 07:09 UTC, ordinCode approved these changes

2020-09-18 07:22 UTC, merged