[REFACTOR] 누락 테스트 작성 core 모듈
woowacourse-teams/2020-songpa-people pull request #249
Opened 2020-09-21 12:08 UTC by DunDung

- core 모듈 90.3% 입니당.
- 회의때 말했던 PR템플릿 추가했습니다. 내용도 리뷰해주시면 반영하겠슴다.
- 소나큐브에 나와있던 web모듈에 버그 코드 수정했습니다.
    - CacheControl 파라미터가 Long 타입인데 int변수로 곱하기 하는 코드여서 버그 코드로 떴었고 숫자 뒤에 L을 붙였습니다.

2020-09-21 13:45 UTC, giantim requested changes
둔덩 수고많으셨습니다 :)
리팩토링 대상들도 찾고 다른 모듈에서 변경 사항 반영 안되어있는것들도 잘 잡아주셨네요!
그리고 PR을 템플릿으로 보기 좋게 관리하는 것은 남은 기간은 얼마 안되지만 좋은 생각인것 같습니다!

한가지 문제가 있는데 이거는 오프라인에서 팀 전체 회의를 통해 결정하는게 좋을 것 같습니다.
지금 core 모듈의 build.gradle을 보면 jacoco 커버리지 기준이 0%로 되어있습니다.
왜냐하면 jacoco 리포트를 봤을 때 문제가 있습니다.
![image](https://user-images.githubusercontent.com/39546083/93774098-d42a8000-fc5b-11ea-9a06-b401450bfc39.png)
위 보고서를 보면 Instruction 커버리지가 63%인 클래스가 하나 있고 branch 커버리지가 0%인 클래스가 있습니다.
이 클래스들이 아직 테스트가 안되고 있어서 jacoco 커버리지 퍼센트를 높게 측정해놓지 못했습니다.
소나큐브에서는 line 커버리지로만 측정해서 높게 나오고 있는데 이 문제를 팀원들과 논의한 후에 테스트 코드를 추가하던가 클래스를 제외하는 방식으로 개선해보면 좋을 것 같습니다.
수고 많았습니다 :)

2020-09-21 14:05 UTC, moonyoungCHAE approved these changes
둔덩 빠르게 수정해주셨네요 ~ 굳굳
PR에 트러블 슈팅한 내용을 공유하면 서로 배우는 게 많을 것 같아요. 미리하지 못해 아쉽지만 좋네요~~

2020-09-22 01:34 UTC, ordinCode approved these changes
이것저것 테스트를 많이 추가해주었네요^^ 수고했습니다

2020-09-22 01:54 UTC, pci2676 approved these changes

2020-09-22 13:57 UTC, giantim commented
수고 많았습니다!
jacoco를 bundle로 분석할 때 커버리지가 떨어지는 이슈에 대해서는 더 고민해보도록 하는게 좋겠네요 :)

2020-09-22 13:57 UTC, giantim approved these changes

2020-09-22 14:17 UTC, merged