[REFACTOR] 누락 테스트 작성 event, insta-crawler
woowacourse-teams/2020-songpa-people pull request #252
Opened 2020-09-21 23:02 UTC by pci2676

close #245

2020-09-22 00:47 UTC, giantim requested changes
비밥 수고많았습니다 :)
지금 instagram-crawler 모듈의 MockDataFactory 클래스의 FileReader 부분을 try ~ catch 구문을 빼버려서 버그라고 소나큐브에 나오네요!
![image](https://user-images.githubusercontent.com/39546083/93834948-8f810200-fcb8-11ea-8c1d-3b1ea79c829f.png)
확인 한번 부탁드리고 jacoco에서 테스트 커버리지 정하는거에 대한 의견 둔덩의 pr에 남겼으니까 한번 확인 부탁드릴께요 :)

2020-09-22 01:45 UTC, ordinCode approved these changes
비밥! 수고했습니다
궁금한거 있어서 몇 개 달았어요. 답변해주시면 감사하겠습니다

2020-09-22 01:45 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataFactoryTest.java
> +}
혹시 비밥 경우에는 이렇게 하니까 커버리지 올라가던가요?

2020-09-22 01:45 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/proxy/ProxiesFactory.java
> +
명시적인 의미로 만드는 건가요?

2020-09-22 01:47 UTC, pci2676 commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/proxy/ProxiesFactory.java
> +
유틸성 클래스는 인스턴스를 생성할 필요가 없기 때문에 private 생성자를 만들어서 불필요한 사용을 막아주는게 좋다고 이펙티브자바에 나오더라구요 상속을 막기두하고요!

2020-09-22 01:52 UTC, pci2676 commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataFactoryTest.java
> +}
헉 안되네요 ㅎㅎ exclude 추가해줬습니다.

2020-09-22 13:31 UTC, DunDung approved these changes
고생하셨슴다 👍

2020-09-22 14:04 UTC, DunDung approved these changes
고생하셨습니다 👍

2020-09-22 14:04 UTC, DunDung commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/proxy/ProxiesFactoryTest.java
> +        Assertions.assertThat(declaredConstructor.isAccessible()).isFalse();
요기랑 PlaceNameParserTest 생성자 테스트에는 Assertions를 지워도 될 것 같아요!

2020-09-22 14:15 UTC, moonyoungCHAE approved these changes
Approve하겠습니다 수고하셨어요!

2020-09-23 00:31 UTC, giantim approved these changes
수고하셨습니다 :)

2020-09-23 04:02 UTC, merged