[REFACTOR] 인스타그램 스케줄러 테스트 추가
woowacourse-teams/2020-songpa-people pull request #259
Opened 2020-09-22 16:57 UTC by moonyoungCHAE

PR 내용: 
인스타그램 스케줄러 누락된 테스트 추가했습니다.
핵심 로직에 테스트가 많이 없었어요.. 앞으로는 테스트까지 리뷰 꼼꼼하게 봐야겠어요

특이 사항 및 트러블 슈팅: 

프로젝트 외부 설정:

2020-09-22 17:07 UTC, DunDung approved these changes
고생하셨습니다 👍

2020-09-23 01:14 UTC, giantim requested changes
타미 수고많았습니다 :)
모듈에 기능이 추가되면서 작성되지 않았던 테스트들이 있었네요. 코드 정적 분석 도구를 도입하면서 누락된 테스트를 잘 찾은것 같습니다!
몇 가지 궁금한 내용에 대해서 리뷰 남겼습니다.

2020-09-23 01:14 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
이 속성 지운 이유가 있나요? :)

2020-09-23 01:14 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
> +        final int NOT_ENOUGH_HASHTAG_COUNT = 100;
카멜케이스로 변수 선언하는게 컨벤션입니다 :)

2020-09-23 01:14 UTC, giantim commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/exception/InstagramSchedulerExceptionStatus.java
> +    NOT_ENOUGH_HASHTAG_COUNT(String.format("해시태그 검색 결과가 %d개 미만입니다.", CrawlingResult.MIN_HASHTAG_COUNT), "INSTAGRAM_SCHEDULER_1000");
예외를 통일한 이유가 궁금하네요 :)

2020-09-23 01:14 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleServiceTest.java
> +        String NEW_HASHTAG_NAME = "블루보틀";
테스트 클래스 전체적으로 메서드 내부 변수들 선언할 때 카멜케이스로 안한 이유가 있나요? :)

2020-09-23 13:42 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/exception/InstagramSchedulerExceptionStatus.java
> +    NOT_ENOUGH_HASHTAG_COUNT(String.format("해시태그 검색 결과가 %d개 미만입니다.", CrawlingResult.MIN_HASHTAG_COUNT), "INSTAGRAM_SCHEDULER_1000");
not exist 사용되는 부분이 없었어요!

2020-09-23 13:44 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
꼭 처음부터 isSkip이 false라고 단정 지을 필요가 없다고 생각했어요. 테스트를 짤 때 isSkip이 디폴트 false면 저장 후에 다시 true로 변환해야 하는데 실제 운영할 때에도 처음부터 isSkip을 true로 설정할 경우가 있을 것 같았어요. 그리고 생성자로 충분히 false 초기화 효과를 줄 수 있어서 테이블에서 강제하지 않았어요.

2020-09-23 13:46 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleServiceTest.java
> +        String NEW_HASHTAG_NAME = "블루보틀";
상수라는 의도를 주고 싶었어요,,

2020-09-23 14:02 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleServiceTest.java
> +        String NEW_HASHTAG_NAME = "블루보틀";
상수는 변수 이름으로 의도를 표현하는게 아닌 final 키워드를 사용해서 지정하셔야죠! :)

2020-09-23 14:04 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
> +        final int NOT_ENOUGH_HASHTAG_COUNT = 100;
이거는 타미가 구현한 내용이 맞네요 :)
저희가 처음에 따르기로 했던 [네이버 캠퍼스 핵데이 Java 코딩 컨벤션](https://naver.github.io/hackday-conventions-java/#constant_uppercase) 을 확인하니 static final 이 아니어도 상수 변수 이름은 대문자와 언더스코어로 만드는거였네요!

2020-09-23 14:07 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
운영환경에서 isSkip 값을 true로 설정할 경우가 있을 수도 있으니 바꾸는거는 좋아보입니다.
하지만 현재 운영환경에 대한 반영사항이 전혀 없네요!
지금 운영환경에서는 isSkip 값이 모두 false로 기본값이 들어가있어야 이 코드가 머지된 후 배포가 되었을 때 장애가 발생하지 않습니다. 기존에 이 부분에 대한 테스트 코드가 없었어서 검증이 안되어서 넘어가신거 같은데 BlackList 객체를 사용하는 부분에서 isSkip 값을 false로 초기화하는 로직들을 추가해주세요 :)

2020-09-23 14:21 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
그동안 해시태그이름+isSkip 둘다 초기화하는 생성자를 쓴 부분이 없어서 지금이나 전이나 다 false 초기화이기 때문에 로직 따로 추가할 필요는 없을 것 같아요.!!:> 디비는 수정해야겟네여~~

2020-09-23 14:32 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
isSkip이 Boolean 이어서 초기화를 안하면 null이 들어가지 않나요? :)

2020-09-23 14:35 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> -    @Column(columnDefinition = "bit default 0")
제가 코드 잘못봤네요! 감사합니다!

2020-09-24 01:03 UTC, ordinCode approved these changes
수고했습니다. 피드백 하나만 반영해주세요

2020-09-24 01:03 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +import javax.persistence.*;
이부분은 다시 이전과 같이 하나하나 풀어주는게 좋을 것 같습니다 수정해주세요.

2020-09-24 01:08 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
> +import javax.persistence.*;
앗 제가 인텔리제이를 다시 깔아서 자동 포맷팅 돼버렸네요 굳!

2020-09-24 02:16 UTC, pci2676 approved these changes

2020-09-24 03:20 UTC, giantim approved these changes
수고 많았습니다 타미! 질문에 답변도 감사합니다 :)

2020-09-24 03:26 UTC, merged