[DOCS]  hashtagmap-common, hashtagmap-core 모듈 README.md 작성
woowacourse-teams/2020-songpa-people pull request #260
Opened 2020-09-22 16:59 UTC by DunDung

PR 내용: 
JPA 의존성에 설명을 달으려다가 관련된 다른 의존성을 사용한 것도 아닌데 도입 이유 같은 걸 달아줄 필요가 있을까?란 생각이 들어서 설명이 필요한 JDBC만 설명을 달아놨습니다.  다른 분들 의견도 달아주세요!
부족한 내용 지적바랍니다~~!

특이 사항 및 트러블 슈팅: 

프로젝트 외부 설정: 

fixes: #256

2020-09-22 17:11 UTC, moonyoungCHAE commented on hashtagmap-common/README.md
> +- 외부 의존 관계, 시스템내 의존 관계를 갖지 않고 순수 Java class 만 정의할 수 있다.
```suggestion
- 외부 의존 관계, 시스템 내 의존 관계를 갖지 않는 순수 Java class 만 정의할 수 있다.
```

2020-09-22 17:11 UTC, moonyoungCHAE commented on hashtagmap-common/README.md
> +- 모든 모듈에서 공통으로 사용할 수 있는 커스텀 예외 객체 등을 제공하는 모듈
예외 객체만 저장하는 것처럼 읽혀요! 
- 모든 모듈에서 공통으로 사용할 수 있는 모듈
- Type, Util 성격, Dto, 커스텀 예외 객체

이런 식으로 쓰면 어떤가요

2020-09-22 17:11 UTC, moonyoungCHAE commented on hashtagmap-core/README.md
> +    - uniqeu key로 저장된 값에 ON DUPLICATE KEY UPDATE 쿼리를 native sql로 작성하기 위함
이게 필요한 이유는 네이티브 쿼리 자체를 사용한 것보다
네이티브 쿼리에 배치 업데이트를 하기 위함 아닌가요?

2020-09-23 01:22 UTC, giantim requested changes
둔덩 수고하셨습니다 :)
몇 가지 의견 남겼는데 다른 팀원들 의견도 들어보고 수정해봐요!

2020-09-23 01:22 UTC, giantim commented on hashtagmap-core/README.md
> +    - uniqeu key로 저장된 값에 ON DUPLICATE KEY UPDATE 쿼리를 native sql로 작성하기 위함
둔덩이 적은 내용이 더 맞는것 같습니다.
네이티브 sql을 이용하려고 Spring JDBC 의존성을 추가했는데 거기서 배치로 업데이트 기능을 제공해 주었습니다.
이 기능을 구현할때는 배치로 작업하려고 하지는 않았었습니다 :)

2020-09-23 01:22 UTC, giantim commented on hashtagmap-common/README.md
> +- 모든 모듈에서 공통으로 사용할 수 있는 커스텀 예외 객체 등을 제공하는 모듈
타미 궁금한게 있는데요 :)
- Type은 enum을 말하는 건가요?
- Dto는 모듈 내에 정의된 도메인에 영향을 받을 것 같아서 common에는 포함 안되지 않을까요?

저는
- 모든 모듈에서 공통으로 사용하는 객체를 제공하는 모듈
- Util 클래스, 커스텀 예외 객체 등

이런 식으로 작성하는 것은 어떨가 싶습니다 :)

2020-09-23 02:02 UTC, ordinCode commented on hashtagmap-common/README.md
> +- 모든 모듈에서 공통으로 사용할 수 있는 커스텀 예외 객체 등을 제공하는 모듈
라빈에 한표

2020-09-23 02:09 UTC, ordinCode approved these changes
수고했슴다

2020-09-23 02:09 UTC, ordinCode commented on hashtagmap-core/README.md
> +    - uniqeu key로 저장된 값에 ON DUPLICATE KEY UPDATE 쿼리를 native sql로 작성하기 위함
추가로 설명한 부분 좋네요

2020-09-23 02:09 UTC, ordinCode commented on hashtagmap-core/README.md
> +- hashtagmap-common 모듈을 이용해 커스텀 예외 객체를 사용한다.
이부분은 빼도 되지 않을까하는 **작은** 의견이 있습니다.

2020-09-23 14:26 UTC, moonyoungCHAE commented on hashtagmap-common/README.md
> +- 모든 모듈에서 공통으로 사용할 수 있는 커스텀 예외 객체 등을 제공하는 모듈
타입은 킹뽀대님 블로그에 있던 내용인데 enum도 포함되겠네요

2020-09-23 14:27 UTC, moonyoungCHAE commented on hashtagmap-core/README.md
> +    - uniqeu key로 저장된 값에 ON DUPLICATE KEY UPDATE 쿼리를 native sql로 작성하기 위함
네이티브 쿼리는 의존성 추가없이 @query 이걸루두 되는 거 아닌가요??

2020-09-24 01:49 UTC, DunDung commented on hashtagmap-core/README.md
> +- hashtagmap-common 모듈을 이용해 커스텀 예외 객체를 사용한다.
좋은 의견입니다 :) 뺐습니다

2020-09-24 01:50 UTC, DunDung commented on hashtagmap-core/README.md
> +    - uniqeu key로 저장된 값에 ON DUPLICATE KEY UPDATE 쿼리를 native sql로 작성하기 위함
- batch update를 List로 넘겨서 효율적으로 처리하기 위함 으로 수정했습니다 ㅎㅎ_+ㅎ

2020-09-24 01:50 UTC, DunDung commented on hashtagmap-common/README.md
> +- 모든 모듈에서 공통으로 사용할 수 있는 커스텀 예외 객체 등을 제공하는 모듈
일단 애매하니까 라빈말대로 반영을 했습니다!

2020-09-24 02:15 UTC, pci2676 approved these changes

2020-09-24 06:51 UTC, giantim approved these changes
수고하셨습니다 둔덩 :)

2020-09-24 09:27 UTC, moonyoungCHAE approved these changes

2020-09-24 09:53 UTC, merged