[DOCS] hashtagmap-batch, hashtagmap-scheduler모듈의 README.md 작성
woowacourse-teams/2020-songpa-people pull request #262
Opened 2020-09-22 23:24 UTC by moonyoungCHAE

PR 내용: 

특이 사항 및 트러블 슈팅: 

프로젝트 외부 설정:

2020-09-23 01:27 UTC, giantim requested changes
타미 수고하셨습니다 :)
궁금한게 크롤링이라는 우리 서비스의 도메인 용어를 갑자기 웹 스크래핑이라고 바꾼 이유가 있을까요?
좀 헷갈리네요!

2020-09-23 01:27 UTC, giantim commented on hashtagmap-batch/README.md
> +- Batch성 Job을 처리하는 모듈
Job은 배치 작업 단위를 말하니까 ```Batch성``` 이라고 표현하지 않고 ```Batch Job``` 이라고 표현하는게 더 적합해 보이네요 :)

2020-09-23 01:27 UTC, giantim commented on hashtagmap-batch/README.md
> +- 인스타그램 해시태그 개수를 웹 스크래핑한다.
크롤링 작업을 스크래핑이라고 표현하는 이유가 있나요? :)
다른 pr의 리뷰에서도 이렇게 표현하시던데 갑자기 도메인 용어가 바뀐게 어색하네요!

2020-09-23 01:27 UTC, giantim commented on hashtagmap-instagram-scheduler/README.md
> +- Instagram 크롤러 모듈을 활용해 크롤링한다.
두 문장의 의미가 중복되 보입니다 :)

2020-09-23 01:50 UTC, DunDung approved these changes
고생하셨슴다 :)

2020-09-23 01:50 UTC, DunDung commented on hashtagmap-batch/README.md
> +- 인스타그램 해시태그 개수를 웹 스크래핑한다.
제가 알아봤을 땐 저희가 하는 로직자체가 웹 스크래핑이고
일반적으로 크롤링이라고 불리니까 그냥 크롤링으로 용어를 통일해도 무방할 것 같아요.
저희 프로젝트에서 스크랩핑과 크롤링을 구분하는 건 조금 무의미하다?.. 라는 생각이 들어요.

2020-09-23 01:50 UTC, DunDung commented on hashtagmap-batch/README.md
> +- Batch성 Job을 처리하는 모듈
- 아래줄은 지우고 instagram-service 모듈을 사용해서 Batch Job을 처리하는 모듈~~ 과 같은 식으로 하는건 어떤가요??

2020-09-23 01:50 UTC, DunDung commented on hashtagmap-instagram-scheduler/README.md
> +- Instagram 크롤러 모듈을 활용해 크롤링한다.
저도 두 문장을 합치는게 조아보여요!

2020-09-23 02:07 UTC, ordinCode approved these changes

2020-09-23 02:07 UTC, ordinCode commented on hashtagmap-batch/README.md
> +- Batch성 Job을 처리하는 모듈
제 생각은 해당 모듈이 현재 인스타 서비스 작업을 하기는하지만 확장가능성을 열어두고있으니 그냥 batch job을 하는 모듈이라는 설명만 하면 어떨까 싶어요

2020-09-23 14:14 UTC, moonyoungCHAE commented on hashtagmap-batch/README.md
> +- Batch성 Job을 처리하는 모듈
batch성 작업이 어떤 게 있는지까진 써주는 게 보는 사람이 이해하기 쉽지 않을까해서 써봤어요!! 인스타로 한정되는 것처럼 보인다면 배치잡에는 인스타가 있다 요런 식으로 쓰는 건 어떤가요

2020-09-23 14:15 UTC, moonyoungCHAE commented on hashtagmap-batch/README.md
> +- 인스타그램 해시태그 개수를 웹 스크래핑한다.
쉽게 말해서 웹 크롤링은 그냥 돌아만 다니는 거고 스크래핑은 긁어 오는 것이다.

그래서 우리가 보통 크롤링을 한다고 하는것은 사실은 스크래핑이라고 할 수 있다.
-
우리가 한 건 스크래핑이 맞긴 한데 객체명도 크롤러이고 일반적으로 크롤링이라고 부르니 크롤링으로 바꿀게요. 배경지식 정도로만 알아두면 좋을 것 같아요

2020-09-24 02:17 UTC, pci2676 approved these changes

2020-09-24 03:57 UTC, giantim approved these changes
고생하셨습니다 타미!
피드백 반영 감사합니다 :)

2020-09-24 03:58 UTC, merged