[REFACTOR] Spring Batch 리팩토링
woowacourse-teams/2020-songpa-people pull request #281
Opened 2020-09-30 15:23 UTC by moonyoungCHAE

즐추 ~~ ^__^ 리뷰는 늦게 해도 괜찮습니다,,

PR 내용: 
* 에러 구체화 (404,429)
  * 404면 3번 돌 필요가 없고 우리가 404,429가 몇 개인지 알기 위해서는 2개를 분리하는 게 나은 것 같아서 분리함!
* Optional 지우기
* 에러나도 끝까지 돌게 하기

특이 사항 및 트러블 슈팅: 
* Optional을 인스타그램 서비스쪽도 다 빼버릴까 생각하다가 저쪽은 오히려 Optional이 있는 게 안전한 것 같아서 batch에서만 뺐습니당
* 착각한 게 있었는데 원래도 에러나도 끝까지 돌아가는 거였음! 왜냐하면 인스타그램 서비스에서 에러났을 때 에러를 throw하는 게 아니라 Optional.empty(), 즉 null을 반환하기 때문에 끝까지 돌아감!
* @학성 @DunDung URL_NOT_CONNECT("연결할 수 없는 URL 입니다.", "CRAWLER_1001") 
이거 404,429 이외에 포함되는 게 있어? 없다면 지워도 될 것 같아서 물어봄~~
(참고) 코드 보면 알겠지만 URL_NOT_CONNECT는 IOException 에서 받고, 404,429는 HttpStatusException 임!
public class HttpStatusException extends IOException

프로젝트 외부 설정:

2020-10-01 15:21 UTC, pci2676 commented
타미 젠킨스에서 테스트가 깨지네요~ 확인해주세요~

2020-10-01 16:12 UTC, moonyoungCHAE commented
크흠 로컬에서는 잘 돌아가는데 젠킨스가면 에러가 나네요...ㄸㄹㄹ

2020-10-02 20:09 UTC, pci2676 approved these changes
깔끔하네요
댓글 확인해주세요

2020-10-02 20:09 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
문득 든 생각인데 batch chunk 단위는 바꿀일이 없을까요? JobParameter로 받아오는게 더 용이할것 같다는 생각이 들어서요~

2020-10-02 20:09 UTC, pci2676 commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/CrawlerTest.java
>      @DisplayName("크롤링 정상 동작 테스트")
displayname에 mock 이라고 써주는게 좋을것 같아요

2020-10-03 09:16 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
좋은 의견이네요. 그런데 어떤 경우 바꾸게 될 지 잘 상상이 가지 않네요. batch chunk는 rollback을 위해 한번에 처리되는 데이터 단위라고만 생각했는데 어떤 경우에 바꾸게 될까요?!

2020-10-03 11:01 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
지금은 batch job이 하나지만 여러개의 잡이 생길경우에 모든 job이 동일한 chunk size를 가지게 되는건 이상하다고 생각되지않나요???

2020-10-03 11:09 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
예를 들어 카카오도 batch에 추가하여 아예 다른 job이면 chunkSize를 각각 만들어 2개 만들어놓는다고 생각했어요!
외부에서 chunkSize를 넣어주는 상황이라면 같은 job이여도 상황마다 다를 때여야 하지 않을까요.

2020-10-04 06:24 UTC, pci2676 commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
그렇게도 되긴 하겠네요!
저는 batch에 사용되는 데이터가 점점 늘어나면 그에따라 chunkSize를 변경해야하는데 그때마다 코드를 고치는게 부자연스러울것 같다고 생각했거든요
그리고 job이 10개면 10개의 property를 관리해야하니까 그것도 힘들것 같다고 생각했어요

2020-10-04 07:39 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
>      @Transactional
```suggestion
```
지우는 게 스프링 배치 전략과 맞을 것 같습니다~~
https://velog.io/@moonyoung/Spring-Batch-Tasklet-Transaction

2020-10-04 07:40 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
그럴수도 있겠네요~~ 전 chunkSize를 실행할 때 넣어주면 의도와 맞지 않는 chunkSize가 들어올 것이 우려스럽다고 생각했습니당! 그러면 지금은 instagram 하나만 있으니까 이대로 해놔도 될까요??

2020-10-04 14:47 UTC, giantim commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/config/InstagramCrawlingJobConfiguration.java
> +                .<Place, CrawlingResult>chunk(batchConfiguration.getChunk())
배치 작업 마다 파라미터를 넘겨받아서 실행하는 이슈를 새로 만드는게 좋아보이네요 :)

2020-10-04 15:06 UTC, giantim requested changes
타미 연휴에도 쉬지 않고 고생 많으셨습니다 :)

테스트 코드를 새로 작성한 부분에 대해서 로컬에서 소나큐브를 최신화해서 이전과 달라진 점이 없는지 꼭 확인 부탁 드릴께요!
현재 추가하신 부분에 대해서는 instagram-service 모듈에 대해 이슈가 생겼습니다.
-> 이 부분은 #284 이슈를 해결하고 생각해 봐야 할 것 같네요!

간단한 리뷰 몇가지 남겼으니 반영 부탁 드릴께요 :)

2020-10-04 15:06 UTC, giantim commented on hashtagmap-instagram-service/src/test/java/com/songpapeople/hashtagmap/service/CrawlerWithProxyTest.java
> +        verify(instagramCrawler, times(3)).crawler(place.getPlaceName());
@DisplayName과 맞지 않는 동작 검증을 하고 있네요 :)
크롤링 결과가 안나올 때 최대 3번 까지 다시 검사하게 로직을 설계했는데 여기서 1번만 검사하려고 했던 이유가 있을까요?

2020-10-04 15:06 UTC, giantim commented on hashtagmap-instagram-service/src/test/java/com/songpapeople/hashtagmap/service/CrawlerWithProxyTest.java
> +        verify(instagramCrawler, times(3)).crawler(place.getPlaceName());
![image](https://user-images.githubusercontent.com/39546083/95018892-4e67f500-069d-11eb-932e-ac1e50347db0.png)

그리고 해당 테스트 코드를 로컬에서 실행하면 3회 실행 되고 있는것 같습니다!

2020-10-04 15:06 UTC, giantim commented on hashtagmap-instagram-crawler/build.gradle
> +    testImplementation group: 'org.mock-server', name: 'mockserver-netty', version: '5.11.1'
새로운 테스트 의존성을 추가했는데 간단하게 도입 배경이나 사용법 등을 설명해 주실 수 있을까요? :)

2020-10-04 15:06 UTC, giantim commented on hashtagmap-instagram-service/src/main/java/com/songpapeople/hashtagmap/service/CrawlerWithProxy.java
> +            }
소나큐브를 최신화 시켰는데 새로 추가한 이 부분이 테스트에서 검증되지 않고 있다고 나오네요!
한번 확인해주세요 :)

2020-10-05 07:37 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/build.gradle
> +    testImplementation group: 'org.mock-server', name: 'mockserver-netty', version: '5.11.1'
크롤링할 때 서버를 mocking하기 위해 사용했습니당! 사용법은 정리해서 올리도록 하겠습니다

2020-10-05 07:42 UTC, moonyoungCHAE commented on hashtagmap-instagram-service/src/test/java/com/songpapeople/hashtagmap/service/CrawlerWithProxyTest.java
> +        verify(instagramCrawler, times(3)).crawler(place.getPlaceName());
이부분은 제가 displayName을 잘못 작성했네요 ! 3번이 맞습니다. 404일 경우에는 1번만 동작합니다.

2020-10-05 07:50 UTC, moonyoungCHAE commented on hashtagmap-instagram-service/src/main/java/com/songpapeople/hashtagmap/service/CrawlerWithProxy.java
> +            }
꼼꼼하게 확인해줘서 고맙습니다! 수정되었습니다.

2020-10-05 14:19 UTC, ordinCode requested changes
CrawlerExceptionStatus.NOT_FOUND_URL 관련
- 나도 HttpStatusException에서는 아마 404랑 429말고는 없을 것 같아서 빼도 될것 같은데 IOException 에 있는거는 예상못한게 있을 수 있으니까 놔두는것도 괜찮을듯

인스타그램 서비스에 옵셔널 살려두는것 좋네요!

타미 수고했습니다~ 코드보면서 의아한거 하나 남겼는데 확인부탁드려요

2020-10-05 14:19 UTC, ordinCode commented on hashtagmap-batch/src/test/java/com/songpapeople/hashtagmap/instagram/InstagramBatchIntegrationTest.java
> +        when(instagramCrawlingService.createCrawlingResult(places.get(2))).thenReturn(Optional.of(crawlingResult3));
크롤링하다가 중간에 Exception이 터지더라도 끝까지 크롤링을 진행하는지 보는 테스트 같은데 그러면 
```java
when(instagramCrawlingService.createCrawlingResult(places.get(1))).thenReturn(Optional.empty());
```
이부분은
```java
when(instagramCrawlingService.createCrawlingResult(places.get(1)))
                .thenThrow(new CrawlerException(CrawlerExceptionStatus.TOO_MANY_REQUEST));
```
요런식으로 해야하지 않나요?

일단 제가 생각한대로 했을 때는 테스트가 실패하네요. 혹시 제가 잘 못 생각한거일수도 있으니 코멘트 부탁드려요.

2020-10-05 14:23 UTC, DunDung approved these changes
고생하셨슴다 타미 💯 
URL_NOT_CONNECT는 지워도 되겠네요!
그리고 3번 반복하는 로직도 이제 없어도 될 것 같아요.,
원래 크롤링 되는 건데 프록시 때매 안될 경우를 대비해서 3번 돌게 했던 건데 이제 필요없어요...
그건 제가 지우도록할게영

2020-10-06 17:48 UTC, moonyoungCHAE commented on hashtagmap-batch/src/test/java/com/songpapeople/hashtagmap/instagram/InstagramBatchIntegrationTest.java
> +        when(instagramCrawlingService.createCrawlingResult(places.get(2))).thenReturn(Optional.of(crawlingResult3));
요건 service에서 예외가 터지면 결국 empty를 반환하기 때문에 이런 식으로 해놨습니다!
근데 이제 404 이외 에러가 발생하면 throw하는 방식으로 수정해서 학성 말대로 수정하겠습니다~~

2020-10-07 04:01 UTC, giantim approved these changes
수고하셨습니다 :)

2020-10-07 06:42 UTC, ordinCode approved these changes

2020-10-07 06:56 UTC, merged