QueryDsl 상속 구조 없애기, QueryDsl 조회 로직 DTO로 수정
woowacourse-teams/2020-songpa-people pull request #289
Opened 2020-10-07 10:47 UTC by DunDung

PR 내용: 

특이 사항 및 트러블 슈팅: 

프로젝트 외부 설정: 

fixes #286

2020-10-07 11:16 UTC, giantim requested changes
둔덩 수고많았습니다 :)
dto로 바꾸는 구조인데 생각보다 수정할 부분이 많았네요!
질문 남겼으니 답변 부탁드릴께요!

2020-10-07 11:16 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForBlacklist.java
> +InstagramForBlacklist {
포매팅이 어색하네요 :)

2020-10-07 11:16 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
상속을 구현하지 않고 만든 레포지토리와 레포지토리에서 이용하는 dto들의 위치에 대해서 저는 다른 생각을 합니다!
지금은 hashtagmap-core모듈에 위치하고 있는데 JPAQueryFactory를 이용한 레포지토리들은 해당 레포지토리를 호출하는 모듈에 위치하는게 맞지 않을까요?
해당 레포지토리는 특정 엔티티를 사용하지 않고 필요한 값만 갖는 dto를 이용합니다. 근데 dto같은 경우에는 뷰의 요구 사항이 변경될 때마다 dto가 담는 값도 변경될 수 있을것 같습니다. 그럼 그 요구사항을 반영해야 하는 모듈에 dto와 레포지토리가 위치해야 할 것 같다고 생각합니다. 지금 구조에서는 admin의 뷰 요구 사항이 변경되었을 때 admin 모듈이 아닌 core 모듈에서 해당 dto를 수정해야 하는 구조 같아 보입니다.

다른 분들은 어떻게 생각하시는지 궁금합니다 :)

2020-10-07 11:21 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForBlacklist.java
> +InstagramForBlacklist {
앗 뭐죠 이거 실수했네요..

2020-10-07 11:27 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
오호... 당연하게 있던자리에 만들었는데
dto를 리턴니까 그렇게 바뀌는게 맞는 것 같네요.. 역시 라빈... 👍

2020-10-08 07:35 UTC, moonyoungCHAE reviewed
둔덩! 할 게 꽤 많았네요! 간단한 이슈인 줄 알았는데 고생 많았습니다~~
더불어 블랙리스트쪽까지 정리하고 굳 b
리뷰 남겼는데 확인 부탁합니당~!!

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +    public Instagram toInstagram() {
요건 좀 위험한 변환 아닐까요,,
이런 게 필요하다면 레이지 로딩으로 했어야 하는 거 아닌가 싶었습니당!

물론 더티체킹으로 바뀐 부분만 저장하긴 하는데
다른 개발자가 초기화되지 않은 instagram의 필드,place의 필드를 사용할 수 있는 오해를 주진 않을까요

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
요놈의 존재 이유에 대해 고민해봤는데 사용되는 곳이

```java
    @Transactional
    public void deleteInstagramAfterAddBlackList(BlackListRequest blackListRequest) {
        blackListRepository.save(BlackListRequest.toSkipBlackList(blackListRequest));
        InstagramForUpdate instagramForUpdate = instagramQueryRepository.findByKakaoId(blackListRequest.getKakaoId());
        instagramPostRepository.deleteByInstagramId(instagramForUpdate.getId());
        instagramRepository.deleteById(instagramForUpdate.getId());
    }

    @Transactional
    public Instagram updateInstagramByBlackList(String kakaoId, String replaceName) {
        saveOrUpdateBlackList(new BlackList(kakaoId, replaceName));
        InstagramForUpdate instagramForUpdate = instagramQueryRepository.findByKakaoId(kakaoId);
        Instagram instagram = instagramForUpdate.toInstagram();
        CrawlingDto crawlingDto = instagramCrawler.crawler(replaceName);
        instagram.updateInstagram(replaceName, crawlingDto.getHashtagCount());
        updateInstagramPost(instagram.getId(), crawlingDto);
        return instagramRepository.save(instagram);
    }

```
이렇게 2군데 더라구요.
deleteInstagramAfterAddBlackList : findIdByKakaoId
updateInstagramByBlackList : Instagram 통으로 가져오기
는 어떨까 생각했어요
둔덩은 어떻게 생각하나요?

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForMaker.java
> +public class InstagramForMaker {
```suggestion
public class InstagramForMarker {
```

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    public List<InstagramForMaker> findAllFetch() {
findAllFetch 에서 Fetch를 명시한 이유가 있나요?! 
저는 Query DSL에서 실행할 때 사용되는 fetch는 데이터를 가져온다는 의미만 있는 걸로 알고 있었느데 다른 의도가 있나요? 궁금해서 질문~

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +
```suggestion
```

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
Batch에서는 findAll을 지양해야 한다고 해요!
원래부터 findAll로 되어있었군요..ㅠㅠ
물론 우리 데이터가 많지 않은 건 맞는데 ㅋㅋㅋㅋ
요놈을 싱글톤으로 만들거나 query로 찌르는 건 어때요

2020-10-08 07:35 UTC, moonyoungCHAE commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForBlacklistTest.java
> +        String roadAddressName = "서울시 강남구";
홍대입구인데 ㅋㅋㅋㅋ 강남구인가요.ㅋㅋ
장난입니다

2020-10-09 04:36 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +    public Instagram toInstagram() {
음...제 생각은 저런식의 변환이 없다면 querydsl을 사용하면서 조회로직에 DTO를 사용하는 것 자체가 불가능하다고 생각해요.. 어차피 무조건 사용될 필드들만 dto에 넣어둔건데 레이지 로딩으로하면 DB에 다시 찔러야한다는 단점이 있다고 생각하는데 타미는 왜 레이지 로딩으로 했어야한다고 생각했는지 궁금합니다!

 다른 개발자들이 이름에서부터 forUpdate인 dto를 toInstagram으로 Instagram객체를 변환했을 때 update를 위해 Instagram을 변경하는데만 사용하지 다른 용도로 사용하지 않을 것 같다고 생각했어요.

다른 적절한 대안있으시면 추천해주세요!

제 의견일 뿐입니다..! 다른분들 의견도 궁금합니다.

2020-10-09 04:40 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
![image](https://user-images.githubusercontent.com/33235211/95543854-9045c200-0a34-11eb-8059-28f8e81f12a6.png)

저는 조졸두님의 글을 읽고 dto 사용이유 중 핵심이 불필요한 조인과 필드를 가져오지 않는 것이라고 생각했어요. updateInstagramByBlackList를 위해서는 instagram id와 place id만 필요하고 조인도 필요없는데 굳이 통으로 다 가져올 필요가 없다고 생각합니다! 
이것도 제의견일 뿐입니다.. 다른 대안이나 다른 생각들도 말씀해주세요!!

2020-10-09 04:41 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForMaker.java
> +public class InstagramForMaker {
앗 오타가있네요 ㅎ.

2020-10-09 04:43 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    public List<InstagramForMaker> findAllFetch() {
흠 원래 Instgram엔티티를 가져올때는 레이지로딩으로 가져오는게 아니라 패치조인으로 통으로 가져온다는 의미에서 Fetch를 붙였었는데 이제 Dto에... queryDsl전용 레포지토리가있으니 굳이 붙일 필요가없을 것 같네요! 추천하시는 네이밍 있나요!?!?

2020-10-09 04:47 UTC, DunDung commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
Batch에서 findAll을 지양해야 하는 이유가 궁금해요. query로 findAll해오는거랑 제공되는 findAll을 하는거랑 무슨차이가 있는지도 궁금합니다!
싱글톤으로 만든다면 어떤걸 싱글톤으로 만드신다는 의도인지도 궁금합니다!!!!

2020-10-09 04:47 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
그런 점도 있겠네요! placeId가 사용되는 곳은 안보이는데.. id만 필요하다면 아래와 방법은 어떤가요.
결국 이미 저장된 instagram을 업데이트하는 게 목적이니까 findIdByKakaoId로 Id를 가져온 다음에
Instagram instagram = new Instagram(id);
// 크롤링
instagram.update();
이런 식으로 하면 어떨까요
그러면 toInstagram 없이도 Instagram 객체를 만들 수 있고
들어있지 않은 필드가 한 눈에 보여서 없는 필드를 사용할 위험도 없을 것 같아요 !!

2020-10-09 04:47 UTC, DunDung commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForBlacklistTest.java
> +        String roadAddressName = "서울시 강남구";
대도시 인천인은 그런거 신경안씁니다..

2020-10-09 04:49 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    public List<InstagramForMaker> findAllFetch() {
findInstagramForMarkers 어때요

2020-10-09 04:52 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
배치에서는 대용량 데이터를 사용하니까 많은 데이터를 findAll하지말란 건데 생각해보니 저희는 굳이 그렇게 안해도 되겠네요 싱글톤도 같은 맥락에서 findAll을 계속하지 말자는 의도에서 제안한건데 지금대로 해도 될 것 같아요!ㅋㅋ

2020-10-09 04:55 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +    public Instagram toInstagram() {
레이지로딩은 제가 잘못 말했네욤.. instagram 안에 있는 필드가 다 있어야 되지 않냐 그 이야기를 하고 싶었어요! ㅋㅋ 둔덩 말대로 사용할 수 있지만 저는 forUpdate에 필요한 필드는 뭐고 toInstagram에 어떤 필드가 들어있는지 확인하는 게 불편하고 오류를 유발할 수 있는 부분이라고 생각했습니당

2020-10-09 04:58 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
앗.. placeId가 필요한 이유는 업데이트할때 Instagram에 Place가 null이면 업데이트할때 null로 업데이트 됨니다 ㅠㅠ 그래서 Place Id도가져오고 toInstagram해줄때 id로 Place도 만들어서 넣어주는 것임니다.. dto내에서 Instagram으로 변환하지 않고 로직에서 직접 변경해주면 필드가 한 눈에 보이는 장점이 있겠군요!  다른분들 의견도 들어보고 반영하겠습니다!!

2020-10-09 04:59 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    public List<InstagramForMaker> findAllFetch() {
아주 좋네요 👍

2020-10-09 05:10 UTC, DunDung commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
아 그렇군요! 데이터가많아지면 findAll을 사용하지 않고 하는 방법이 뭐가있을까요?? 타미가 본내용에 대안은 없었나요?? 싱글톤은 DB에 있는 내용이 바뀔가능성 생각하면 위험하지않을까요?? 제가넘 오바하는건가요...

2020-10-09 05:39 UTC, moonyoungCHAE commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
배치에서는 그냥 여러번 쿼리를 찌르더라도 부분적으로 가져오는 걸로 알고 있어요~
바뀔 가능성은 제가 생각을 안 해봤네요! 맞는 말이네요!!!

2020-10-10 10:11 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
음... 그러게요... 확실히 일리가 있는 말인 것 같습니다. 그런데 또 한가지 생각해볼 부분은 core만 db에 접속할 수 있는 구조인데 JPAQueryFactory를 이용한 레포지토리를 각 모듈로 옮기면 그 모듈에서도 db에 접속해버리기 되네요. 이게 딱히 문제가 있는건 아니지만 뭔가 께름칙하기도(개인적인 생각)
그래서 여러가지를 종합적으로 생각했을 때 저의 의견은....
그냥 core에서 해도 될것 같다는 의견입니다.!!

2020-10-10 10:37 UTC, ordinCode commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +    public Instagram toInstagram() {
음... 제 생각에는 애초에 InstagramForUpdate를 불러오는 것부터가 잘못된 거 아닌가 해요.
DTO반환은 조회로직에서만 하는건데 InstagramForUpdate는 이름만 봐도 조회 로직이 아니라 command로직...ㅎㅎㅎㅎㅎ
이건 entity를 반환했어야하는거 같아요.

2020-10-10 10:49 UTC, ordinCode approved these changes
둔덩 고생했습니다~

2020-10-10 10:49 UTC, ordinCode commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
앗 이부분 subBlackList, semiBlackList 이런거 AbnormalInstagram로 바꿨었는데 요기는 놓친 것 같아요.
ABNORMAL_INSTAGRAM_LIST_SIZE로 바꿔주실 수 있나요? 이게 의미가 더 맞는거 같습니다.

2020-10-11 07:29 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
음... 학성의 의견은 지금 당장 어떤 의도인지 모르겠습니다 :)
querydsl의 의존성과 admin, web 모듈의 결합때문에 그런건가요?
지금도 admin, web 모듈이 core 모듈을 의존하고 있고 인터페이스(엔티티별 레포지토리)를 호출해서 데이터베이스에 접근하는 로직을 사용하고 있어서 저는 문제될 것이 없다고 생각합니다.
오히려 구현체가 변경을 받을 수 있는 모듈에 존재하게 되니까 유지보수가 더 용이할꺼 같은데 어떻게 생각하시나요?

2020-10-11 07:49 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
타미! 들어있지 않은 필드를 어떤 객체에서 어떻게 사용할 위험을 생각한건지 설명 한번 해주세요 :)

2020-10-11 09:44 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
전 라빈의견에 한표!

2020-10-11 13:42 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +public class InstagramForUpdate {
toInstagram으로 Instagram 객체를 반환했을 때 예를 들어 hashtagName이나 이런 필드가 온전하다고 생각하고 접근할 수 있지 않냐는 말이었어요~ 저는 학성말대로 dto는 조회로직에서만 사용해도 충분할 것 같네요. 만약 update하는 게 1개 추가되면 그때마다 dto를 변경하는 것도 비효율적인것 같아요!

2020-10-11 13:48 UTC, moonyoungCHAE commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepositoryTest.java
> +    @DisplayName("instagramDto로 필요한 정보만 조회해오기")
화면 출력에 필요한 InstagramDto 조회하기

이런 식으로 하면 어때요

2020-10-11 14:04 UTC, pci2676 approved these changes

2020-10-11 14:04 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    }
생성자 방법중에 `@QueryProjection` 쓰는 방법 참고해보세용

2020-10-11 14:04 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/taglevel/repository/TagLevelQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
포맷팅 확인해주세용

2020-10-12 13:45 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/dto/InstagramForUpdate.java
> +    public Instagram toInstagram() {
흠 command로직에도 dto로 하면 성능향상이 있을것같았는데.,.,
command에서는 entity를 반환하는게 타미말대로 안전하고 좋을 것 같네요!
command로직은 entity를 사용하도록 반영하겠습니다!

2020-10-12 13:46 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    private final JPAQueryFactory jpaQueryFactory;
라빈의 의견대로 반영해보겠슴니다!

2020-10-12 13:54 UTC, DunDung commented on hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
> +        List<Place> places = placeRepository.findAll();
그럼 이부분 어떻게 해결하면 좋을까요? 배치 작업 끝나면 프로그램이 종료되니까 타미 말대로 그냥 BatchWriter에서 상수로 places를 가지고 있어도 괜찮을것같은데 타미 생각은 어때요?

2020-10-12 13:55 UTC, DunDung commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
그거야 어렵지 않죠~~!

2020-10-12 13:56 UTC, DunDung commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepositoryTest.java
> +    @DisplayName("instagramDto로 필요한 정보만 조회해오기")
더 좋은것 같아요. 수정했슴다

2020-10-12 13:58 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramQueryRepository.java
> +    }
@QueryProjection을 사용하면 더 안전하게 가져올 수 있겠군요. 반영하겠슴다 :)

2020-10-16 08:14 UTC, giantim approved these changes
둔덩 면접 준비하는 기간에도 큰 이슈 처리 수고많았습니다! :)

2020-10-16 08:14 UTC, giantim commented on hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/instagram/service/InstagramQueryService.java
> +    public static final int ABNORMAL_INSTAGRAM_LIST_SIZE = 20;
이 값도 나중에 어드민에서 블랙리스트를 관리할 때 20개를 보여주는게 아닌 더 많은 값을 보여주는 식으로 요구사항이 변경된다고 했을 때 클래스 내부에서 관리하는거 보다 다른 상수 값들처럼 프로퍼티에서 관리하는게 더 좋아보이는데 나중에 필요성이 생기면 리팩토링 해봐도 좋을 것 같네요 :)

2020-10-16 08:14 UTC, giantim commented on hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/blacklist/service/BlackListCommandServiceTest.java
> +        final String newHashtagCount = "1000";
[상수는 대문자와 언더스코어로 표기하는게 컨벤션입니다 :)](https://naver.github.io/hackday-conventions-java/#constant_uppercase)

2020-10-18 16:09 UTC, moonyoungCHAE approved these changes
리뷰가 늦어서 미안합니다 😅
1. Dto를 return하는 건 모듈 분리하고 아닌 것은 core에 있도록 한 것 맞나요?
2. 상속구조가 남아있는 게 있어요!!
* InstagramPost
* Place 
  * 이거 지우면 gradle에 추가됐던 것도 지워야 겠네요

너무 너무 고생하셨습니다 !!!!

2020-10-19 08:22 UTC, DunDung commented
InstagramPost는 못봤었네요!! InstagramPost도 수정했슴다
Place는 QueryDsl을 사용하지 않아서 건들지 않았슴다.

2020-10-19 08:32 UTC, merged