[FEAT] Kakao API를 이용한 가게 데이터 수집
woowacourse-teams/2020-songpa-people pull request #37
Opened 2020-07-17 11:12 UTC by giantim

Kakao Api 연동 모듈 구현
- 주어진 범위(사각형)에 대해 가게 데이터를 수집한다.
- 범위 내에서 표현할 수 있는 가게 데이터 수를 초과할 때 범위를 재조정해서 다시 탐색한다.

fixes: #11

2020-07-18 04:12 UTC, ordinCode reviewed
예상보다 힘든 이슈였을텐데 고생많았습니다.
코드를 보면서 의미가 바로바로 다가오지 않는 것들을 서슴없이 적어보았어요. 아마 코드를 짜면서 많이 고민하고 했을텐데 근거가 있다면 설명 달아주시면 좋을 것 같습니다.
수고 많았습니다

2020-07-18 04:12 UTC, ordinCode commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/dto/KakaoPlaceDto.java
> +}
kakaoPlaceDto만 보고는 meta와 doucument가 무엇인지 감이 안왔네요. 각자 무슨 객체인지 들어가보고 알았는데
Meta는 MetaInfo로 바꾸는건 어때요
그리고 Document도 뭔가 애매한 네이밍같은데 PlaceInfo가 더 어울리것도 같습니다.

KakaoPlaceDto는 **위치와 관련된 정보인 PlaceInfo**와 **위치와 관련되지 않은 Meta정보**를 가지고 있는 느낌으로

2020-07-18 04:12 UTC, ordinCode commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +            int pageableCount = firstPage.getMeta().getPageableCount();
```suggestion
            int pageableCount = firstPage.getPageableCount();
```
로 해서 KakaoPlaceDto 안에 getPageableCount()가 있는게 났지 않을까요?
```
public class KakaoPlaceDto {
...
    public Integer getPageableCount() {
            return meta.getPageableCount();
        }
...
}
```

2020-07-18 04:12 UTC, ordinCode commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +}
재귀가 호출되는 것을 보고 더 작은 rect에서 가게를 가져오는 메서드인지 알 수 있었어요.(작은데서 가져오는거 맞죠?)
Rearranged 라는 표현에서 조금 더 의미를 정확하게 하기위해 findPlacesInSmallerRect는 어떤가요?

2020-07-18 04:12 UTC, ordinCode commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/dto/Meta.java
> +    private RegionInfo sameName;
이 sameName이라는게 참 애매하네요.
무슨 변수인지 설명부탁드릴게요. 변수명을 바꿔보는 것도 좋을 것 같습니다.

2020-07-18 05:05 UTC, giantim commented
학성 좋은 의견 감사합니다!
의견 주신 도메인 용어에 관한 내용은 모두 카카오 api 에서 제공하는 도메인 용어를 가져다 사용한 것입니다.

2020-07-19 07:46 UTC, pci2676 requested changes
타미, 라빈 외부 api를 다루는 코드 작성하는게 쉽지 않았을텐데 고생 많으셨습니다!
함께 고민해볼만한 부분에 대해 리뷰를 남겼습니다!
답변을 듣고 싶은 부분이 있어 바로 Approve 하지는 않겠습니다! ㅎㅎ

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoRestTemplateBuilder.java
> +                    public ClientHttpResponse intercept(HttpRequest request, byte[] body,
인터셉터는 익명 클래스를 구현하는 것보다 구체 클래스를 직접 만들어서 사용하는 것이 테스트하기에 용이하고 유지보수하기 더 용이하지 않을까요?

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/exception/KakaoExceptionHandler.java
> +    }
`errorMessages`의 구현 내용이 `ExceptionHandler`에서 알아야하는 내용일까요?
Enum으로 에러 메세지와 코드를 한번에 관리하는 것도 하나의 방법이 될 수 있을것 같아요!

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/exception/KakaoExceptionHandler.java
> +    }
불필요한 공백이 존재하네요!
```suggestion
    public boolean hasError(ClientHttpResponse httpResponse) throws IOException {
        return httpResponse.getStatusCode().series() == CLIENT_ERROR
                || httpResponse.getStatusCode().series() == SERVER_ERROR;
    }
```

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoRestTemplateApiCaller.java
> +    private static final int KAKAO_MAX_PAGEABLE_COUNT = 45;
상수필드가 굉장히 많이 있네요!
물론 설정을 위해서 상수값들이 필요하지만 이러한 상수 값을 상수 필드로 두지않고 상수를 담당하는 Properties로 변경해서 사용하는 방법도 있습니다!
KakaoApi의 key를 `.properties` 파일로 관리한것 처럼 분리해서 관리해보는 방법은 어떨까요?

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/location/Longitude.java
> +        ;
코드 포맷팅 해주세요!

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/test/java/com/songpapeople/hashtagmap/kakaoapi/domain/exception/KakaoExceptionHandlerTest.java
> +    public void badRequestTest(HttpStatus status) {
간혹 비어있는 `@DisplayName`이 보이네요!
테스트 코드는 문서가 될 수 있어야 한다고 생각합니다!
비어있는 부분을 채워주시면 좋을 것 같아요!

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/test/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoServiceTest.java
> +    private void stubServer(Rect rect) throws JsonProcessingException {
메소드 이름만 보고 어떠한 일을 하는지 파악하기가 힘드네요 ㅠㅠ

2020-07-19 07:46 UTC, pci2676 commented on hashtagmap-kakao-api/src/test/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoServiceTest.java
> +    private void stubServer(Rect rect) throws JsonProcessingException {
현재 이 테스트 코드에서 미리 만들어둔 픽스쳐를 많이 사용하는데 
픽스쳐를 한 곳에서만 관리하기보다 사용하는곳이 한곳이라면 해당 테스트 코드 클래스에 같이 둬도 될것 같아요 왔다 갔다 봐야해서 보기가 힘드네요 ㅎㅎ

2020-07-20 07:43 UTC, pci2676 approved these changes

2020-07-20 18:07 UTC, DunDung approved these changes
두 분, 고생하셨습니다... 💯 
시간 부족하셨을 텐데, 깔끔하고 고민을 많이한 게 느껴졌어요.
열심히 코드 보면서 그냥 궁금한 점 느낀 점 전부 적어봤어요.
개인적인 의견일 뿐이니 반영할 게 있다면 선택적으로 반영하시면 됩니다!
테스트 코드는 리팩토링이 끝나면 다시 한 번 천천히 보면서 질문하겠습니다!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/Rect.java
> +    }
트랙방에서 코드리뷰할 때 나왔던 내용 같긴한데! static factory method로 빼면 좋을 것 같아요!
각각의 생성자가 무슨의미인지 알 수 있는 네이밍과 함께요!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/RectDivider.java
> +    }
getter로 꺼내올거면 Rect 객체에게 메세지를 보내는 건 어때요?
RectDivider를 따로 만든 이유가 있다면 알려주세요!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/RectDivider.java
> +    }
마찬가지로 Location에게 메세지를 보내서 비교하는 방식도 괜찮을 것 같아요!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/location/Location.java
> +}
위도와 경도가 다른 forward 메서드를 가져야하는 이유가 뭐였죠??
분명 들었는데 기억이 나지않아요. 미안함니다. 한번 더 설명 부탁해요.

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +                .collect(Collectors.toList());
DividedRects 일급 컬렉션 객체로 서비스 로직을 줄이는 방법도 좋겠어요!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoApiCaller.java
> +public interface KakaoApiCaller {
KakaoApiCaller를 인터페이스로 구현한 이유가 있으신가요?
웹클라이언트로 API가 바뀔 경우 편하게 바꿔끼기 위해서라고 추측해봅니다!
요구사항에 맞는 최소한의 구현을 하는게 좋다고 생각하는 입장에서,
바뀔 가능성이 거의 없어보이는 데 굳이 인터페이스로 할 필요가 있나 싶긴해요!
메서드도 두개라서 인터페이스로 안해도 메서드들이 눈에 들어올 것 같기도 하구요.
생각의 차이니 얘기해볼 가치가 있다고 생각합니다!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoRestTemplateApiCaller.java
> +        int totalCount = kakaoPlaceDto.getMeta().getTotalCount();
디미터 관련해서 이 부분도 수정하실 예정이셨겠지만! 못보실까봐 코멘트남겨용.

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +}
저듀 공감합니다!

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +}
크기가 크면 재귀하는 로직이 핵심로직인데 너무 밑에? 숨겨져있다고 생각해요.
findPlaces에서 부터 검사하고 재귀하면 로직도 많이 줄고 가독성도 향상 될 것 같아요!
```java
    public List<KakaoPlaceDto> findPlaces(String category, Rect initialRect, BigDecimal offset) {
        List<Rect> dividedRects = RectDivider.divide(initialRect, offset);
        List<KakaoPlaceDto> result = new ArrayList<>();
        for (Rect rect : dividedRects) {
            if (kakaoApiCaller.isLessOrEqualTotalCount(rect)) {
                result.addAll(findPlacesInDividedRect(category, rect, offset));
                continue;
            }
            result.addAll(findPlaces2(category, rect, offset.divide(HALF)));
        }
        return result;
    }
```

슥 짠거라 이상할 수도 있습니다!
두 분이 시간이 부족하게 짜셨으니 저 로직을 천천히 다시 생각해볼 필요는 있는 것 같아요!
물론 개인적인 생각일 뿐이에요..

2020-07-20 18:07 UTC, DunDung commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/dto/Document.java
> +    private String distance;
필요한 정보만 가져올 수도 있는건지 궁금합니다!
addressName 이나 roadAddressName 둘 중 하나만 가져와도 되는 거 아닌가요?!?
distance도 굳이 안필요해 보이구요! 
다 필요한건데 제가 모르는걸 수도 있어요 ㅠㅠ 설명부탁드립니다!

2020-07-21 05:36 UTC, ordinCode approved these changes
오프라인 코드리뷰로 인해 approve

2020-07-21 05:37 UTC, moonyoungCHAE approved these changes

2020-07-21 06:09 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/Rect.java
> +    }
```byOffset```이라고 명명해봤어요!

2020-07-21 06:15 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/dto/Document.java
> +    private String distance;
이 모듈은 다른 프로젝트에서도 사용할 수 있는 독립적인 모듈이기 때문에 존재하는 게 좋다고 생각해요.
다른 프로젝트에서는 distance가 필요할 수도 있구요.
필요한 정보만 가져오는 것은 스케줄러에서 Entity로 만들 때 해주면 될 것 같네요 :)

2020-07-21 06:19 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoApiCaller.java
> +public interface KakaoApiCaller {
둔덩 말대로 추상화가 필요한 시점에 추상화하는 게 더 좋을 것 같네요.
interface 제거했습니다 👍

2020-07-21 06:20 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +            int pageableCount = firstPage.getMeta().getPageableCount();
반영했습니다 👍

2020-07-21 06:21 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoRestTemplateBuilder.java
> +                    public ClientHttpResponse intercept(HttpRequest request, byte[] body,
header만 필요한 부분이라 header만 추가하는 것으로 반영했습니다 :)

2020-07-21 06:47 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/exception/KakaoExceptionHandler.java
> +    }
좋은 지적이네요. 반영했습니다~

2020-07-21 06:48 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/test/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoServiceTest.java
> +    private void stubServer(Rect rect) throws JsonProcessingException {
Service 코드를 개선하면서 해당 테스트도 바뀔 것 같아요. 요 부분은 Service 리팩토링하면서 개선하겠습니다 :)

2020-07-21 06:50 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +                .collect(Collectors.toList());
List<Rect>가 메서드 인수나 외부로 노출되는 경우가 없어서 일급 컬렉션으로 감쌀 필요가 없지 않을까요?

2020-07-21 07:49 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +}
개선했어욜~

2020-07-21 07:51 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/location/Location.java
> +}
한 점이 주어졌을 때 우하향 대각선으로 사각형을 만듭니다.
그리고 위도(x)는 증가하고, 경도(y)는 감소하기 때문에 forward의 로직이 다릅니다.
이런 로직을 채택한 이유는 Kakao에서 왼쪽 위, 오른쪽 아래 좌표를 기준으로 format을 받기 때문입니다.

2020-07-21 07:53 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/RectDivider.java
> +    }
반영했어요! 좋은 의견이네요 :)

2020-07-21 07:53 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/caller/KakaoRestTemplateApiCaller.java
> +    private static final int KAKAO_MAX_PAGEABLE_COUNT = 45;
반영 완료 💯

2020-07-21 07:54 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoService.java
> +}
재귀로직이 바뀌면서 해당 네이밍이 사려졌어요. :)

2020-07-21 07:55 UTC, moonyoungCHAE commented on hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/RectDivider.java
> +    }
Rect를 divide하는 것은 Rect의 역할이라고 생각하지 않았어요! 둔덩의 의견은 어떤가요?

2020-07-21 08:03 UTC, merged