[FEAT] vuetify 적용
woowacourse-teams/2020-songpa-people pull request #54
Opened 2020-07-22 11:45 UTC by DunDung

[vuetify 빠른시작](https://vuetifyjs.com/ko/getting-started/quick-start/)에서 vue CLI로 설치하기로 했습니다~
터미널에서 `vue add vutify` 입력 후
App.vue에 KakaoMap 컴포넌트 추가해줬어요.

잘 돌아가는지 확인했슴다.

fixes #45

2020-07-23 00:29 UTC, giantim requested changes
코드 포맷팅이 안되어있네요
확인해주세요 :)

2020-07-23 01:15 UTC, ordinCode approved these changes

2020-07-24 04:48 UTC, moonyoungCHAE reviewed
vuetify 적용하느라 수고하셨어요 :)
잘 작동하네요. 작은 코멘트 남겼습니당

2020-07-24 04:48 UTC, moonyoungCHAE commented on hashtagmap-web/front/babel.config.js
> +  presets: ["@vue/cli-plugin-babel/preset"],
불필요한 쉼표 !

2020-07-24 04:48 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/App.vue
> +
필요없어보여욥

2020-07-24 08:14 UTC, giantim approved these changes

2020-07-24 08:23 UTC, moonyoungCHAE approved these changes

2020-07-24 08:24 UTC, pci2676 approved these changes

2020-07-24 08:31 UTC, DunDung commented on hashtagmap-web/front/babel.config.js
> +  presets: ["@vue/cli-plugin-babel/preset"],
prettier 적용했더니 자동으로 생겼어요! 원래 있는게 맞는가봐요.

2020-07-24 08:31 UTC, DunDung commented on hashtagmap-web/front/src/App.vue
> +
vuetify가 자동으로 생성해준 거라서 일단 납둘게요!

2020-07-24 08:31 UTC, merged