[FEAT] 가게 정보에 따라 핀 그리기
woowacourse-teams/2020-songpa-people pull request #55
Opened 2020-07-23 01:08 UTC by giantim

font/src/plugins/KakaoMap.js 에 mock 데이터를 하드코딩으로 추가해서 지도에 해당 데이터에 맞게 핀이 그려지는지 확인했습니다.
추후에 core, scheduler 설계가 어느정도 완성되면 web 모듈에 컨트롤러, 서비스 계층을 만들고 실제 데이터베이스에서 데이터를 가져와 지도에 표시해주도록 변경해야 합니다.

fixes: #13

2020-07-23 04:06 UTC, ordinCode approved these changes

2020-07-23 05:47 UTC, pci2676 requested changes

2020-07-23 05:47 UTC, pci2676 commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +    Vue.prototype.$loadCurrentPosition = async () => {
이 메서드도 async가 필요해???

2020-07-23 17:16 UTC, moonyoungCHAE reviewed
라라랜드!
핀 그리기 구현하느라 수고하셨습니다.
데이터까지 만들어서 구현하느라 고생했겠네요.
잘 나옵니다 ! 👍 몇 가지 코멘트 달았으니 확인해주세요 ^____^

2020-07-23 17:16 UTC, moonyoungCHAE commented on hashtagmap-web/build.gradle
> +    implementation project(':hashtagmap-core')
요기는 상관없어보이네요

2020-07-23 17:16 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +          displayPlaceMarker.call(this);
"loadCurrentPosition"보다는 place만 찍어주는 메서드로 분리하는 게 어떨까요?

2020-07-23 17:16 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +    const displayPlaceMarker = () => {
1. api call을 부르고 메서드를 분리하면,  parameter로 places를 받게 되지 않을까요?
parameter로 places를 받아보면 어떨까요

2. 나중에 server쪽 만들면 없어질 데이터이긴 하지만 ㅠㅠ 보기가 너무 어렵네요.
데이터는 다른 파일로 빼는 게 어떨까요

2020-07-23 17:16 UTC, moonyoungCHAE commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +          title: "나나쓰",
place가 class로 있으면 데이터 관리가 쉽지 않을까요?

2020-07-25 08:13 UTC, giantim commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +    Vue.prototype.$loadCurrentPosition = async () => {
테스트 해보다가 실수로 남겨두었습니다.
지웠습니다아~!

2020-07-25 08:15 UTC, giantim commented on hashtagmap-web/build.gradle
> +    implementation project(':hashtagmap-core')
왜 그렇게 생각하시는지 궁금하네요!
core의 의존성에 대해서 지금 참조를 할 필요가 있나요?

2020-07-25 08:15 UTC, giantim commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +          displayPlaceMarker.call(this);
독립적인 메서드로 분리했습니다 :)

2020-07-26 00:31 UTC, pci2676 approved these changes
수고하셨습니다 :)

2020-07-26 15:18 UTC, DunDung approved these changes
고생하셨습니다. 💯

2020-07-26 15:18 UTC, DunDung commented on hashtagmap-web/front/src/plugins/KakaoMap.js
> +    };
api call하는 로직이 추가되면 메서드를 보기 좋게 분리할 필요는 있어보이네요!
로직이 추가될 때 같이 고민해보아요.

2020-07-27 05:32 UTC, moonyoungCHAE approved these changes

2020-07-27 05:35 UTC, merged