[FEAT] Kakao API를 활용한 가게 데이터 수집 스케줄링
woowacourse-teams/2020-songpa-people pull request #65
Opened 2020-07-27 05:32 UTC by giantim

Kakao Api를 활용한 스케쥴러를 구현했습니다.
Spring boot Scheduler 를 활용해서 별도의 스레드에서 동작합니다.
추후에 스레드 풀 사이즈를 최적화해서 성능 개선할 것입니다.

fixes: #18

2020-07-27 11:16 UTC, pci2676 requested changes
고생많으셨습니다 타미, 라빈!
Config 클래스는 정말 잘 만드신것 같아요!
비동기적인 테스트 부분에 대해 피드백을 남겼으니 반영해주시면 될 것 같아요!

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/District.java
> +@AllArgsConstructor
다른곳은 @Allarg안 쓰고 구현한곳도 있던데 일관성있게 롬복은 최대한 안쓰는 방향으로 하는게 좋을것 같아요

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +@NoArgsConstructor
접근제어자를 PROTECET로 안하면 이슈 있나요?

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +    @Generated
이거 롬복 어노테이션이던데 필요한건가요?

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +                && Objects.equals(roadAddressName, location.roadAddressName);
해당필드 직접 접근보다 getter를 이용한 접근이 더 안정성이 있어보입니다!

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +        return Objects.hash(point, roadAddressName);
equals와 동일합니다!

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/place/domain/repository/ZoneRepositoryCustomImplTest.java
> +        zoneRepository.saveAll(Arrays.asList(zone1, zone2, zone3));
save 하는 로직이 있으면
```java
    @AfterEach
    void tearDown() {
        
    }
```
내부에 repository.deleteAll 메서드를 꼭 추가해주세요

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +    public void collectData() {
save 하는 로직인데 @Transaction이 붙어있는게 안전하지 않을까요?

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoScheduler.java
> +    private final KakaoSchedulerTask kakaoSchedulerTask;
이 부분을 interface로 도출하면 테스트가 좀더 유연해 질수 있을것 같아요!

2020-07-27 11:16 UTC, pci2676 commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/acceptance/SchedulerAcceptanceTest.java
> +                    }
걷어낼수 있도록 테스트를 고쳐주시면 좋을 것 같아요!

2020-07-27 13:03 UTC, ordinCode requested changes
이번에도 너무 고생많았으👍

2020-07-27 13:03 UTC, ordinCode commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskTest.java
> +    }
테스트 실패하는데 저만 그런가요?

2020-07-27 13:03 UTC, ordinCode commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +        placeRepository.saveAll(places);
void 메서드인데 너무 많은 역할을 하는것 같네요
RectFactory.from(zones)가 일급 컬렉션 Rects를 만들어서 kakaoPlaceDtos를 만드는 역할을 Rects가 하면 어떨까 합니다.

아마 이런 식이 될것 같네요
~~~java
    public void collectData() {
        List<Zone> zones = zoneRepository.findByActivated();
        Rects rects = new Rects(RectFactory.from(zones));

       //경우에 따라서는 아래 documents도 rects에서 만들어주는건 어떨지 고려해봐도 좋구요
        List<KakaoPlaceDto> kakaoPlaceDtos = rects.toKakaoPlaceDtos(kakaoApiService);

        Set<Document> documents = kakaoPlaceDtos.stream()
                .flatMap(kakaoPlaceDto -> kakaoPlaceDto.getDocuments().stream())
                .collect(Collectors.toSet());
        List<Place> places = PlaceFactory.from(documents);

        placeRepository.saveAll(places);
    }
~~~

Rects.java
~~~java
public class Rects {
    private final List<Rect> rects;

    public Rects(List<Rect> rects) {
        this.rects = rects;
    }

    public List<KakaoPlaceDto> toKakaoPlaceDtos(KakaoApiService kakaoApiService) {
        return rects.stream()
                .map(rect -> 메서드이름은알아서(rect, kakaoApiService))
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
    }

    private List<KakaoPlaceDto> 메서드이름은알아서(Rect rect, KakaoApiService kakaoApiService) {
        return Arrays.stream(Category.values())
                .map(category -> kakaoApiService.findPlaces(category.getCategoryGroupCode(),rect))
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
    }
}
~~~

이렇게되면 테스트도 가능해지고 여러모로 났지 않을까요?

2020-07-27 13:03 UTC, ordinCode commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +import java.util.ArrayList;
사용하지 않고 있네요

2020-07-27 13:05 UTC, ordinCode requested changes
.

2020-07-28 05:05 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskTest.java
> +    }
혹시 key 추가하셨나요?

2020-07-28 05:06 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +import java.util.ArrayList;
사용하고 있는 중입니다~ 학성이 코드 수정하다가 빠졌나봐요!

2020-07-28 05:11 UTC, DunDung approved these changes
고생하셨습니다. 라빈, 타미 💯 
제 눈에는 리뷰할 게 별로 없었어요. 👍

2020-07-28 05:11 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Category.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하는 않는 카데고리 코드입니다."));
카데고리 오타있씁니다!

2020-07-28 05:11 UTC, DunDung commented on hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskTest.java
> +    }
저도 실패하네요.

2020-07-28 05:11 UTC, DunDung commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +    public List<KakaoPlaceDto> findPlacesByRect(Category category, Rect rect) {
private 메서드로 하지 않은 이유가있나요??!?

2020-07-28 05:11 UTC, DunDung commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/config/KakaoSchedulerConfig.java
> +        PeriodicTrigger trigger = new PeriodicTrigger(30, TimeUnit.DAYS);
인텔리제이에서는 파라미터 네임이 보여서 괜찮지만 30을 상수로 두는 것이 좋아보여요.
물론 이 경우엔 매직넘버로도 충분히 의미 파악이 가능하지만 상수면 쪼금 더 파악하기 쉬울 것 같아요.

2020-07-28 05:15 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +    @Generated
jacoco test coverage에서 제외하고자 달았습니다~ 회의 때 공유했던 내용이에요. ^ㅋ^

2020-07-28 05:36 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Location.java
> +                && Objects.equals(roadAddressName, location.roadAddressName);
getter가 필요한 이유가 lazy loading 에서 proxy 관련 이슈 맞나요?

2020-07-28 06:32 UTC, moonyoungCHAE commented on hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
> +        placeRepository.saveAll(places);
학성 말대로 해당 메서드에 많은 책임이 있는 것 같아요. 일급 컬렉션으로 객체를 포장하는 것은 좋지만, 일급 컬렉션에서 api call을 쏘는 것은 조금 책임이 맞지 않다는 생각이 들었어요.
당장 좋은 방법을 찾지 못해 요거는 refactoring 이슈로 빼도록 하겠습니다.

2020-07-28 06:36 UTC, moonyoungCHAE commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/District.java
> +@AllArgsConstructor
@Allarg 사용하지 않은 곳은 Builder 때문에 생성자로 구현했습니다!

2020-07-28 06:37 UTC, moonyoungCHAE approved these changes
페어로 approve 🥇

2020-07-28 07:32 UTC, pci2676 approved these changes
이만 Approve 하겠습니다!
고생 하셨습니다!

2020-07-28 09:32 UTC, ordinCode approved these changes
고생했으요

2020-07-28 10:02 UTC, merged