[FEAT] 인스타그램 크롤링 스케줄링 구현
woowacourse-teams/2020-songpa-people pull request #68
Opened 2020-07-27 10:54 UTC by ordinCode

db에서 가게 이름정보를 받아와 인스타그램 크롤링을 하여 다시 db에 저장하는 기능을 구현했습니다.

2020-07-27 10:57 UTC, DunDung approved these changes
페어프로그래밍했기 때문에 Approve 할게요 👍

2020-07-27 12:24 UTC, pci2676 requested changes
고생하셨습니다. 둔덩, 학성!
궁금한 부분들에 대해, 같이 고민해 보고 싶은 부분에 대해 리뷰 남겼습니다!

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-common/src/main/java/com/songpapeople/hashtagmap/exception/HashtagMapException.java
> +    // TODO: 2020-07-27 super 안해도되나?
이제 불필요한 주석아닌가요???

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-core/build.gradle
> +    compile 'org.springframework.boot:spring-boot-starter-data-jpa'
JPA 의존성을 스케쥴러 모듈을 사용하는 다른 모듈에게 흘려보낼 필요가 있나요?

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramSchedulerTest.java
> +        placeRepository.saveAll(places);
saveAll 하는 부분이 있으면 
```java
    @AfterEach
    void tearDown() {
        
    }
```
에 deleteAll 하는 메서드도 같이 추가해주세요~

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramSchedulerTest.java
> +    }
prefix 한 데이터가 있으면 분명 중복되는 데이터를 줄일수 있어 편합니다.
그런데 prefix 데이터에 현재 테스트 클래스 전체가 의존하게 될 수 있다는 문제점이 발생할 수 있습니다.
앞으로 현재 테스트 클래스에 항상 prefix 데이터가 2개 필요한 테스트를 작성할 게 아니라면 prefix한 데이터는 만들지 않는게 좋다고 생각되는데요!
어떻게 생각하시나요?

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> +    }
DB에 WRITE 하는 작업이 있다면 `@Transactional` 을 붙이는게 안전하지 않을까요?

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +                new ProxySetter(ProxiesFactory.create()), new InstagramCrawler());
매번 `new InstagramCrawler()` 할 필요가 있나요?
InstagramCrawler는 Bean으로 만들고 사용해도 될 것 같아요!

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
이 부분에서 재귀를 사용해서 크롤링 재시도를 하는 이유는 뭔가요??

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
크롤링 결과 존재하지 않는 HashTag인 경우 Exception을 발생시키는 방법도 있지만
내용물이 비어있는 CrawlingResult를 반환하는 방법에 대해서는 어떻게 생각하시나요?
이 메서드를 사용하는 쪽에서 Optional로 만들어서 반환하고 isPresent로 필터링을 하는 부분을 보고 리뷰를 남깁니다!

물론 옵셔널을 사용하는 방법도 있겠지만 저는 비어있는 CrawlingResult를 만들어서 반환하고
필터링을 할때 CrawlingResult가 비어있는지 확인하는 메소드를 사용하는게 더 자연스러워 보일 것 같다는 생각을 했거든요!

2020-07-27 12:24 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlingResult.java
> +    private void validateLessMinHashtagCount(CrawlingDto crawlingDto) {
CrawlingResult 라는 클래스만 봐서는 이 객체가 반드시 100개 이상의 해시태그를 가진 정보만 들고 있을 거라는 생각이 들지 않았어요.
CrawlingResult 는 단순히 크롤링 정보만 전달해 주면 안되는 걸까요? 100개 미만의 해시태그 정보를 가진 객체를 CrawlingResult 을 사용하는 쪽에서 필털이 해주는건 좋지 않을까요? 궁금하네요!

2020-07-27 12:57 UTC, giantim requested changes
둔덩! 학성! 스케쥴링 모듈 구현하느라 고생 많으셨습니다!
질문 위주의 피드백 남겼습니다. 확인하시고 답변 주세요 :)

2020-07-27 12:57 UTC, giantim commented on hashtagmap-core/src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.H2Dialect
변경하신 이유가 있나요?

2020-07-27 12:57 UTC, giantim commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/CoreApplicationTest.java
> +public class CoreApplicationTest {
hashtagmap-core 모듈에 관련된 테스트가 없어서 필요 없지 않을까요?

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/exception/CrawlerExceptionStatus.java
> +    NOT_ENOUGH_POPULAR_POST(String.format("인기게시물이 %d개 미만입니다.", PostDtos.POPULAR_POST_SIZE), "crawler_1002"),
enum에서 굳이 PostDtos의 상수를 알게하신 이유가 무엇인가요?
만약 포스트의 수가 9개에서 변경이 된다면 PostDtos 클래스만 수정하려고 하신건가요?

제가 생각할때는 여기서 내려주는 예외는 admin에서 우리가 수집할 예외이기 때문에 명시적으로 인기게시물의 개수를 보여주지 않아도 된다고 생각합니다.

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataReader.java
> +    protected String createBody() {
테스트 클래스가 상속받아서 createBody() 메서드를 사용하고 있는데 이렇게 설계하신 이유가 있을까요?
저는 이 클래스 이름이 MockDataReader 여서 static 메서드를 갖고 있을줄 알았습니다.
테스트 클래스들이 상속받기에는 클래스 이름이 애매한것 같아요 :)

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/RegexPatternTest.java
> +                .isInstanceOf(CrawlerException.class);
포함하는 메세지를 검사하는 부분을 추가하지 않은 이유가 있을까요?

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +            proxySetter.set();
내부 기능을 더 드러내는 메서드 명으로 바꾸면 이해하기 좋을 것 같아요!

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        } catch (CrawlerException e) {
catch 에 InstagramSchedulerException 이 아닌 CrawlerException 으로 잡은 이유가 있나요?
new CrawlingResult 를 호출할 때 인자로 넘겨주는 메서드 결과에서만 예외가 발생하는 건가요?

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
> +    // TODO: 2020/07/24 crawler클래스에서 검색결과는 없는 것 예외처리 테스트
이제 완료된 todo 아닌가요? :)

2020-07-27 12:57 UTC, giantim commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/Instagram.java
> +public class Instagram extends BaseEntity {
엔티티 명이 데이터를 대표한다는 느낌이 없는것 같습니다.
InstagramPost에 공통으로 포함되는 데이터이니 ```MetaInstagram``` 과 같은 엔티티 명으로 바꿔보는 것은 어떨까요?

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
> +                .isInstanceOf(InstagramSchedulerException.class);
위에도 비슷한 피드백 남겼습니다 :)

2020-07-27 12:57 UTC, giantim commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/SchedulerTestResource.java
> +    protected static PostDtos createPostDtos() {
instagram-crawler 모듈에서도 남겼지만 mock 데이터를 만드는 클래스를 상속 받아서 구현하신 이유가 궁금하네요 :)
여기는 static 메서드로 만든 후 protected 로 접근 제어자를 단 다음에 클래스를 상속하신 이유가 궁금합니다.

2020-07-27 12:59 UTC, giantim commented on hashtagmap-core/build.gradle
> +    compile 'org.springframework.boot:spring-boot-starter-data-jpa'
코어 모듈에서는 상위로 jpa 의존성을 전파했지만 스케쥴러 모듈에서는 코어 모듈을 implementation 으로 의존하기 때문에
스케쥴러 모듈을 사용하는 모듈에서는 jpa 의존성을 알 수 없지 않을까요? :)

2020-07-27 13:12 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
인스타그램 크롤링할때 예외가 발생하는 경우가 2가지 있습니다.
~~~
1. 설정해준 프록시에 문제가 있는 경우
2. 해당 검색어의 인스타그램 결과가 없는경우
~~~

3번동안 크롤링을 시도했는데 계속 예외가 생겼다는 것은 위의 2번에 해당하는 문제이기 때문에 이를 구분하기 위해서 그렇게 했습니다😃

2020-07-27 13:17 UTC, ordinCode commented on hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/CoreApplicationTest.java
> +public class CoreApplicationTest {
InstagramSchedulerTest에서 repository를 사용하기때문에 필요한 것 같아요

2020-07-27 13:18 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/exception/CrawlerExceptionStatus.java
> +    NOT_ENOUGH_POPULAR_POST(String.format("인기게시물이 %d개 미만입니다.", PostDtos.POPULAR_POST_SIZE), "crawler_1002"),
음.. 알려줘도 상관없지 않을까요? 귀찮아서 문제지 가능하면 알려주는게 더 좋다고 생각하는데

2020-07-27 13:19 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
고민해볼게요

2020-07-27 13:23 UTC, ordinCode commented on hashtagmap-core/src/main/resources/application.yml
> +        dialect: org.hibernate.dialect.H2Dialect
아 수정했습니다!

2020-07-27 13:30 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
> +    // TODO: 2020/07/24 crawler클래스에서 검색결과는 없는 것 예외처리 테스트
이거는 인스타 크롤러 모듈의 Crawler.java 의 테스트입니다:)

2020-07-27 13:49 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
혹시 그러면 1번의 문제가 3번이상 발생할 가능성도 있는건가요???

2020-07-27 13:51 UTC, pci2676 commented on hashtagmap-core/build.gradle
> +    compile 'org.springframework.boot:spring-boot-starter-data-jpa'
core를 사용하는 모든 모듈에서 jpa 기능을 필요로 할까? 라는 생각을 해봣어요! 
그런 경우가 없다면 compile로 두는게 맞을것 같네요!

2020-07-27 13:51 UTC, pci2676 commented on hashtagmap-core/build.gradle
> +    compile 'org.springframework.boot:spring-boot-starter-data-jpa'
그리고 코어가 아니라 스케쥴러로 착각했네요 ㅋㅋㅋㅋㅋ

2020-07-28 00:51 UTC, moonyoungCHAE reviewed
둔덩 학성 인스타그램 크롤링 스케줄러 구현하느라 수고하셨어요!! :)
몇 가지 코멘트 남겼으니 참고해주세요 ^___^

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/InstagramSchedulerApplicationTest.java
> +    void contextLoads() {
이 메서드가 없어도 테스트가 다 통과해요.
@SpringBootApplication만 붙여도 컴포넌트 스캔이 가능합니다 :)

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +    public CrawlingResult instagramCrawling(Place place, int tryCount) {
메서드 네이밍은 동사로 하는 게 어떨까요
```crawlInstagram```을 추천할게요.

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
> +    public CrawlingDto crawling(String placeName) {
요기도 메서드이기 때문에 동사로 crawl으로 하면 어떨까요?

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/ProxySetter.java
> +        proxies.setHostAndPort(random.nextInt(size));
proxies.setHostAndPort() 에서 proxies 중 random으로 proxy를 설정해준다면
외부에서 proxies의 size을 알지 않아도 될 것 같아요

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramSchedulerTest.java
> +    void update() {
@DisplayName 달아주세욥!

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataReader.java
> +            while (true) {
while(fileReader.read() != -1) {
..
}
이런 식으로 바꾸면 어떨까요?
개인적으로 while(true)를 선호하지 않아서!

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
>  public class InstagramCrawler {
InstagramCrawler 와 Crawler가 있으니 둘이 마치 상속 관계인 것처럼 느껴졌어요!
실제로 크롤링하는 부분은 Crawler이니, InstagramCrawler를 다른 네이밍으로 하거나
Crawler를 추상 클래스로 만들어서 createUrl 부분을 빼거나 하는 식으로 수정하면 어떨까요?

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> +    private List<InstagramPost> getInstagramPosts(List<Place> places) {
CrawlingResult를 InstagramPost로 바꾸는 것은 스케줄러의 역할일까요?! 따로 분리하면 어떨까요? :)

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
1. 재귀 대신 1, 2 에러를 각각 잡아줄 수는 없나요? 그러면 로직이 더 명확해질 것 같아요!
2.  
```
 public CrawlingResult instagramCrawling(Place place){
  return instagramCrawling(place, 0); 
```
을 만들면 의도치않은 tryCount 입력을 막을 수 있겠네요.

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstaCrawlingResultTest.java
>          String hashTagCount = instaCrawlingResult.findHashTagCount();
1. InstaCrawlingResult에 static 메서드를 만들고
2. hashtagCount와 postDto를 모두 들고 있는 CrawlingDto를 반환하면 어떨까요?

이유는 2가지 정보는 굉장히 연관성이 크고 자주 사용할 것 같아서 static을 생각했어요~

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +@Component
@Service가 더 적절할 것 같아요.

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +public class CrawlerWithProxy {
Proxy를 바꿔가며 크롤링을 해주는 역할은  instagram-crawler 모듈에 넣는 게 더 어울리지 않을까 생각했어요.
요청만 보내면 instagram-crawler 모듈에서 알아서 proxy를 바꿔가며 크롤링해준다면 어떨까요?

2020-07-28 00:51 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> +        instagramPostRepository.saveAll(instagramPosts);
포스트가 갱신되지 않고 쌓이고 있어요!

2020-07-28 03:51 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
1번의 문제가 3번 이상 발생할 가능성은 있습니다.. 하지만 굉장히 희박한 확률이에요.
300개가 넘는 프록시 중 안되는 프록시는 몇 안되기 때문에 3번이면 충분히 프록시문제와 검색 결과가 없는 경우를
구분할 수 있을 겁니다!

에러를 각각 잡는 건 크롤러 쪽에서 프록시 때문에 발생하는 예외인지 검색 결과가 없는 예외인지
구분할 방법이 없어서 힘들 것 같네요 ...

2020-07-28 03:58 UTC, DunDung commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/RegexPatternTest.java
> +                .isInstanceOf(CrawlerException.class);
시간이 부족해서 나중에 추가하기로 했었어요. 추가하도록 하겠습니다.

2020-07-28 04:01 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        } catch (CrawlerException e) {
네 맞아요. instagramCrawler.crawling에서 발생하는 예외를 잡기 위함입니다.

2020-07-28 04:02 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/InstagramSchedulerApplicationTest.java
> +    void contextLoads() {
좋은 정보 감사합니다.

2020-07-28 04:02 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +    public CrawlingResult instagramCrawling(Place place, int tryCount) {
맞네요, 수정할게요.

2020-07-28 04:04 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/ProxySetter.java
> +        proxies.setHostAndPort(random.nextInt(size));
proxies에서 random을 생성하면 테스트를 하기 어려워지기 때문에
외부에서 size로 랜덤을 생성해주는 방식을 선택했는데요.

어떻게 생각하시나요??

2020-07-28 04:08 UTC, DunDung commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstaCrawlingResultTest.java
>          String hashTagCount = instaCrawlingResult.findHashTagCount();
맞는 말씀인 것 같아요~ 고민해보겠습니다.

2020-07-28 04:12 UTC, DunDung commented on hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataReader.java
> +            while (true) {
넵 수정하겠습니다 ㅎㅎㅎ

2020-07-28 04:37 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +        }
프록시가 사용가능한지 ping으로 확인하는 방법을 사용하는건 어떨까요?
사용가능한 프록시를 이용해서 크롤링을 하는게 맞을것 같다는 생강기 들어요!
한가지 메서드가 가능한지 가능하지 않은지 판단하지 못하기 때문에 3번의 호출하는건 조금 이상하다는 생각이 드네요..!

2020-07-28 04:37 UTC, pci2676 commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/exception/CrawlerExceptionStatus.java
> +    NOT_ENOUGH_POPULAR_POST(String.format("인기게시물이 %d개 미만입니다.", PostDtos.POPULAR_POST_SIZE), "crawler_1002"),
지금 봤는데 상수 코드인 carwler는 전부 대문자로 작성하는게 낫지 않을까요?

2020-07-28 05:56 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +                new ProxySetter(ProxiesFactory.create()), new InstagramCrawler());
일단은 InstagramCrawler가 있는 모듈에 Spring의존성이 없고, 그것 때문에 spring의존성을 달아주는것도 좀 무겁다고 생각해서

~~~java
private final InstagramCrawler instagramCrawler = new InstagramCrawler();

public List<CrawlingResult> createCrawlingResult(List<Place> places) {
    CrawlerWithProxy crawlerWithProxy = new CrawlerWithProxy(
            new ProxySetter(ProxiesFactory.create()), instagramCrawler);
~~~

이런식으로 변경했습니다.

2020-07-28 06:50 UTC, DunDung commented on hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/InstagramSchedulerApplicationTest.java
> +    void contextLoads() {
contextLoads 메서드가 명시의 의미가 있기때문에 남겨두는 것이 나을 것 같아요.

2020-07-28 07:13 UTC, DunDung commented on hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/Instagram.java
> +public class Instagram extends BaseEntity {
MetaInstagram도 모호해서 Meta라는 단어가 있으나마나 한 것 같다는 생각이 들어요.
조금 더 고민해봐야될 것 같습니다... 회의 때 논의하는 것도 괜찮다고 생각해요.

2020-07-28 07:53 UTC, ordinCode commented on hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstagramCrawler.java
>  public class InstagramCrawler {
오호 그런 방법도 좋네요. 일단 전체적인 로직을 바꾸는것도 좋은것 같은데 너무 큰 일이될것 같아 추후 이슈따서 해야할것 같습니다.
일단 지금은 네이밍만 바꿔보도록할게요

2020-07-28 07:57 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> +    private List<InstagramPost> getInstagramPosts(List<Place> places) {
CrawlingResult를 InstagramPost로 바꾸는 toInstagramPosts를 말씀하시는건가요?
toInstagramPosts는 CrawlingResult의 메서드인데 정확히 어떤말씀이신지ㅎㅎㅎ

2020-07-28 08:04 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +public class CrawlerWithProxy {
인스타그램 크롤러는 말그래도 크롤러라서 프록시를 알 필요는 없을 것 같아요

2020-07-28 08:05 UTC, ordinCode commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduler.java
> +        instagramPostRepository.saveAll(instagramPosts);
오호 맞네요 일단 deleteAll을 추가해놓았습니다.
추후 갱신방법은 같이 의논해봐요

2020-07-28 08:42 UTC, giantim approved these changes
전체적인 의견 반영 잘해주셔서 감사합니다~~ 👍

2020-07-28 11:56 UTC, pci2676 approved these changes
고생하셨습니다!

2020-07-28 15:08 UTC, pci2676 commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
> +                new ProxySetter(ProxiesFactory.create()), new InstagramCrawler());
그렇네요 스프링 의존성이 없다고 생각하지 못했어요! 싱글톤으로 만들고 사용하면 되네요!
고생하셨습니다!

2020-07-29 04:08 UTC, moonyoungCHAE approved these changes
수정하느라 수고하셨습니다~

2020-07-29 04:09 UTC, moonyoungCHAE commented on hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
> +public class CrawlerWithProxy {
개인적으로 크롤러에 프록시가 들어가는게 낫다고 생각해요.
스케줄러는 말그대로 크롤러를 호출해주고, 인스타그램 크롤링 특성상 프록시를 바꾸기 때문에

2020-07-29 05:04 UTC, merged